'use client'

import Link from 'next/link'
import { ArrowRight, CheckCircle2, ClipboardCheck, FolderTree, ShieldCheck } from 'lucide-react'
import styles from './CinematicLandingPage.module.css'

const workflow = [['01','Define','Requirements and constraints'],['02','Resolve','Parts, symbols, footprints and pin maps'],['03','Build','Schematic, placement and routing'],['04','Validate','ERC, DRC and manufacturing checks'],['05','Approve','Review the candidate before publishing']] as const
const comparison = [
  ['ENGINEERING CORE','','',''],['Requirements capture','●','●','●'],['Component binding','●','●','●'],['Schematic and PCB generation','●','●','●'],['ERC, DRC and KiCad export','●','●','●'],['Manufacturing package','●','●','●'],
  ['ADVANCED ENGINEERING','','',''],['Requirements Intelligence','—','●','●'],['Candidate comparison and evidence history','—','●','●'],['Advanced routing and differential pairs','—','●','●'],
  ['COLLABORATION','','',''],['Shared projects and libraries','—','—','●'],['Comments, review gates and approvals','—','—','●'],['Role-based permissions and activity history','—','—','●'],
] as const

function Brand() { return <Link href="/" className={styles.brand}><b>BF</b><span>BoardForge</span></Link> }
function Header() { return <header className={styles.header}><Brand/><nav><a href="#product">Product</a><a href="#workflow">Workflow</a><a href="#resources">Documentation</a><a href="#pricing">Pricing</a><a href="#company">Company</a></nav><div><Link href="/login">Sign in</Link><Link className={styles.primary} href="/signup">Get Started <ArrowRight size={15}/></Link></div></header> }

function ProjectEvidence() { return <div className={styles.projectEvidence}><div className={styles.projectBar}><span>Industrial Ethernet Controller</span><code>Candidate 04 · DEMONSTRATION FIXTURE</code></div><div className={styles.boardFrame}><img src="/images/boardforge-production-pcb-hero.png" alt="Industrial Ethernet controller PCB candidate"/><aside><label>VALIDATION</label><b><CheckCircle2/> ERC 0 errors</b><b><CheckCircle2/> DRC 0 violations</b><b><CheckCircle2/> 0 unconnected</b><label>COMPONENT BINDING</label><code>18/18 verified</code><code>W5500 · MPN verified</code><label>OUTPUTS</label><code>kicad · gerber · drill</code><code>BOM · CPL · manifest</code></aside></div><div className={styles.evidenceFooter}><span><ShieldCheck size={14}/> Source protected</span><span><ClipboardCheck size={14}/> Candidate awaiting approval</span><code>SHA256: 96a1…7de4</code></div></div> }

function Hero() { return <section className={styles.hero} id="product"><div><p className={styles.kicker}>LOCAL-FIRST PCB ENGINEERING</p><h1>From requirements to a manufacturing-ready <em>KiCad project.</em></h1><p className={styles.lead}>BoardForge turns a design brief into an editable schematic, PCB, sourced BOM, validation record, and manufacturing package—while keeping every proposed change reviewable.</p><p className={styles.actions}><Link className={styles.primary} href="/new-board">Start a Board <ArrowRight size={16}/></Link><a href="#workflow">View the Workflow</a></p><ul className={styles.trust}><li>Local-first execution</li><li>KiCad-native output</li><li>Live supplier evidence</li><li>User-approved changes</li></ul></div><ProjectEvidence/></section> }

function Workflow() { return <section className={styles.workflow} id="workflow">{workflow.map(([n,t,d],i)=><article key={t}><code>{n}</code><div><b>{t}</b><span>{d}</span></div>{i<4&&<i/>}</article>)}</section> }

function Workspace() { return <section className={styles.workspace}><div className={styles.workspaceScreen}><header><span>BoardForge / Industrial Ethernet Controller</span><code>Candidate 04</code><b>DRC clean</b></header><div><aside><small>PROJECT</small><b>Industrial Ethernet Controller</b><small>DESIGN</small><span>Schematic</span><strong>PCB layout</strong><span>Validation</span><span>Evidence</span></aside><main><div><span>F.Cu</span><code>U1 W5500</code><code>J1 MagJack</code><code>R12 49.9Ω</code></div><img src="/images/boardforge-production-pcb-hero.png" alt="Populated BoardForge PCB workspace demonstration fixture"/></main></div></div><div className={styles.workspaceNotes}><h2>A real engineering workspace, not a one-shot generator.</h2><p>BoardForge creates editable candidates, preserves the original project, and exposes every validation result before anything is approved.</p><ol><li>Candidate-based editing</li><li>Protected source project</li><li>Live validation feedback</li><li>Exact component bindings</li><li>KiCad-native serialization</li></ol></div></section> }

function Evidence() { return <section className={styles.evidence} id="resources"><div><h2>Every important decision stays inspectable.</h2><p>Requirements, part selection, validation results, and manufacturing outputs remain attached to the candidate instead of disappearing inside a generated result.</p><dl><div><dt>ERC</dt><dd><b>0</b> errors <span>0 warnings</span></dd></div><div><dt>DRC</dt><dd><b>0</b> violations <span>0 unconnected</span></dd></div><div><dt>Bindings</dt><dd><b>18</b> verified <span>0 unresolved</span></dd></div><div><dt>Manufacturing</dt><dd>BOM/CPL parity <span>manifest verified</span></dd></div></dl></div><div className={styles.sourceTable}><header><span>Ref</span><span>Requirement</span><span>Evidence</span><span>Status</span></header><p><code>U1</code><span>Ethernet controller<br/><b>W5500</b></span><span>Package + pin map verified</span><strong>Passed</strong></p><p><code>J1</code><span>RJ45 MagJack<br/><b>Exact MPN</b></span><span>Symbol and footprint bound</span><strong>Passed</strong></p><p><code>R12</code><span>49.9 Ω 1%<br/><b>0603</b></span><span>Value + package verified</span><strong>Passed</strong></p><small>Demonstration fixture; supplier evidence is displayed only when provider data is available.</small></div></section> }

function Outline() { return <section className={styles.outline}><div><p className={styles.kicker}>MECHANICAL WORKFLOW</p><h2>Mechanical constraints become real board geometry.</h2><p>Custom Board Generator keeps the outline editable while it records Edge.Cuts geometry, mounting holes, routeability and manufacturing risk before a KiCad project is created.</p><ul><li>Selectable points, fillets and connector relief</li><li>Mounting-ear and keep-out geometry</li><li>Routeability and manufacturing-risk checks</li><li>KiCad Edge.Cuts handoff</li></ul><Link href="/custom-board-generator">Open Custom Board Generator <ArrowRight size={15}/></Link></div><figure><img src="/images/boardforge-outline-workflow.png" alt="Actual BoardForge Custom Board Generator with Robotics controller preset"/><figcaption>Live browser workspace · Robotics controller preset · geometry checks pass</figcaption></figure></section> }

function Deliverables() { return <section className={styles.deliverables}><div className={styles.fileTree}><p><FolderTree size={16}/> Industrial_Ethernet_Controller/</p><code>|-- project.kicad_pro</code><code>|-- project.kicad_sch</code><code>|-- project.kicad_pcb</code><code>|-- gerbers/</code><code>|-- drill/</code><code>|-- BOM.csv</code><code>|-- CPL.csv</code><code>|-- validation/</code><code>|   |-- ERC.json</code><code>|   |-- DRC.json</code><code>|   `-- binding-evidence.json</code><code>`-- manufacturing.zip</code></div><div><p className={styles.kicker}>MANUFACTURING HANDOFF</p><h2>The output is the engineering project—not a screenshot.</h2><p>Open the project in KiCad, inspect every decision, modify it locally, or send the manufacturing package for review.</p><dl><dt>Project hash</dt><dd><code>96a1...7de4</code></dd><dt>Validation</dt><dd>KiCad CLI evidence attached</dd><dt>Package</dt><dd>BOM/CPL parity recorded</dd><dt>Approval</dt><dd>Required before publishing</dd></dl></div></section> }

function Pricing() { return <section className={styles.pricing} id="pricing"><header><p className={styles.kicker}>LICENSING</p><h2>Plans sized for accepted production boards.</h2><p>An accepted production board completes the BoardForge generation, sourcing, ERC, DRC, and manufacturing acceptance workflow. Drafts, failed candidates, archived attempts, and user-rejected candidates do not use the monthly allowance.</p></header><div className={styles.planHeads}><div/><div><b>Builder</b><strong>$26 <small>/ month</small></strong><span>12 accepted boards</span></div><div className={styles.recommended}><b>Engineer <small>Recommended for active development</small></b><strong>$57 <small>/ month</small></strong><span>42 accepted boards</span></div><div><b>Team</b><strong>$110 <small>/ month</small></strong><span>90 accepted boards</span></div></div><div className={styles.comparison}>{comparison.map((r)=><div key={r[0]} className={r[1]?'':styles.category}><b>{r[0]}</b><span>{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span></div>)}</div><div className={styles.planActions}><span/><Link href="/signup?plan=builder">Start Builder</Link><Link className={styles.primary} href="/signup?plan=engineer">Start Engineer <ArrowRight size={15}/></Link><Link href="/signup?plan=team">Start Team</Link></div></section> }

function Footer() { return <><section className={styles.finalRow}><b>Ready to build a reviewable KiCad project?</b><span><Link className={styles.primary} href="/new-board">Start a Board <ArrowRight size={15}/></Link><Link href="/login">Sign In</Link></span></section><footer id="company"><section><div><Brand/><p>Local-first PCB engineering with KiCad-native deliverables.</p></div><div><b>Product</b><Link href="/dashboard">Dashboard</Link><Link href="/custom-board-generator">Custom Board Generator</Link><Link href="/schematic-workspace">Schematic Editor</Link><Link href="/pcb-workspace">PCB Editor</Link></div><div><b>Engineering</b><Link href="/evidence">Validation</Link><Link href="/reports">Component sourcing</Link><Link href="/projects">Candidate workflow</Link><Link href="/readiness">System status</Link></div><div><b>Resources</b><Link href="/docs">Documentation</Link><Link href="/readiness">Reference designs</Link><Link href="/reports">Release notes</Link><a href="mailto:hello@boardforge.ai">Support</a></div><div><b>Company</b><a href="#company">About</a><a href="mailto:hello@boardforge.ai">Contact</a><a href="#pricing">Pricing</a><a href="mailto:privacy@boardforge.ai">Privacy</a></div></section><small>© 2026 BoardForge <i/> System status: operational · Local engine compatible</small></footer></> }
export function CinematicLandingPage(){return <main className={styles.landing}><Header/><Hero/><Workflow/><Workspace/><Evidence/><Outline/><Deliverables/><Pricing/><Footer/></main>}
export default CinematicLandingPage
