import { expect, test } from '@playwright/test'

test('Rust PCB editor edits, routes, validates, and restores history', async ({ page }) => {
  await page.goto('/pcb-workspace')
  const editor = page.getByRole('application', { name: /Rust-backed interactive PCB editor/i })
  await expect(editor).toBeVisible()
  await expect(page.getByText(/Rust revision 0/)).toBeVisible()
  await expect(page.getByText(/source protected/)).toBeVisible()

  const footprint = editor.getByRole('button', { name: /Select / }).first()
  await footprint.dispatchEvent('pointerdown', { pointerId: 1, button: 0 })
  await expect(page.getByText(/1 selected/)).toBeVisible()
  await page.getByRole('button', { name: 'Rotate' }).click()
  await expect(page.getByText(/Rust revision 1/)).toBeVisible()
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(page.getByRole('button', { name: 'Redo' })).toBeEnabled()
  await page.getByRole('button', { name: 'Redo' }).click()

  await page.getByRole('button', { name: 'track', exact: true }).click()
  await page.getByLabel('Routing angle').selectOption('45')
  const box = await editor.boundingBox()
  if (!box) throw new Error('PCB editor bounds missing')
  await page.mouse.click(box.x + box.width * .45, box.y + box.height * .45)
  await page.mouse.click(box.x + box.width * .58, box.y + box.height * .55)
  await page.getByRole('button', { name: 'Finish route' }).click()
  await expect(page.getByText(/2 transactions/)).toBeVisible()
  await expect(page.getByText(/live violations/)).toBeVisible()
})

test('viewport supports manual zoom, pan and touch pointer input', async ({ page }) => {
  await page.goto('/pcb-workspace')
  const editor = page.getByRole('application', { name: /Rust-backed interactive PCB editor/i })
  await expect(editor).toBeVisible()
  const box = await editor.boundingBox()
  if (!box) throw new Error('PCB editor bounds missing')
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.wheel(0, -240)
  await page.getByRole('button', { name: 'pan' }).click()
  await page.mouse.move(box.x + 150, box.y + 150)
  await page.mouse.down()
  await page.mouse.move(box.x + 210, box.y + 190)
  await page.mouse.up()
  await expect(page.getByText(/Rust revision 0/)).toBeVisible()
})

test('typing in routing controls does not invoke destructive canvas shortcuts', async ({ page }) => {
  await page.goto('/pcb-workspace')
  const editor = page.getByRole('application', { name: /Rust-backed interactive PCB editor/i })
  const footprint = editor.getByRole('button', { name: /Select / }).first()
  await footprint.dispatchEvent('pointerdown', { pointerId: 1, button: 0 })
  await expect(page.getByText(/1 selected/)).toBeVisible()

  const net = page.getByLabel('Net')
  await net.fill('USB')
  await net.press('Backspace')
  await net.press('Control+z')

  await expect(net).toHaveValue('USB')
  await expect(page.getByText(/Rust revision 0/)).toBeVisible()
  await expect(page.getByText(/1 selected/)).toBeVisible()
})
