'use client'
import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {newTransaction,pcbObject,PcbId,PcbPoint,RustPcbTransactionV1,RustPcbViewV1} from '../../lib/pcb-editor/model'
import {RustPcbBridge,WasmPcbBridge} from '../../lib/pcb-editor/rust-bridge'
import { createBrowserProject, readBrowserProjects, saveBrowserProject } from '../../lib/browser-project-registry'
import styles from './BrowserPcbEditor.module.css'
type View={zoom:number;x:number;y:number};type Tool='select'|'pan'|'measure'|'track'|'via';type Angle='45'|'90'|'free'
const world=(e:{clientX:number;clientY:number},svg:SVGSVGElement,v:View)=>{const r=svg.getBoundingClientRect();return{x:(e.clientX-r.left-v.x)/v.zoom,y:(e.clientY-r.top-v.y)/v.zoom}}
const pcbWorkspaceError=(action:string)=>`The browser PCB sandbox could not ${action}. Your source project has not been changed; reload the workspace and try again.`
export function BrowserPcbEditor({bridge:given}:{bridge?:RustPcbBridge}){
 const bridge=useMemo(()=>given??new WasmPcbBridge(),[given]),[board,setBoard]=useState<RustPcbViewV1>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[log,setLog]=useState<RustPcbTransactionV1[]>([]),[undos,setUndos]=useState<RustPcbTransactionV1[]>([]),[redos,setRedos]=useState<RustPcbTransactionV1[]>([])
 const [view,setView]=useState<View>({zoom:8,x:70,y:70}),[tool,setTool]=useState<Tool>('select'),[selected,setSelected]=useState<Set<PcbId>>(new Set()),[grid,setGrid]=useState(true),[measure,setMeasure]=useState<PcbPoint[]>([]),[visible,setVisible]=useState<Map<string,number>>(new Map()),[isolated,setIsolated]=useState<string>(),[route,setRoute]=useState<PcbPoint[]>([]),[angle,setAngle]=useState<Angle>('45'),[activeLayer,setActiveLayer]=useState('F.Cu'),[net,setNet]=useState(''),[width,setWidth]=useState(.25),[highlight,setHighlight]=useState(''),[saveStatus,setSaveStatus]=useState('');const svg=useRef<SVGSVGElement>(null),drag=useRef<{screen:PcbPoint;world:PcbPoint;view:View;moving:boolean}|null>(null),pointers=useRef(new Map<number,PcbPoint>()),pinch=useRef<{distance:number;view:View;center:PcbPoint}|null>(null)
 const [projectId,setProjectId]=useState(''),[projectOptions,setProjectOptions]=useState(()=>readBrowserProjects().projects)
 const applyLoadedBoard=useCallback((document:RustPcbViewV1)=>{setBoard(document);setVisible(new Map(document.layers.map(layer=>[layer.id,1])))},[])
 const restoreSavedDraft=useCallback(async(project:string)=>{
  const card=readBrowserProjects().projects.find(item=>item.projectId===project),snapshot=card?.browserDraft?.kind==='pcb'?card.browserDraft.pcb:undefined
  if(!snapshot){setSaveStatus('That browser project has no saved PCB draft.');return}
  if(!bridge.restoreBrowserSnapshot){setSaveStatus('This PCB bridge cannot reopen browser snapshots. Reload with the browser workspace bridge.');return}
  setBusy(true);try{applyLoadedBoard(await bridge.restoreBrowserSnapshot(snapshot));setLog(snapshot.transactions);setUndos([]);setRedos([]);setProjectId(project);setSaveStatus(`Reopened ${card?.projectName || 'browser PCB draft'}. Browser PCB drafts are not KiCad candidates and KiCad validation has not run.`)}catch{setError(pcbWorkspaceError('reopen that browser PCB draft'))}finally{setBusy(false)}
 },[applyLoadedBoard,bridge])
 useEffect(()=>{let live=true;bridge.load().then(document=>{if(live)applyLoadedBoard(document)}).catch(()=>live&&setError(pcbWorkspaceError('load the PCB document')));return()=>{live=false}},[applyLoadedBoard,bridge])
 const apply=useCallback(async(tx:RustPcbTransactionV1,record=true)=>{setBusy(true);try{const r=await bridge.apply(tx);setBoard(r.document);if(record){setLog(x=>[...x,tx]);setUndos(x=>[...x,r.inverse]);setRedos([])}}catch{setError(pcbWorkspaceError('apply that edit'))}finally{setBusy(false)}},[bridge]);const transact=useCallback((op:RustPcbTransactionV1['operation'])=>{if(!board)return;return apply(newTransaction(board,op))},[apply,board])
 const fit=()=>{if(!board||!svg.current)return;const r=svg.current.getBoundingClientRect(),w=board.bounds.max.x-board.bounds.min.x,h=board.bounds.max.y-board.bounds.min.y,z=Math.min((r.width-80)/w,(r.height-80)/h);setView({zoom:z,x:40-board.bounds.min.x*z,y:40-board.bounds.min.y*z})}
 const choose=(id:PcbId,e:React.PointerEvent)=>{e.stopPropagation();setSelected(s=>{const n=new Set(e.shiftKey?s:[]);if(n.has(id))n.delete(id);else n.add(id);return n})}
 const down=(e:React.PointerEvent)=>{if(!svg.current)return;svg.current.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2){const[a,b]=[...pointers.current.values()];pinch.current={distance:Math.hypot(a.x-b.x,a.y-b.y),view,center:{x:(a.x+b.x)/2,y:(a.y+b.y)/2}};return}const p=world(e,svg.current,view);if(tool==='track'){setRoute(r=>[...r,p]);return}if(tool==='via'){void transact({kind:'route-track',net,layer:activeLayer,width,points:[p,p],via:{at:p,diameter:Math.max(width*2,0.6),drill:.3,toLayer:activeLayer==='F.Cu'?'B.Cu':'F.Cu'}});return}if(tool==='select'&&!(e.target as Element).closest('[data-object-id]'))setSelected(new Set());drag.current={screen:{x:e.clientX,y:e.clientY},world:p,view,moving:tool==='select'&&selected.size>0};if(tool==='measure')setMeasure(m=>m.length===2?[p]:[...m,p])}
 const move=(e:React.PointerEvent)=>{pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2&&pinch.current&&svg.current){const[a,b]=[...pointers.current.values()],z=Math.max(1,Math.min(100,pinch.current.view.zoom*Math.hypot(a.x-b.x,a.y-b.y)/pinch.current.distance)),r=svg.current.getBoundingClientRect(),c=pinch.current.center,p={x:(c.x-r.left-pinch.current.view.x)/pinch.current.view.zoom,y:(c.y-r.top-pinch.current.view.y)/pinch.current.view.zoom};setView({zoom:z,x:(a.x+b.x)/2-r.left-p.x*z,y:(a.y+b.y)/2-r.top-p.y*z});return}if(drag.current&&(tool==='pan'||e.buttons===4))setView({...drag.current.view,x:drag.current.view.x+e.clientX-drag.current.screen.x,y:drag.current.view.y+e.clientY-drag.current.screen.y})}
 const up=(e:React.PointerEvent)=>{pointers.current.delete(e.pointerId);if(pointers.current.size<2)pinch.current=null;const d=drag.current;if(d?.moving&&svg.current){const p=world(e,svg.current,view);void transact({kind:'transform',ids:[...selected],translation:{x:p.x-d.world.x,y:p.y-d.world.y},snapMm:.25})}drag.current=null};const wheel=(e:React.WheelEvent)=>{if(!svg.current)return;e.preventDefault();const p=world(e,svg.current,view),z=Math.max(1,Math.min(100,view.zoom*Math.exp(-e.deltaY*.0015))),r=svg.current.getBoundingClientRect();setView({zoom:z,x:e.clientX-r.left-p.x*z,y:e.clientY-r.top-p.y*z})}
 const undo=async()=>{const tx=undos.at(-1);if(!tx||!board)return;setBusy(true);try{if(bridge.undo)setBoard(await bridge.undo());else await apply({...tx,baseRevision:board.revision,baseSourceSha256:board.sourceSha256},false);setUndos(x=>x.slice(0,-1));setRedos(x=>[...x,log.at(-1)!]);setLog(x=>x.slice(0,-1))}catch{setError(pcbWorkspaceError('undo that edit'))}finally{setBusy(false)}};const redo=async()=>{const tx=redos.at(-1);if(!tx||!board)return;setBusy(true);try{if(bridge.redo)setBoard(await bridge.redo());else await apply({...tx,baseRevision:board.revision,baseSourceSha256:board.sourceSha256},false);setRedos(x=>x.slice(0,-1));setUndos(x=>[...x,tx]);setLog(x=>[...x,tx])}catch{setError(pcbWorkspaceError('redo that edit'))}finally{setBusy(false)}}
 const finishRoute=async()=>{if(route.length>1){const points:PcbPoint[]=[];for(let i=1;i<route.length;i++){const planned=bridge.planRoute?await bridge.planRoute(route[i-1],route[i],angle,activeLayer,net,width):[route[i-1],route[i]];points.push(...(i?planned.slice(1):planned))}await transact({kind:'route-track',net,layer:activeLayer,width,points})}setRoute([]);setTool('select')};useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setRoute([]);setTool('select')}else if(e.key==='Backspace'&&route.length){e.preventDefault();setRoute(r=>r.slice(0,-1))}else if(e.key==='Enter'&&route.length>1)void finishRoute();else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();void(e.shiftKey?redo():undo())}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'&&selected.size){e.preventDefault();void transact({kind:'duplicate',ids:[...selected],translation:{x:1.27,y:1.27}})}else if(e.key.toLowerCase()==='r'&&selected.size)void transact({kind:'transform',ids:[...selected],translation:{x:0,y:0},rotationDegrees:90});else if((e.key==='Delete'||e.key==='Backspace')&&selected.size){void transact({kind:'delete',ids:[...selected]});setSelected(new Set())}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[selected,transact,undos,redos,board,log,route])
 const downloadSandbox=()=>{const artifact=bridge.downloadSandbox?.();if(!artifact){setSaveStatus('Sandbox download is unavailable for this session');return}const url=URL.createObjectURL(new Blob([artifact.source],{type:'application/x-kicad-pcb'})),link=document.createElement('a');link.href=url;link.download=artifact.filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);setSaveStatus('Sandbox PCB downloaded — review it in KiCad before use')}
 const saveBrowserDraft=()=>{if(!board)return;const artifact=bridge.downloadSandbox?.();if(!artifact){setSaveStatus('This PCB bridge cannot provide an exact browser snapshot to save.');return}const snapshot={schema:'boardforge.browser-pcb-snapshot/v1' as const,savedAt:new Date().toISOString(),sandboxSource:artifact.source,document:board,transactions:log},draft={schema:'boardforge.browser-draft.v1' as const,kind:'pcb' as const,updatedAt:snapshot.savedAt,summary:`Browser PCB snapshot: ${board.footprints.length} footprints, ${board.tracks.length} tracks, ${board.vias.length} vias. KiCad validation not run.`,pcb:snapshot};try{const existing=projectId?readBrowserProjects().projects.find(item=>item.projectId===projectId):undefined;const next=existing?{...existing,browserDraft:draft,reports:{...existing.reports,browserDraft:draft.summary},status:'BROWSER_PCB_DRAFT',syncStatus:'browser_saved'}:createBrowserProject({projectId:crypto.randomUUID(),projectName:`${board.title} browser PCB`,prompt:draft.summary,kind:'browser_pcb',browserDraft:draft});saveBrowserProject(next);setProjectId(next.projectId);setProjectOptions(readBrowserProjects().projects);setSaveStatus(`Saved to ${next.projectName}. It is a browser PCB draft only; it is not a KiCad candidate and no KiCad validation has run.`)}catch{setSaveStatus('The browser could not save this PCB draft. No project or KiCad file was changed.')}
 }
 if(!board)return <main className={styles.loading} role={error?'alert':undefined}>{error||'Loading Rust PCB document…'}</main>;const shown=(l:string)=>visible.has(l)&&(!isolated||isolated===l),active=[...selected][0],object=active?pcbObject(board,active):undefined
 return <div className={styles.shell} aria-busy={busy}><header><strong>PCB workspace</strong><span>{board.title}</span><span className={styles.saved}>Rust revision {board.revision} · source protected</span></header><nav aria-label="PCB tools">{(['select','pan','measure','track','via']as Tool[]).map(t=><button key={t} aria-pressed={tool===t} onClick={()=>setTool(t)}>{t}</button>)}{tool==='track'&&<><select aria-label="Routing angle" value={angle} onChange={e=>setAngle(e.target.value as Angle)}><option>45</option><option>90</option><option>free</option></select><button disabled={route.length<2} onClick={finishRoute}>Finish route</button></>}<i/><button disabled={!undos.length} onClick={()=>void undo()}>Undo</button><button disabled={!redos.length} onClick={()=>void redo()}>Redo</button><button aria-pressed={grid} onClick={()=>setGrid(x=>!x)}>Grid</button><button onClick={fit}>Fit board</button><button onClick={()=>selected.size&&transact({kind:'transform',ids:[...selected],translation:{x:0,y:0},rotationDegrees:90})}>Rotate</button><button onClick={downloadSandbox}>Download sandbox</button><label className={styles.projectSelect}>Browser project<select aria-label="Browser PCB project" value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">New browser PCB draft</option>{projectOptions.map(project=><option key={project.projectId} value={project.projectId}>{project.projectName}</option>)}</select></label><button onClick={saveBrowserDraft}>Save browser PCB draft</button><button disabled={!projectId} onClick={()=>void restoreSavedDraft(projectId)}>Open saved draft</button>{saveStatus&&<output aria-label="Browser PCB draft status">{saveStatus}</output>}</nav>
 <aside className={styles.layers}><h2>Layers</h2>{board.layers.map(l=><div className={styles.layer} key={l.id}><input aria-label={`Show ${l.name}`} type="checkbox" checked={visible.has(l.id)} onChange={()=>setVisible(v=>{const n=new Map(v);if(n.has(l.id))n.delete(l.id);else n.set(l.id,1);return n})}/><span style={{background:l.color}}/><button aria-pressed={isolated===l.id} onClick={()=>setIsolated(x=>x===l.id?undefined:l.id)}>{l.name}</button><input aria-label={`${l.name} opacity`} type="range" min=".1" max="1" step=".1" value={visible.get(l.id)??1} onChange={e=>setVisible(v=>new Map(v).set(l.id,+e.target.value))}/></div>)}<h2>Objects</h2><p>{board.footprints.length} footprints</p><p>{board.tracks.length} tracks · {board.vias.length} vias</p><p>{board.unconnectedCount} unconnected airwires</p><p>{board.violations.length} live violations</p></aside>
 <main className={styles.canvas}><svg ref={svg} tabIndex={0} role="application" aria-label="Rust-backed interactive PCB editor" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onDoubleClick={()=>route.length>1&&void finishRoute()} onWheel={wheel}><defs><pattern id="pcbgrid" width={view.zoom*2.54} height={view.zoom*2.54} patternUnits="userSpaceOnUse" x={view.x} y={view.y}><circle cx="1" cy="1" r=".7" fill="#334155"/></pattern></defs>{grid&&<rect width="100%" height="100%" fill="url(#pcbgrid)"/>}<g transform={`translate(${view.x} ${view.y}) scale(${view.zoom})`}>
 {board.graphics.filter(g=>shown(g.layer)&&g.points.length>1).map(g=><polyline key={g.id} data-object-id={g.id} points={g.points.map(p=>`${p.x},${p.y}`).join(' ')} fill={g.kind==='polygon'?'#123b31':'none'} stroke={board.layers.find(l=>l.id===g.layer)?.color} strokeWidth={g.width??.2} opacity={visible.get(g.layer)} onPointerDown={e=>choose(g.id,e)}/>)}{board.ratsnest.map(r=><line key={r.id} className={styles.ratsnest} x1={r.start.x} y1={r.start.y} x2={r.end.x} y2={r.end.y}/>)}{board.tracks.filter(t=>shown(t.layer)).map(t=><line key={t.id} data-object-id={t.id} x1={t.start.x} y1={t.start.y} x2={t.end.x} y2={t.end.y} stroke={board.layers.find(l=>l.id===t.layer)?.color} opacity={visible.get(t.layer)} strokeWidth={t.width} className={selected.has(t.id)?styles.selectedStroke:''} onPointerDown={e=>choose(t.id,e)}/>)}{board.vias.map(v=><circle key={v.id} data-object-id={v.id} cx={v.at.x} cy={v.at.y} r={v.diameter/2} className={`${styles.via} ${selected.has(v.id)?styles.selected:''}`} onPointerDown={e=>choose(v.id,e)}/>)}
 {board.footprints.filter(f=>shown(f.layer)).map(f=><g key={f.id} data-object-id={f.id} role="button" aria-label={`Select ${f.reference}`} transform={`translate(${f.at.x} ${f.at.y}) rotate(${f.rotation})`} className={selected.has(f.id)?styles.selectedFootprint:''} opacity={highlight && !f.pads.some(p=>p.net===highlight) ? .25 : 1} onPointerDown={e=>choose(f.id,e)}>{f.courtyard ? <polygon points={f.courtyard.map(p=>`${p.x},${p.y}`).join(' ')} className={styles.courtyard}/> : null} {f.pads.map(p=><rect key={p.id} data-object-id={p.id} role="button" aria-label={`Select pad ${p.number||p.id}`} x={p.at.x-p.size.x/2} y={p.at.y-p.size.y/2} width={p.size.x} height={p.size.y} rx={p.shape==='circle'?p.size.x/2:0} className={`${styles.pad} ${selected.has(p.id)?styles.selected:''}`} onPointerDown={e=>choose(p.id,e)}/>)}<text y="-4">{f.reference}</text></g>)}{board.violations.map(v=><g key={v.id} transform={`translate(${v.at.x} ${v.at.y})`}><circle r="1.7" className={styles.issue}/><text className={styles.issueText}>!</text><title>{v.message}</title></g>)}{measure.length===2&&<g className={styles.measure}><line x1={measure[0].x} y1={measure[0].y} x2={measure[1].x} y2={measure[1].y}/><text x={(measure[0].x+measure[1].x)/2} y={(measure[0].y+measure[1].y)/2}>{Math.hypot(measure[1].x-measure[0].x,measure[1].y-measure[0].y).toFixed(2)} mm</text></g>}{route.length>0&&<polyline points={route.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke={width<.2?'#ef4444':'#facc15'} strokeWidth={width}><title>{width<.2?'Invalid: below minimum track width':'Rust route preview'}</title></polyline>}</g></svg></main>
 <aside className={styles.inspector}><h2>Routing</h2><p>Current: net {net||'unassigned'} · {activeLayer} · {width} mm</p><label>Net<input value={net} onChange={e=>setNet(e.target.value)}/></label><label>Width (mm)<input type="number" step=".05" value={width} onChange={e=>setWidth(+e.target.value)}/></label><label>Layer<select value={activeLayer} onChange={e=>setActiveLayer(e.target.value)}>{board.layers.filter(l=>l.kind==='copper').map(l=><option key={l.id}>{l.id}</option>)}</select></label><label>Highlight net<input value={highlight} onChange={e=>setHighlight(e.target.value)}/></label><h2>Properties</h2>{object?<><strong>{'reference'in object?object.reference:object.id}</strong><p>Stable ID: {object.id}</p>{'at'in object&&<><label>X (mm)<input type="number" value={object.at.x} onChange={e=>transact({kind:'set-property',id:object.id,property:'x',value:+e.target.value})}/></label><label>Y (mm)<input type="number" value={object.at.y} onChange={e=>transact({kind:'set-property',id:object.id,property:'y',value:+e.target.value})}/></label></>}</>:<p>Select an object. Shift-click adds to selection. All edits are Rust transactions.</p>}<h2>Validation</h2><p>BoardForge live geometry DRC: {board.violations.length?'violations':'no current geometry violations'}<br/>KiCad CLI DRC: candidate validation only<br/>Manufacturing review: separate gate</p>{board.violations.map(v=><button className={styles.issueCard} key={v.id} onClick={()=>setView(current=>({...current,x:400-v.at.x*current.zoom,y:300-v.at.y*current.zoom}))}>{v.severity==='error'?'⛔':'⚠'} {v.rule}: {v.message}<small>Objects {v.objectIds.join(', ')} · ({v.at.x.toFixed(2)}, {v.at.y.toFixed(2)}) mm</small></button>)}{error&&<p role="alert">{error}</p>}</aside><footer><span>Rust/WASM source of truth</span><span>{selected.size} selected</span><span>{log.length} transactions</span><span>{board.unsupportedCount} preserved constructs</span></footer></div>
}
