import {approvedAssetFor} from '../../components/approved-production-assets.mjs'
export const MOTOR_DRIVER_PROPOSAL_SCHEMA='boardforge.phase2c.production-proposal.motor-driver.v1'
const approved=(ref,role,mpn)=>({ref,role,mpn,status:approvedAssetFor(mpn)?'APPROVED_EXACT_ASSET':'BLOCKED_MISSING_APPROVED_EXACT_ASSET'})
const blocked=(ref,role,requirement)=>({ref,role,mpn:null,status:'BLOCKED_MISSING_APPROVED_EXACT_ASSET',requirement})

export const motorDriverProductionProposal=Object.freeze({
  schema:MOTOR_DRIVER_PROPOSAL_SCHEMA,status:'BLOCKED_PENDING_MOTOR_SUPPLY_REGEN_AND_EXACT_SYMBOL_ENVELOPE',boardId:'014_MOTOR_DRIVER',maximumAreaMm2:2650,
  architecture:'Protected single-channel bidirectional brushed-DC H-bridge with measured and regulated motor current',
  motorEnvelope:null,supplyEnvelope:null,regenerationEnvelope:null,
  primarySources:{driver:'https://www.ti.com/lit/ds/symlink/drv8876.pdf',ratings:'https://www.ti.com/product/DRV8876'},
  candidate:{role:'BRUSHED_DC_H_BRIDGE',family:'DRV8876',exactMpn:'DRV8876PWPR',status:'PRIMARY_SOURCE_ORDER_SUFFIX_PACKAGE_AND_PIN_MAP_VERIFIED_KICAD_SYMBOL_MISSING',verified:{motorType:'one bidirectional brushed DC motor',operatingSupplyV:[4.5,37],absoluteMaximumV:40,peakOutputCurrentA:3.5,package:'PWP HTSSOP-16 exposed pad',installedKiCadFootprint:'Package_SO:HTSSOP-16-1EP_4.4x5mm_P0.65mm_EP3.4x5mm',installedKiCadSymbol:null,pinMap:{1:'EN/IN1',2:'PH/IN2',3:'nSLEEP',4:'nFAULT',5:'VREF',6:'IPROPI',7:'IMODE',8:'OUT1',9:'PGND',10:'OUT2',11:'VM',12:'VCP',13:'CPH',14:'CPL',15:'GND',16:'PMODE',17:'THERMAL_PAD_GND'},integratedCurrentSense:true,currentRegulation:true,faultOutput:true,protections:['UVLO','charge-pump undervoltage','overcurrent','thermal shutdown']}},
  outline:{family:'thermal-wings-motor-driver',closed:true,maximumAreaMm2:2650,points:[[0,4],[4,4],[4,0],[62,0],[62,4],[66,4],[66,36],[62,36],[62,40],[4,40],[4,36],[0,36]],purposefulFeatures:{thermalWingCount:2,powerStageWing:'right',connectorWing:'left',mountingHoleCount:4,thermalViaFieldRequired:true}},
  bom:[
    blocked('U1','integrated brushed motor H-bridge power switches and gate driver','DRV8876PWPR and its PWP pin map/footprint are exact, but KiCad has no installed authoritative symbol and thermal closure requires continuous/stall current and ambient.'),
    blocked('J_MOTOR','bidirectional motor output connector','Freeze exact connector MPN from continuous/stall current, voltage, wire gauge, pitch and mating-cycle requirements.'),
    blocked('R_IPROPI','motor current sense limit and IPROPI network','Calculate exact resistor MPNs/tolerance/power from current envelope and controller ADC/VREF.'),
    approved('F1','motor input fuse candidate','3413.0218.22'),approved('Q_REV','motor reverse-polarity power switch candidate','SI7465DP-T1-GE3'),approved('D_TVS','motor supply transient clamp candidate','SMAJ24A'),approved('C_BULK','motor DC-link bulk decoupling candidate','UWT1H100MCL1GB'),approved('C_HF','motor bridge high-frequency bypass','CL10B104KB8NNNC'),
    blocked('J_PWR','motor supply power connector','Freeze exact connector MPN from supply voltage/current, fault energy, wire gauge and touch-safety requirements.'),
    blocked('R_GATE','PWM direction sleep and fault gate-control network','Freeze controller interface/ADC/VREF, PMODE/IMODE/bias/series parts, charge-pump capacitors and disabled reset/brownout state.'),
    blocked('P_REGEN','motor braking and regeneration energy path','Select exact clamp, dump, storage or supply-absorption architecture from worst-case inertia, speed, load and braking duty.'),
    blocked('P_EMI','motor terminal transient and EMI suppression','Select exact RC/TVS/common-mode parts from motor and cable measurements; do not assume a universal capacitor.'),
  ],
  requiredTopology:['Fused and reverse-polarity-protected motor supply entry with TVS selected from the declared supply transient envelope.','Local ceramic bypass and bulk capacitance sized for wiring inductance, PWM ripple, startup, braking, and stall energy.','Bidirectional motor terminal on OUT1/OUT2 and a separately rated supply terminal.','Hardware current limit/reference and IPROPI network calculated from declared continuous, startup, and stall current.','Defined nSLEEP/input pull states that keep the bridge disabled during reset and brownout.','nFAULT monitoring, thermal-pad copper/vias, current-rated copper, and connector/trace temperature-rise evidence.','Motor EMI suppression selected from measured motor/cable behavior; no generic capacitor value asserted in advance.'],
  mandatoryUnresolved:['Declare motor nominal voltage, winding resistance/inductance or exact motor MPN, no-load/continuous/startup/stall current and stall duration, speed/inertia/load, PWM frequency, braking/coast behavior, cable length, ambient and duty cycle.','Declare supply nominal/range/transients, current limit, source impedance, fuseable fault energy, reverse-polarity case, wire/connector requirements, and whether the source can absorb regenerated energy.','Create and independently verify an exact DRV8876PWPR KiCad symbol with all 16 pins and exposed pad; do not relabel another bridge.','Calculate bulk capacitance, charge-pump capacitors, current-limit/IPROPI/VREF/IMODE values, TVS standoff/clamp, fuse rating/I²t, reverse-polarity device, terminal rating, copper width, and thermal-via field from the declared envelope.','Prove regenerated/braking energy handling; integrated overcurrent protection does not by itself clamp the supply rail.'],
  evidenceRequired:['exactAssetsApproved','motorEnvelopeVerified','hBridgeRatingsVerified','continuousStartupStallCurrentVerified','currentSenseLimitVerified','powerEntryProtectionVerified','reversePolarityVerified','transientClampVerified','bulkRippleVerified','gateSafeStateVerified','regenerationHandled','thermalCopperViaVerified','connectorTraceTemperatureRiseVerified','motorEmiVerified','productionStallFaultTestVerified'],
})

export function validateMotorDriverArchitecture(definition={}){const roles=(definition.bom||[]).map(x=>String(x.role||'').toLowerCase()),has=p=>roles.some(x=>p.test(x)),errors=[];if(!has(/motor.*(h-bridge|driver)|h-bridge.*motor/))errors.push('motor-h-bridge-missing');if(!has(/motor.*terminal/))errors.push('motor-terminal-missing');if(!has(/motor.*current.*(sense|limit)|current.*regulation/))errors.push('motor-current-control-missing');if(!has(/motor.*(tvs|transient)|supply.*tvs/))errors.push('motor-supply-transient-protection-missing');if(!has(/reverse.*polarity|motor.*input.*protection/))errors.push('motor-reverse-polarity-protection-missing');if(!has(/motor.*bulk|bulk.*motor/))errors.push('motor-bulk-capacitance-missing');if(!has(/bridge.*disabled.*reset|motor.*safe.*reset|sleep.*pull/))errors.push('motor-reset-safe-state-missing');const e=definition.semanticEvidence?.motorDriver||{};if(!e.motorEnvelopeVerified)errors.push('motor-electrical-envelope-unverified');if(!e.thermalVerified)errors.push('motor-thermal-design-unverified');if(!e.regenerationHandled)errors.push('motor-regeneration-path-unverified');return{ok:errors.length===0,errors}}
export function validateMotorDriverProductionProposal(proposal={}){const errors=[],bom=Array.isArray(proposal.bom)?proposal.bom:[],roles=bom.map(x=>String(x.role||'').toLowerCase()),has=p=>roles.some(x=>p.test(x));for(const[p,c]of[[/h-bridge power switches and gate driver/,'brushed-motor-h-bridge-missing'],[/motor output connector/,'brushed-motor-connector-missing'],[/current sense/,'brushed-motor-current-sense-missing'],[/input fuse/,'brushed-motor-power-entry-protection-missing'],[/transient clamp/,'brushed-motor-transient-clamp-missing'],[/gate-control/,'brushed-motor-gate-control-missing'],[/bulk decoupling/,'brushed-motor-bulk-decoupling-missing'],[/regeneration energy path/,'brushed-motor-regeneration-path-missing']])if(!has(p))errors.push(c);if(!proposal.motorEnvelope)errors.push('brushed-motor-electrical-envelope-undeclared');if(!proposal.supplyEnvelope)errors.push('brushed-motor-supply-envelope-undeclared');if(!proposal.regenerationEnvelope)errors.push('brushed-motor-regeneration-envelope-undeclared');const blockedParts=bom.filter(x=>x.status!=='APPROVED_EXACT_ASSET');if(blockedParts.length)errors.push('brushed-motor-exact-assets-unapproved');const f=proposal.outline?.purposefulFeatures||{},area=polygonArea(proposal.outline?.points);if(proposal.outline?.closed!==true||!Number.isFinite(area)||area>(proposal.maximumAreaMm2||0)||f.thermalWingCount!==2||f.thermalViaFieldRequired!==true)errors.push('brushed-motor-purposeful-outline-invalid');for(const key of proposal.evidenceRequired||[])if(proposal.semanticEvidence?.[key]!==true)errors.push(`brushed-motor-evidence-${key.replace(/[A-Z]/g,m=>`-${m.toLowerCase()}`)}-missing`);return{schema:'boardforge.phase2c.motor-driver-remediation-gate.v1',ok:errors.length===0,errors,areaMm2:area,maximumAreaMm2:proposal.maximumAreaMm2,blockedRefs:blockedParts.map(x=>x.ref)}}
function polygonArea(points=[]){if(points.length<3)return NaN;let s=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];s+=a[0]*b[1]-b[0]*a[1]}return Math.abs(s)/2}
