import {assertRustPcbView,BrowserPcbSnapshotV1,RustPcbTransactionResultV1,RustPcbTransactionV1,RustPcbViewV1} from './model'

export type RouteAngle='45'|'90'|'free'
export interface RustPcbBridge {load():Promise<RustPcbViewV1>;apply(transaction:RustPcbTransactionV1):Promise<RustPcbTransactionResultV1>;planRoute?(start:{x:number;y:number},cursor:{x:number;y:number},angle:RouteAngle,layer:string,net:string,width:number):Promise<{x:number;y:number}[]>;undo?():Promise<RustPcbViewV1>;redo?():Promise<RustPcbViewV1>;downloadSandbox?():{filename:string;source:string};restoreBrowserSnapshot?(snapshot:BrowserPcbSnapshotV1):Promise<RustPcbViewV1>;saveCandidate(document:RustPcbViewV1,transactions:RustPcbTransactionV1[]):Promise<{candidatePath:string;validationStatus:string}>}

/** HTTP transports Rust DTOs only. The local engine owns parsing, geometry and mutations. */
export class LocalEnginePcbBridge implements RustPcbBridge {
 constructor(private readonly endpoint='/api/local-engine/v2/pcb-session'){}
 private async request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${this.endpoint}${path}`,{...init,headers:{'content-type':'application/json',...init?.headers}});if(!response.ok)throw new Error((await response.text())||`Local engine returned ${response.status}`);return response.json() as Promise<T>}
 async load(){return assertRustPcbView(await this.request<unknown>(''))}
 async apply(transaction:RustPcbTransactionV1){const result=await this.request<RustPcbTransactionResultV1>('/transactions',{method:'POST',body:JSON.stringify(transaction)});return{...result,document:assertRustPcbView(result.document)}}
 async saveCandidate(document:RustPcbViewV1,transactions:RustPcbTransactionV1[]){return this.request<{candidatePath:string;validationStatus:string}>('/candidate',{method:'POST',body:JSON.stringify({schema:'boardforge.pcb-candidate-request/v1',documentId:document.documentId,sourceSha256:document.sourceSha256,revision:document.revision,transactions})})}
}

type WasmPcbModule={default:(input?:unknown)=>Promise<unknown>;parse_pcb_document:(source:string)=>unknown;apply_pcb_edits:(source:string,tx:unknown)=>{source:string;source_sha256:string};pcb_plan_route?:(request:unknown)=>unknown;pcb_validate?:(request:unknown)=>unknown;pcb_net_metrics?:(request:unknown)=>unknown}
export class WasmPcbBridge implements RustPcbBridge {
 private source='';private originalSource='';private document?:RustPcbViewV1;private wasm?:WasmPcbModule;private operationLog:Record<string,unknown>[]=[]
 private undoStack:Array<{source:string;operations:Record<string,unknown>[]}>=[];private redoStack:Array<{source:string;operations:Record<string,unknown>[]}>=[]
 constructor(private readonly fixture='/fixtures/m4-simple-2layer.kicad_pcb'){}
 private async module(){if(this.wasm)return this.wasm
  // The generated ESM module is served from public/ and intentionally has no TS source module.
  // @ts-expect-error runtime WASM asset
  const wasm=await import(/* webpackIgnore: true */'/wasm/boardforge_wasm.js') as unknown as WasmPcbModule
  await wasm.default('/wasm/boardforge_wasm_bg.wasm');return this.wasm=wasm}
 async load(){const [wasm,response]=await Promise.all([this.module(),fetch(this.fixture)]);if(!response.ok)throw new Error(`Unable to load PCB fixture (${response.status})`);this.source=await response.text();this.originalSource=this.source;this.operationLog=[];this.undoStack=[];this.redoStack=[];return this.document=await this.parseAndValidate(wasm,0)}
 async restoreBrowserSnapshot(snapshot:BrowserPcbSnapshotV1){
  if(snapshot.schema!=='boardforge.browser-pcb-snapshot/v1'||!snapshot.sandboxSource)throw new Error('Unsupported browser PCB snapshot')
  const wasm=await this.module();this.source=snapshot.sandboxSource;this.originalSource=this.source;this.operationLog=[];this.undoStack=[];this.redoStack=[]
  const restored=await this.parseAndValidate(wasm,snapshot.document.revision)
  if(restored.sourceSha256!==snapshot.document.sourceSha256)throw new Error('Browser PCB snapshot no longer matches its saved model')
  return this.document=restored
 }
 private geometry(document:RustPcbViewV1){return{schema:1,outline:document.graphics.filter(g=>g.layer==='Edge.Cuts').flatMap(g=>g.points),segments:document.tracks.map(t=>({...t,net:t.net||null})),vias:document.vias.map(v=>({...v,net:v.net||null,layers:[...v.layers]})),pads:document.footprints.flatMap(f=>f.pads.map(p=>({id:p.id,at:{x:f.at.x+p.at.x,y:f.at.y+p.at.y},size:p.size,layer:p.layers[0]||f.layer,net:p.net||null}))),keepouts:[],rules:{clearance:.2,min_track_width:.2,edge_clearance:.25,via_clearance:.2,grid:.05}}}
 private async parseAndValidate(wasm:WasmPcbModule,revision:number){const parsed=assertRustPcbView(wasm.parse_pcb_document(this.source));const response=wasm.pcb_validate?.(this.geometry(parsed)) as {violations?:Array<{id:string;at:{x:number;y:number};severity:'error'|'warning';kind:string;message:string;object_ids:string[]}>}|undefined;return{...parsed,revision,violations:(response?.violations??[]).map(v=>({id:v.id,at:v.at,severity:v.severity,rule:v.kind,message:v.message,objectIds:v.object_ids}))}}
 private operations(tx:RustPcbTransactionV1){const board=this.document!;const op=tx.operation,items:Record<string,unknown>[]=[]
  if(op.kind==='transform')for(const id of op.ids){const fp=board.footprints.find(x=>x.id===id),track=board.tracks.find(x=>x.id===id),via=board.vias.find(x=>x.id===id);if(fp){items.push({op:'move_footprint',uuid:id,x:fp.at.x+op.translation.x,y:fp.at.y+op.translation.y});if(op.rotationDegrees)items.push({op:'rotate_footprint',uuid:id,angle:fp.rotation+op.rotationDegrees})}else if(track)items.push({op:'drag_track',uuid:id,start:[track.start.x+op.translation.x,track.start.y+op.translation.y],end:[track.end.x+op.translation.x,track.end.y+op.translation.y]});else if(via)items.push({op:'delete_via',uuid:id},{op:'add_via',uuid:id,at:[via.at.x+op.translation.x,via.at.y+op.translation.y],size:via.diameter,drill:via.drill,layers:via.layers,net:via.net})}
  else if(op.kind==='delete')for(const id of op.ids)items.push({op:board.footprints.some(x=>x.id===id)?'delete_footprint':board.tracks.some(x=>x.id===id)?'delete_track':'delete_via',uuid:id})
  else if(op.kind==='duplicate')for(const id of op.ids){const fp=board.footprints.find(x=>x.id===id);if(fp)items.push({op:'duplicate_footprint',uuid:id,new_uuid:crypto.randomUUID(),x:fp.at.x+op.translation.x,y:fp.at.y+op.translation.y})}
  else if(op.kind==='set-property')items.push({op:'set_property',uuid:op.id,name:op.property,value:String(op.value)})
  else if(op.kind==='route-track'){const netCode=Number(op.net)||0;op.points.slice(1).forEach((p,i)=>items.push({op:'add_track',uuid:crypto.randomUUID(),start:[op.points[i].x,op.points[i].y],end:[p.x,p.y],width:op.width,layer:op.layer,net:netCode}));if(op.via)items.push({op:'add_via',uuid:crypto.randomUUID(),at:[op.via.at.x,op.via.at.y],size:op.via.diameter,drill:op.via.drill,layers:[op.layer,op.via.toLayer],net:netCode})}return items}
 private inverse(tx:RustPcbTransactionV1):RustPcbTransactionV1 {const op=tx.operation;if(op.kind==='transform')return{...tx,id:crypto.randomUUID(),operation:{...op,translation:{x:-op.translation.x,y:-op.translation.y},rotationDegrees:-(op.rotationDegrees??0)}};return tx}
 async apply(transaction:RustPcbTransactionV1){if(!this.document)throw new Error('PCB document is not loaded');const wasm=await this.module(),operations=this.operations(transaction);this.undoStack.push({source:this.source,operations:[...this.operationLog]});this.redoStack=[];const result=wasm.apply_pcb_edits(this.source,{version:1,expected_source_sha256:this.document.sourceSha256,operations});this.source=result.source;this.operationLog.push(...operations);this.document={...(await this.parseAndValidate(wasm,this.document.revision+1)),sourceSha256:result.source_sha256};return{schema:'boardforge.pcb-transaction-result/v1' as const,transactionId:transaction.id,document:this.document,inverse:this.inverse(transaction),diff:{rust:true,operations}}}
 async planRoute(start:{x:number;y:number},cursor:{x:number;y:number},angle:RouteAngle,layer:string,net:string,width:number){const wasm=await this.module();if(!wasm.pcb_plan_route)throw new Error('Rust route planner is unavailable');const preview=wasm.pcb_plan_route({schema:1,id_prefix:'preview',start,cursor,layer,net:net||null,width,angle:angle==='45'?'forty_five':angle==='90'?'ninety':'free',insert_via:false,target_layer:null,via_diameter:.6,via_drill:.3,rules:{clearance:.2,min_track_width:.2,edge_clearance:.25,via_clearance:.2,grid:.05}}) as {segments:Array<{start:{x:number;y:number};end:{x:number;y:number}}>};return preview.segments.length?[preview.segments[0].start,...preview.segments.map(s=>s.end)]:[]}
 private async restore(target:Array<{source:string;operations:Record<string,unknown>[]}>,opposite:Array<{source:string;operations:Record<string,unknown>[]}>) {if(!this.document)throw new Error('PCB document is not loaded');const state=target.pop();if(!state)throw new Error('No history item');opposite.push({source:this.source,operations:[...this.operationLog]});this.source=state.source;this.operationLog=state.operations;const wasm=await this.module();return this.document=await this.parseAndValidate(wasm,this.document.revision+1)}
 undo(){return this.restore(this.undoStack,this.redoStack)}
 redo(){return this.restore(this.redoStack,this.undoStack)}
 downloadSandbox(){return{filename:'boardforge-browser-sandbox.kicad_pcb',source:this.source}}
 async saveCandidate(document:RustPcbViewV1,transactions:RustPcbTransactionV1[]){const response=await fetch('/api/local-engine/kicad/candidate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({schema:'boardforge.pcb-candidate-request/v1',source:this.originalSource,operations:this.operationLog,revision:document.revision,transactions})});if(!response.ok)throw new Error(`Candidate pipeline returned ${response.status}: ${await response.text()}`);return response.json() as Promise<{candidatePath:string;validationStatus:string}>}
}
