import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{AGRICULTURE_NODE_MECHANICAL_CONTRACT as contract,validateAgricultureNodeMechanicalGeometry as validate}from'../lib/phase2c/agriculture-node-mechanical-contract.mjs'

const capsuleOutline=[[6,0],[64,0],[70,5],[72,10],[72,28],[70,33],[64,38],[6,38],[0,33],[-2,28],[-2,10],[0,5]]
const valid=()=>({outline:capsuleOutline,outlineClosed:true,capsuleProfile:{minimumEdgeRadiusMm:6,tangentTransitionsVerified:true},sealPath:{closedContinuousPathVerified:true,minimumOutlineInsetMm:2.5,enclosureGasketAligned:true,noCopperViasComponentsOrSlotsCrossPath:true,noUnsealedFastenersInsidePath:true},placements:{probeAndPowerGlands:{minX:-1,maxX:6},antenna:{minX:59,maxX:70},coreElectronics:{minX:18,maxX:50}},climateVent:{weatherMembraneInterfaceVerified:true,drainPathVerified:true,airPathToClimateSensorVerified:true,clearOfSplashLineAndCableGlands:true},antennaKeepout:{allCopperLayers:true,noPlanesTracksOrVias:true,noMetalBatteryOrFastenersInFieldRegion:true,enclosureWindowVerified:true},cableAndProbeStrain:{glandRetentionVerified:true,loadPathClearOfSealAndComponents:true},mountingBosses:[{x:12,y:7,holeDiameterMm:3.2,copperKeepoutRadiusMm:3.2,allLayersKeepout:true,sealedBossInterfaceVerified:true,inAntennaOrVentRegion:false},{x:12,y:31,holeDiameterMm:3.2,copperKeepoutRadiusMm:3.2,allLayersKeepout:true,sealedBossInterfaceVerified:true,inAntennaOrVentRegion:false}]})

test('Board032 manifest preserves weatherproof-capsule intent and 3350mm2 cap',()=>{const board=manifest.boards[31];assert.equal(board.id,'032_AGRICULTURE_NODE');assert.equal(board.outline.family,'weatherproof capsule-agriculture-node');assert.equal(board.maximumAreaMm2,3350);assert.equal(contract.maximumAreaMm2,3350)})
test('current catalog outline is under cap but lacks weatherproof capsule evidence',()=>{const definition=catalogDefinition(manifest.boards[31],31),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2<3350);assert.ok(result.errors.includes('weatherproof-capsule-outline-invalid'));assert.ok(result.errors.includes('weatherproof-gasket-path-unverified'))})
test('purposeful sealed agriculture capsule fits the maximum area',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,2692);assert.equal(result.bounds.width,74);assert.equal(result.bounds.height,38)})
test('capsule profile and continuous gasket boundary fail closed',()=>{const x=valid();x.capsuleProfile.minimumEdgeRadiusMm=2;x.sealPath.minimumOutlineInsetMm=1;x.sealPath.noCopperViasComponentsOrSlotsCrossPath=false;const e=validate(x).errors;assert.ok(e.includes('weatherproof-capsule-profile-unverified'));assert.ok(e.includes('weatherproof-gasket-path-unverified'));assert.ok(e.includes('weatherproof-seal-boundary-compromised'))})
test('glands, core, antenna and climate vent retain functional separation',()=>{const x=valid();x.placements.probeAndPowerGlands.maxX=15;x.placements.coreElectronics.maxX=60;x.placements.antenna.minX=45;x.climateVent.clearOfSplashLineAndCableGlands=false;const e=validate(x).errors;assert.ok(e.includes('field-glands-not-on-sealed-service-end'));assert.ok(e.includes('agriculture-core-outside-sealed-central-envelope'));assert.ok(e.includes('agriculture-antenna-not-on-opposite-capsule-end'));assert.ok(e.includes('climate-vent-placement-unverified'))})
test('sealed mounting bosses, strain path and antenna field fail closed',()=>{const x=valid();x.mountingBosses[0].sealedBossInterfaceVerified=false;x.mountingBosses[1].inAntennaOrVentRegion=true;x.cableAndProbeStrain.loadPathClearOfSealAndComponents=false;x.antennaKeepout.noMetalBatteryOrFastenersInFieldRegion=false;const e=validate(x).errors;assert.ok(e.includes('mounting-boss-1-seal-keepout-unverified'));assert.ok(e.includes('mounting-boss-2-intrudes-functional-end'));assert.ok(e.includes('agriculture-gland-strain-path-unverified'));assert.ok(e.includes('agriculture-antenna-keepout-unverified'))})
