import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {audioDspProductionProposal,validateAudioDspProductionProposal} from '../lib/phase2c/templates/audio-dsp.mjs'
test('Board035 PD sink cannot pass as digital audio processor',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[34],34));assert.equal(g.ok,false);for(const c of ['audio-dsp-processor-missing','audio-codec-converter-missing','audio-input-connector-missing','audio-output-connector-missing','audio-input-conditioning-missing','audio-output-conditioning-missing','audio-master-clock-missing','audio-low-noise-power-missing','audio-pop-mute-protection-missing','audio-performance-evidence-missing','audio-grounding-layout-evidence-missing','audio-dsp-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board035 reuses approved control storage assets and blocks unresolved audio chain',()=>{const p=audioDspProductionProposal,g=validateAudioDspProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('audio-dsp-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_CODEC','U_DSP','Y_MCLK','P_APWR','P_DPWR','J_IN','P_IN','J_OUT','P_OUT','J_DIG','P_GND','P_TEST']);for(const r of ['U_CTRL','U_BOOT','U_META','C_DEC','FB_A'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board035 requires jitter noise distortion EMC grounding and loopback evidence',()=>{for(const k of ['mclkBclkLrclkJitterTimingVerified','inputNoiseGainHeadroomVerified','outputLoadDistortionStabilityVerified','frequencyResponseSnrThdnVerified','crosstalkDynamicRangeVerified','analogDigitalRailNoiseVerified','groundReturnShieldPinOneVerified','emcEsdImmunityVerified','productionAllChannelLoopbackVerified'])assert.ok(audioDspProductionProposal.evidenceRequired.includes(k),k)})
test('Board035 audio-jack outline stays inside 1600 mm2',()=>{const p=audioDspProductionProposal,g=validateAudioDspProductionProposal(p);assert.equal(g.areaMm2,1540);assert.ok(g.areaMm2<=1600);assert.equal(p.outline.purposefulFeatures.audioJackEdge.jackCount,2);assert.equal(p.outline.purposefulFeatures.analogDigitalMoatRequired,true)})
