import test from'node:test';import assert from'node:assert/strict';import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs';import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs';import{AUDIO_DSP_MECHANICAL_CONTRACT as contract,validateAudioDspMechanicalGeometry as validate}from'../lib/phase2c/audio-dsp-mechanical-contract.mjs'
const outline=[[0,0],[50,0],[50,30],[30,30],[30,25],[20,25],[20,30],[0,30]]
const valid=()=>({outline,outlineClosed:true,rackNotch:{widthMm:10,depthMm:5,inwardCutoutVerified:true,edgeCutsVerified:true,chassisRailAligned:true,insertionToolClearanceVerified:true},placements:{audioConnectors:[{frontPanelAligned:true},{frontPanelAligned:true}],powerAndService:{rearEdgeAligned:true},dspCore:{centralEnvelopeVerified:true}},signalZones:{analogDigitalBoundaryVerified:true,powerKeptOutOfAnalogConnectorZone:true,connectorShellClearanceVerified:true},cableExit:{clearOfRackNotchAndFasteners:true},assemblyHeight:{rackEnvelopeVerified:true},rackMountingHoles:[{x:6,y:6,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,chassisDatumAligned:true},{x:44,y:6,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,chassisDatumAligned:true}]})
test('Board035 manifest preserves rack-notch intent and 1600mm2 cap',()=>{const b=manifest.boards[34];assert.equal(b.id,'035_AUDIO_DSP');assert.equal(b.outline.family,'rack notch-audio-dsp');assert.equal(b.maximumAreaMm2,1600);assert.equal(contract.maximumAreaMm2,1600)})
test('current catalog outline exceeds cap and lacks rack evidence',()=>{const d=catalogDefinition(manifest.boards[34],34),r=validate({outline:d.outlinePoints,outlineClosed:true});assert.equal(r.ok,false);assert.ok(r.areaMm2>1600);assert.ok(r.errors.includes('purposeful-rack-notch-unverified'))})
test('purposeful rack-notch audio DSP fits the cap',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,1450)})
test('rack notch and chassis interface fail closed',()=>{const x=valid();x.rackNotch.depthMm=2;x.rackNotch.chassisRailAligned=false;const e=validate(x).errors;assert.ok(e.includes('purposeful-rack-notch-unverified'));assert.ok(e.includes('rack-notch-chassis-interface-unverified'))})
test('front rear and mixed-signal zones fail closed',()=>{const x=valid();x.placements.audioConnectors[0].frontPanelAligned=false;x.placements.powerAndService.rearEdgeAligned=false;x.signalZones.analogDigitalBoundaryVerified=false;const e=validate(x).errors;assert.ok(e.includes('audio-connectors-not-front-panel-aligned'));assert.ok(e.includes('audio-power-service-not-rear-aligned'));assert.ok(e.includes('audio-mixed-signal-mechanical-zones-unverified'))})
test('mounting and rack service clearance fail closed',()=>{const x=valid();x.rackMountingHoles[0].chassisDatumAligned=false;x.rackMountingHoles[1].allLayersKeepout=false;x.cableExit.clearOfRackNotchAndFasteners=false;const e=validate(x).errors;assert.ok(e.includes('rack-mount-1-invalid'));assert.ok(e.includes('rack-mount-2-keepout-unverified'));assert.ok(e.includes('audio-rack-service-clearance-unverified'))})
