import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{BATTERY_BMS_MECHANICAL_CONTRACT as contract,validateBatteryBmsMechanicalGeometry as validate}from'../lib/phase2c/battery-bms-mechanical-contract.mjs'

const outline=[[0,0],[22,0],[24,2],[32,2],[34,0],[56,0],[56,24],[34,24],[32,22],[24,22],[22,24],[0,24]]
const valid=()=>({outline,outlineClosed:true,body:{widthMm:56,heightMm:24},packMechanicalDrawingVerified:true,packDatumToleranceVerified:true,registrationReliefs:[{depthMm:2,widthMm:8},{depthMm:2,widthMm:8}],currentTerminals:{negative:{minX:1,maxX:5},positive:{minX:51,maxX:55},edgeClearanceMm:1.2,edgeKeepoutVerified:true},cellCount:4,balanceConnector:{pinCount:5,minX:24,maxX:32,serviceAccessVerified:true},powerStage:{minX:6,maxX:17,switchCopperAreaMm2:50,shuntCopperAreaMm2:35,thermalViaCount:8,allCopperLayersTied:true},monitorPlacement:{minX:22,maxX:36},temperatureSensors:[{packContactVerified:true},{packContactVerified:true}],senseToPowerKeepoutVerified:true,packVoltagePrimarySourceVerified:true,cellTabInsulationKeepoutVerified:true})

test('Board019 manifest preserves pack-matched BMS intent and 1600mm2 cap',()=>{const b=manifest.boards[18];assert.equal(b.id,'019_BATTERY_BMS');assert.match(b.outline.family,/pack matched/);assert.equal(b.maximumAreaMm2,1600);assert.equal(contract.maximumAreaMm2,1600)})
test('current PD-sink clone fails pack area and datum requirements',()=>{const d=catalogDefinition(manifest.boards[18],18),r=validate({outline:d.outlinePoints,outlineClosed:true,body:{widthMm:58,heightMm:38}});assert.equal(r.areaMm2,2664.89);assert.equal(r.ok,false);assert.ok(r.errors.includes('bms-outline-exceeds-maximum-area'));assert.ok(r.errors.includes('bms-pack-datum-unverified'))})
test('keyed pack strip is purposeful and under maximum area',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,1304);assert.equal(r.bounds.width,56);assert.equal(r.bounds.height,24)})
test('pack registration and opposite current tabs fail closed',()=>{const x=valid();x.registrationReliefs[0].depthMm=1;x.currentTerminals.negative.maxX=12;x.currentTerminals.positive.minX=45;const e=validate(x).errors;assert.ok(e.includes('bms-registration-relief-1-undersized'));assert.ok(e.includes('bms-negative-terminal-not-on-left-edge'));assert.ok(e.includes('bms-positive-terminal-not-on-right-edge'))})
test('balance connector must match verified series-cell count',()=>{const x=valid();x.cellCount=6;x.balanceConnector.pinCount=5;x.balanceConnector.serviceAccessVerified=false;const e=validate(x).errors;assert.ok(e.includes('bms-balance-connector-pin-count-mismatch'));assert.ok(e.includes('bms-balance-connector-placement-invalid'))})
test('switch, shunt, sensing and insulation evidence are mandatory',()=>{const x=valid();x.powerStage.switchCopperAreaMm2=20;x.temperatureSensors.pop();x.senseToPowerKeepoutVerified=false;x.cellTabInsulationKeepoutVerified=false;const e=validate(x).errors;assert.ok(e.includes('bms-switch-shunt-thermal-placement-unverified'));assert.ok(e.includes('bms-pack-temperature-sensing-incomplete'));assert.ok(e.includes('bms-sense-power-spacing-unverified'));assert.ok(e.includes('bms-cell-tab-insulation-keepout-unverified'))})
