import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{BATTERY_CHARGER_MECHANICAL_CONTRACT as contract,validateBatteryChargerMechanicalGeometry as validate}from'../lib/phase2c/battery-charger-mechanical-contract.mjs'

const outline=[[0,0],[46,0],[46,34],[30,34],[30,38],[16,38],[16,34],[0,34]]
const valid=()=>({outline,outlineClosed:true,body:{widthMm:46,heightMm:34},thermalTab:{projectionMm:4,spanMm:14,fastener:{x:23,y:36,diameterMm:3.2,keepoutRadiusMm:3.2,allLayersKeepout:true},copperAreaMm2:50,thermalViaCount:10,allCopperLayersTied:true},placements:{sourceInput:{minX:1,maxX:5},batteryConnector:{minX:41,maxX:45},powerStage:{minX:18,maxX:29,minY:27,maxY:33},ntcConnector:{minX:38,maxX:45,batteryContactVerified:true}},powerStageToTabRootMm:2,ntcToPowerStageMm:12,highCurrentPathCapacityVerified:true,switchNodeKeepoutVerified:true,packVoltagePrimarySourceVerified:true,thermalModelPrimarySourceVerified:true,connectorPolarityKeyingVerified:true})

test('Board020 manifest preserves charger thermal-tab intent and 1950mm2 cap',()=>{const b=manifest.boards[19];assert.equal(b.id,'020_BATTERY_CHARGER');assert.match(b.outline.family,/thermal tab/);assert.equal(b.maximumAreaMm2,1950);assert.equal(contract.maximumAreaMm2,1950)})
test('current PD-sink octagon fails area and functional-tab checks',()=>{const d=catalogDefinition(manifest.boards[19],19),r=validate({outline:d.outlinePoints,outlineClosed:true,body:{widthMm:58,heightMm:38}});assert.equal(r.areaMm2,2962.25);assert.equal(r.ok,false);assert.ok(r.errors.includes('battery-charger-outline-exceeds-maximum-area'));assert.ok(r.errors.includes('battery-charger-thermal-tab-undersized'))})
test('purposeful fastened thermal tab remains under maximum area',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,1620);assert.equal(r.bounds.width,46);assert.equal(r.bounds.height,38)})
test('thermal tab requires fastener keepout, copper and vias',()=>{const x=valid();delete x.thermalTab.fastener;x.thermalTab.copperAreaMm2=20;x.thermalTab.thermalViaCount=2;const e=validate(x).errors;assert.ok(e.includes('battery-charger-tab-fastener-missing'));assert.ok(e.includes('battery-charger-tab-fastener-keepout-unverified'));assert.ok(e.includes('battery-charger-tab-thermal-path-unverified'))})
test('source, battery and power stage use ordered service edges',()=>{const x=valid();x.placements.sourceInput.maxX=10;x.placements.batteryConnector.minX=35;x.placements.powerStage.minX=5;const e=validate(x).errors;assert.ok(e.includes('battery-charger-source-not-on-left-edge'));assert.ok(e.includes('battery-charger-battery-not-on-right-edge'));assert.ok(e.includes('battery-charger-power-stage-outside-tab-zone'))})
test('temperature, current, switching and source evidence fail closed',()=>{const x=valid();x.ntcToPowerStageMm=4;x.highCurrentPathCapacityVerified=false;x.switchNodeKeepoutVerified=false;x.packVoltagePrimarySourceVerified=false;x.connectorPolarityKeyingVerified=false;const e=validate(x).errors;assert.ok(e.includes('battery-charger-temperature-sense-placement-invalid'));assert.ok(e.includes('battery-charger-current-path-capacity-unverified'));assert.ok(e.includes('battery-charger-switch-node-keepout-unverified'));assert.ok(e.includes('battery-charger-source-backed-design-evidence-missing'));assert.ok(e.includes('battery-charger-connector-keying-unverified'))})
