import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {batteryChargerProductionProposal,validateBatteryChargerProductionProposal} from '../lib/phase2c/templates/battery-charger.mjs'
test('Board020 generic PD sink cannot pass as a safe battery charger',()=>{const d=catalogDefinition(manifest.boards[19],19),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);for(const c of ['battery-charger-controller-missing','battery-charger-pack-connector-missing','battery-charger-current-programming-missing','battery-charger-voltage-chemistry-evidence-missing','battery-charger-temperature-qualification-missing','battery-charger-termination-status-missing','battery-charger-reverse-or-power-path-missing','battery-charger-safety-timer-missing','battery-charger-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board020 blocks chemistry and pack dependent charger hardware while reusing only exact protection candidates',()=>{const p=batteryChargerProductionProposal,g=validateBatteryChargerProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('battery-charger-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_CHG','P_STAGE','J_PACK','R_ICHG','TH_PACK','P_STATUS','P_TIMER','J_SRC','P_PACK_PROTECT']);for(const r of ['F_IN','Q_REV','D_IN','C_IN','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board020 completeness gate rejects absent chemistry pack source load profile and thermal envelopes',()=>{const g=validateBatteryChargerProductionProposal(batteryChargerProductionProposal);for(const code of ['battery-charger-chemistry-envelope-undeclared','battery-charger-pack-envelope-undeclared','battery-charger-source-envelope-undeclared','battery-charger-system-load-envelope-undeclared','battery-charger-charge-profile-envelope-undeclared','battery-charger-thermal-envelope-undeclared'])assert.ok(g.errors.includes(code),code)})
test('Board020 requires chemistry temperature termination timer power-path and thermal evidence',()=>{for(const k of ['chemistryCellPackVerified','temperatureQualificationVerified','prechargeTerminationRechargeVerified','reverseCurrentPowerPathVerified','safetyTimerWatchdogVerified','switchingStageLossVerified','productionChargeFaultThermalTestVerified'])assert.ok(batteryChargerProductionProposal.evidenceRequired.includes(k),k)})
test('Board020 charging-cradle outline stays inside 1950 mm2',()=>{const g=validateBatteryChargerProductionProposal(batteryChargerProductionProposal);assert.equal(g.areaMm2,1840);assert.ok(g.areaMm2<=1950);assert.deepEqual(batteryChargerProductionProposal.outline.purposefulFeatures.packCradleNotch,{widthMm:20,depthMm:4})})
