import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {batteryBmsProductionProposal,validateBatteryBmsProductionProposal} from '../lib/phase2c/templates/battery-bms.mjs'
test('Board019 generic PD sink cannot pass as a battery BMS',()=>{const d=catalogDefinition(manifest.boards[18],18),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);for(const c of ['bms-cell-monitor-missing','bms-cell-tap-connector-missing','bms-balance-channels-missing','bms-charge-discharge-switches-missing','bms-pack-current-sense-missing','bms-temperature-sense-missing','bms-pack-protection-missing','bms-threshold-evidence-missing','bms-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board019 defines 4S taps and four balance channels while blocking exact pack hardware',()=>{const p=batteryBmsProductionProposal,g=validateBatteryBmsProductionProposal(p);assert.equal(p.seriesCellCount,4);assert.equal(p.bom.find(x=>x.ref==='R_CELL').quantity,4);assert.equal(p.bom.find(x=>x.ref==='P_BAL').quantity,4);assert.equal(g.ok,false);assert.ok(g.errors.includes('bms-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_BMS','J_CELL','R_CELL','P_BAL','Q_CHG','Q_DSG','R_SHUNT','TH_PACK','J_PACK','F_PACK','P_PRE'])})
test('Board019 completeness gate rejects absent chemistry cell pack fault thermal and charger envelopes',()=>{const g=validateBatteryBmsProductionProposal(batteryBmsProductionProposal);for(const code of ['bms-chemistry-envelope-undeclared','bms-cell-envelope-undeclared','bms-pack-envelope-undeclared','bms-current-fault-envelope-undeclared','bms-thermal-envelope-undeclared','bms-charger-port-envelope-undeclared'])assert.ok(g.errors.includes(code),code)})
test('Board019 requires threshold current temperature connector and safety evidence',()=>{for(const k of ['overvoltageUndervoltageThresholdsVerified','overcurrentShortCircuitThresholdsVerified','temperatureCutoffsVerified','packCurrentShuntKelvinVerified','secondaryProtectionFaultEnergyVerified','configurationCalibrationArtifactVerified','productionCellFaultThermalTestVerified'])assert.ok(batteryBmsProductionProposal.evidenceRequired.includes(k),k)})
test('Board019 pack-matched outline stays inside 1600 mm2',()=>{const g=validateBatteryBmsProductionProposal(batteryBmsProductionProposal);assert.equal(g.areaMm2,1464);assert.ok(g.areaMm2<=1600);assert.equal(batteryBmsProductionProposal.outline.purposefulFeatures.packMountEars,2);assert.equal(batteryBmsProductionProposal.outline.purposefulFeatures.highCurrentAndSensePartitionRequired,true)})
