import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{BLDC_CONTROLLER_MECHANICAL_CONTRACT as contract,validateBldcControllerMechanicalGeometry as validate}from'../lib/phase2c/bldc-controller-mechanical-contract.mjs'

const center={x:30,y:30},polar=(r,degrees)=>({x:center.x+r*Math.cos(degrees*Math.PI/180),y:center.y+r*Math.sin(degrees*Math.PI/180)}),outline=Array.from({length:24},(_,i)=>{const p=polar(29,i*15);return[p.x,p.y]})
const valid=()=>({outline,outlineClosed:true,center,motorPilot:{diameterMm:12,primaryMechanicalDrawingVerified:true,nonPlatedCutout:true,boardKeepoutBeyondPilotMm:2,allLayersKeepout:true},mountingHoles:[45,135,225,315].map(a=>({...polar(22,a),diameterMm:3.2,keepoutRadiusMm:3.2,allLayersKeepout:true})),powerStages:[0,120,240].map(a=>({...polar(16,a),thermalCopperAreaMm2:50,thermalViaCount:10,allCopperLayersTied:true})),phaseConnectors:[0,120,240].map(a=>polar(27,a)),dcInput:polar(25,180),controlPlacement:{outsidePilotKeepout:true,insideMountingPattern:true},highCurrentCopperEdgeClearanceVerified:true})

test('Board016 manifest preserves circular motor mount and 3350mm2 cap',()=>{const b=manifest.boards[15];assert.equal(b.id,'016_BLDC_CONTROLLER');assert.match(b.outline.family,/circular motor mount/);assert.equal(b.maximumAreaMm2,3350);assert.equal(contract.maximumAreaMm2,3350)})
test('current elongated octagon fails circularity and purposeful mount checks',()=>{const d=catalogDefinition(manifest.boards[15],15),r=validate({outline:d.outlinePoints,outlineClosed:true,center:{x:29,y:19}});assert.equal(r.areaMm2,2754.25);assert.equal(r.ok,false);assert.ok(r.errors.includes('circular-motor-outline-invalid'));assert.ok(r.errors.includes('bldc-outline-not-circular'));assert.ok(r.errors.includes('motor-pilot-opening-unverified'))})
test('24-sided concentric motor mount is purposeful and under area cap',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.ok(r.areaMm2<3350);assert.ok(r.bounds.width>57&&r.bounds.height>57)})
test('motor pilot and symmetric mounting pattern fail closed',()=>{const x=valid();x.motorPilot.primaryMechanicalDrawingVerified=false;x.mountingHoles[0].x+=2;x.mountingHoles[1].keepoutRadiusMm=1;const e=validate(x).errors;assert.ok(e.includes('motor-pilot-opening-unverified'));assert.ok(e.includes('bldc-mounting-radius-not-concentric'));assert.ok(e.includes('bldc-mounting-hole-2-keepout-unverified'))})
test('three phase stages and terminals require 120-degree symmetry',()=>{const x=valid();x.powerStages[1]={...x.powerStages[1],...polar(16,90),thermalViaCount:2};x.phaseConnectors.pop();const e=validate(x).errors;assert.ok(e.includes('bldc-power-stage-angular-spacing-invalid'));assert.ok(e.includes('bldc-power-stage-2-thermal-path-unverified'));assert.ok(e.includes('bldc-phase-connector-count-invalid'))})
test('DC input, control annulus and edge copper need explicit clearance evidence',()=>{const x=valid();x.dcInput=center;x.controlPlacement.outsidePilotKeepout=false;x.highCurrentCopperEdgeClearanceVerified=false;const e=validate(x).errors;assert.ok(e.includes('bldc-dc-input-not-on-board-edge'));assert.ok(e.includes('bldc-control-placement-invalid'));assert.ok(e.includes('bldc-high-current-edge-clearance-unverified'))})
