import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {bldcControllerProductionProposal,validateBldcControllerProductionProposal} from '../lib/phase2c/templates/bldc-controller.mjs'
test('Board016 generic shell cannot pass as a three-phase BLDC controller',()=>{const d=catalogDefinition(manifest.boards[15],15),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);for(const c of ['bldc-controller-missing','bldc-three-phase-gate-drive-missing','bldc-power-switches-missing','bldc-current-sense-missing','bldc-motor-connector-missing','bldc-dc-link-decoupling-missing','bldc-power-entry-protection-missing','bldc-rotor-position-interface-missing','bldc-safe-gate-disable-missing','bldc-regeneration-handling-missing'])assert.ok(g.errors.includes(c),c)})
test('Board016 requires six switches and blocks every envelope-dependent exact power asset',()=>{const p=bldcControllerProductionProposal,g=validateBldcControllerProductionProposal(p);assert.equal(p.bom.find(x=>x.ref==='Q_PHASE').quantity,6);assert.equal(g.ok,false);assert.ok(g.errors.includes('bldc-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_CTRL','U_GATE','Q_PHASE','R_GATE','R_SHUNT','J_MOTOR','J_PWR','J_ROTOR','P_REGEN','P_DISABLE']);for(const r of ['F1','Q_REV','D_TVS','C_BULK','C_HF'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board016 completeness gate rejects absent motor bus commutation rotor and regeneration envelopes',()=>{const g=validateBldcControllerProductionProposal(bldcControllerProductionProposal);for(const code of ['bldc-motor-envelope-undeclared','bldc-bus-envelope-undeclared','bldc-commutation-envelope-undeclared','bldc-rotor-envelope-undeclared','bldc-regeneration-envelope-undeclared'])assert.ok(g.errors.includes(code),code)})
test('Board016 requires regeneration safe-disable current thermal and rotor evidence',()=>{for(const k of ['currentSenseOvercurrentVerified','rotorPositionStartupVerified','safeGateDisableVerified','regenerationHandled','mosfetLossSoaVerified','thermalCopperViaVerified','productionSpinStallFaultTestVerified'])assert.ok(bldcControllerProductionProposal.evidenceRequired.includes(k),k)})
test('Board016 circular motor-mount outline stays inside 3350 mm2',()=>{const g=validateBldcControllerProductionProposal(bldcControllerProductionProposal);assert.ok(Math.abs(g.areaMm2-3196.35)<.1,g.areaMm2);assert.ok(g.areaMm2<=3350);assert.equal(bldcControllerProductionProposal.outline.purposefulFeatures.circularMotorMount,true);assert.equal(bldcControllerProductionProposal.outline.purposefulFeatures.mountingHoleCount,4)})
