import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{BLE_BEACON_MECHANICAL_CONTRACT as contract,validateBleBeaconMechanicalGeometry as validate}from'../lib/phase2c/ble-beacon-mechanical-contract.mjs'

const organicOutline=[[4,0],[30,0],[34,3],[36,8],[36,16],[34,21],[30,24],[4,24],[0,21],[-2,16],[-2,8],[0,3]]
const valid=()=>({outline:organicOutline,outlineClosed:true,organicProfile:{minimumEdgeRadiusMm:3,tangentTransitionsVerified:true,noAcuteExteriorCorners:true,skinAndEnclosureClearanceVerified:true,maximumAssemblyHeightVerified:true},retention:{centerXmm:2,centerYmm:12,holeDiameterMm:3.5,copperKeepoutRadiusMm:3.5,allLayersKeepout:true,edgeClearanceVerified:true},placements:{battery:{minX:9,maxX:23},antenna:{minX:28,maxX:35}},antennaKeepout:{allCopperLayers:true,noPlanesTracksOrVias:true,noComponentsExceptFeedAndMatching:true,enclosureAndBodyClearanceVerified:true},separation:{antennaToBatteryMm:6,retentionLoadPathClearOfComponents:true},serviceAccessWithinEnvelope:true})

test('Board025 manifest preserves wearable-organic intent and 900mm2 cap',()=>{const board=manifest.boards[24];assert.equal(board.id,'025_BLE_BEACON');assert.equal(board.outline.family,'wearable organic-ble-beacon');assert.equal(board.maximumAreaMm2,900);assert.equal(contract.maximumAreaMm2,900)})
test('current catalog outline exceeds the compact cap and lacks wearable evidence',()=>{const definition=catalogDefinition(manifest.boards[24],24),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2>900);assert.ok(result.errors.includes('ble-beacon-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('wearable-organic-edge-treatment-unverified'))})
test('purposeful organic beacon envelope fits the maximum area',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,844);assert.equal(result.bounds.width,38);assert.equal(result.bounds.height,24)})
test('organic edge treatment and wearable clearances fail closed',()=>{const x=valid();x.organicProfile.minimumEdgeRadiusMm=1;x.organicProfile.tangentTransitionsVerified=false;x.organicProfile.skinAndEnclosureClearanceVerified=false;const e=validate(x).errors;assert.ok(e.includes('wearable-organic-edge-treatment-unverified'));assert.ok(e.includes('wearable-envelope-clearance-unverified'))})
test('retention feature requires edge clearance, keepout and clear load path',()=>{const x=valid();x.retention.holeDiameterMm=2;x.retention.allLayersKeepout=false;x.separation.retentionLoadPathClearOfComponents=false;const e=validate(x).errors;assert.ok(e.includes('wearable-retention-feature-invalid'));assert.ok(e.includes('wearable-retention-keepout-unverified'));assert.ok(e.includes('retention-load-path-component-clearance-unverified'))})
test('battery and enclosure stay out of the antenna end',()=>{const x=valid();x.placements.battery.maxX=30;x.placements.antenna.minX=22;x.antennaKeepout.noPlanesTracksOrVias=false;x.separation.antennaToBatteryMm=2;const e=validate(x).errors;assert.ok(e.includes('battery-outside-placement-envelope'));assert.ok(e.includes('ble-antenna-not-on-opposite-end'));assert.ok(e.includes('ble-antenna-keepout-unverified'));assert.ok(e.includes('ble-antenna-battery-separation-insufficient'))})
