import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {bleBeaconProductionProposal,validateBleBeaconProductionProposal} from '../lib/phase2c/templates/ble-beacon.mjs'
test('Board025 generic USB sensor shell cannot pass as a BLE beacon',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[24],24));assert.equal(g.ok,false);for(const c of ['ble-beacon-radio-missing','ble-beacon-antenna-missing','ble-beacon-battery-source-missing','ble-beacon-low-iq-power-missing','ble-beacon-programming-interface-missing','ble-beacon-identity-provisioning-missing','ble-beacon-energy-budget-missing','ble-beacon-rf-compliance-missing','ble-beacon-category-mapped-to-usb-sensor-shell'])assert.ok(g.errors.includes(c),c)})
test('Board025 blocks every unresolved BLE RF clock battery security and test asset',()=>{const p=bleBeaconProductionProposal,g=validateBleBeaconProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('ble-beacon-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_BLE','J_ANT','P_RF','D_RF','Y_HF','Y_LF','BT1','P_PWR','J_PROG','P_ID','P_TEST']);for(const r of ['U_SENSOR','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board025 requires advertising energy security detuning and production evidence',()=>{for(const k of ['bleProtocolAdvertisingVerified','hfLfClockAccuracyVerified','antennaEfficiencyEnclosureBodyDetuningVerified','rangeLatencyMissProbabilityVerified','advertisingEventCurrentVerified','batteryPulseEnergyTemperatureLifeVerified','identityKeysPrivacyProvisioningVerified','wearableIngressThermalMechanicalVerified','productionRfClockCurrentIdentityTestVerified'])assert.ok(bleBeaconProductionProposal.evidenceRequired.includes(k),k)})
test('Board025 compact antenna-tab outline stays inside 900 mm2',()=>{const p=bleBeaconProductionProposal,g=validateBleBeaconProductionProposal(p);assert.equal(g.areaMm2,832);assert.ok(g.areaMm2<=900);assert.deepEqual(p.outline.purposefulFeatures.antennaTab,{projectionMm:4,spanMm:12});assert.equal(p.outline.purposefulFeatures.antennaCopperKeepoutRequired,true)})
