import test from'node:test'
import assert from'node:assert/strict'
import{BOARD006_ISOLATION_REMEDIATION as proposal,validateBoard006IsolationRemediation as validate}from'../lib/phase2c/board006-isolation-remediation.mjs'

const network=(channel)=>({RTHR:{ref:`R${channel}1`,ohms:1000,ratedPowerW:.25,primarySourceVerified:true,designCalculationVerified:true},RSENSE:{ref:`R${channel}2`,ohms:562,ratedPowerW:.125,primarySourceVerified:true,designCalculationVerified:true},CIN:{ref:`C${channel}1`,farads:10e-9,ratedVoltageV:100,primarySourceVerified:true,designCalculationVerified:true}})
const valid=()=>({isolatedPower:{mpn:'THI 2-0511M',primarySourceUrl:proposal.isolatedPower.primarySource,primarySourceVerified:true,ratingUnit:'VACrms',isolationVrms:3000,inputV:5,outputV:5,outputCurrentMa:400,pinMap:{1:'GND',7:'NC',8:'NC',9:'FIELD_5V',10:'FIELD_GND',16:'5V'}},iso1212:{mpn:'ISO1212DBQR',primarySourceUrl:proposal.iso1212.primarySource,primarySourceVerified:true,channels:[network(1),network(2)]},isolationCorridor:{allLayersKeepoutVerified:true,noCopperPlanesTracksViasOrMountMetal:true,clearanceMm:3.2,creepageMm:4},domainAudit:{fieldGround:'FIELD_GND',logicGround:'GND',groundsGalvanicallyDistinct:true},assetBinding:{symbolFootprintPinMapVerified:true,exactMpnVerified:true}})

test('proposal is explicit non-acceptance and links only primary manufacturer sources',()=>{assert.equal(proposal.status,'PROPOSAL_NOT_ACCEPTANCE');assert.match(proposal.isolatedPower.primarySource,/tracopower\.com/);assert.match(proposal.iso1212.primarySource,/ti\.com/);assert.equal(proposal.isolatedPower.sourceIsolationVrms,3000)})
test('source-backed 3000VACrms replacement and complete ISO1212 networks pass the design gate',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.proposalOnly,true)})
test('DC ratings cannot be laundered into the 2500Vrms system gate',()=>{const x=valid();x.isolatedPower.ratingUnit='VDC';x.isolatedPower.isolationVrms=5200;assert.ok(validate(x).errors.includes('replacement-isolated-power-below-2500vrms'))})
test('replacement pin map and exact primary-source identity fail closed',()=>{const x=valid();x.isolatedPower.pinMap[1]='5V';x.isolatedPower.pinMap[9]='GND';x.isolatedPower.primarySourceVerified=false;const e=validate(x).errors;assert.ok(e.includes('replacement-isolated-power-pin-1-must-be-GND'));assert.ok(e.includes('replacement-isolated-power-pin-9-must-be-FIELD_5V'));assert.ok(e.includes('replacement-isolated-power-primary-source-unverified'))})
test('each ISO1212 channel requires unique value-bearing RTHR RSENSE and CIN evidence',()=>{const x=valid();delete x.iso1212.channels[0].CIN;x.iso1212.channels[1].RTHR.ref=x.iso1212.channels[0].RTHR.ref;x.iso1212.channels[1].RSENSE.ohms=200;const e=validate(x).errors;assert.ok(e.includes('iso1212-channel-1-cin-evidence-incomplete'));assert.ok(e.includes('iso1212-channel-2-rthr-reference-not-unique'));assert.ok(e.includes('iso1212-channel-2-rsense-not-type1-type3-562ohm'))})
test('geometry domain separation and production asset binding remain mandatory',()=>{const x=valid();x.isolationCorridor.allLayersKeepoutVerified=false;x.isolationCorridor.creepageMm=2;x.domainAudit.groundsGalvanicallyDistinct=false;x.assetBinding.symbolFootprintPinMapVerified=false;const e=validate(x).errors;assert.ok(e.includes('board006-isolation-corridor-unverified'));assert.ok(e.includes('board006-isolation-creepage-below-4mm'));assert.ok(e.includes('board006-field-logic-domain-audit-failed'));assert.ok(e.includes('replacement-isolated-power-asset-binding-unverified'))})
