import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition} from '../lib/phase2c/catalog-production-engine.mjs'
import {board008PlacementPreferences,createBoard008MechanicalPlacementFixture,validateBoard008MechanicalPlacementFixture} from '../lib/phase2c/board008-mechanical-placement-contract.mjs'

test('Board008 fixture has coherent sub-3350mm2 dual-port mechanics and routing',()=>{const f=createBoard008MechanicalPlacementFixture(),r=validateBoard008MechanicalPlacementFixture(f);assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,2848);assert.deepEqual(r.bounds,{minX:0,maxX:68,minY:0,maxY:44,width:68,height:44});assert.equal(f.holes.length,4);assert.equal(r.serviceZoneCount,4);assert.equal(r.corridorCount,6)})
test('Board008 fails closed on merged ports, missing mount, and lost 3V3 capacity',()=>{const f=createBoard008MechanicalPlacementFixture();f.serviceZones.find(x=>x.id==='CAN2_PORT').minY=10;f.serviceZones.find(x=>x.id==='CAN2_PORT').maxY=14;f.holes.pop();f.corridors.find(x=>x.id==='3V3_BACKBONE').widthMm=.8;const e=validateBoard008MechanicalPlacementFixture(f).errors;for(const code of['board008-can-port-service-zones-not-separated','board008-mount-count-invalid','board008-power-routing-capacity-insufficient'])assert.ok(e.includes(code),code)})
test('Board008 catalog definition projects the reusable mechanical contract',()=>{const d=catalogDefinition(manifest.boards[7],7),f=createBoard008MechanicalPlacementFixture();assert.deepEqual(d.outlinePoints,f.outline);assert.deepEqual(d.holes,f.holes);assert.equal(d.placementTopologyId,'can-gateway-asymmetric-dual-port');assert.equal(d.mechanicalPlacementContract.serviceZones.length,4)})
test('Board008 placement preferences cover the expanded hardened BOM and separate both CAN paths',()=>{const p=board008PlacementPreferences();assert.equal(Object.keys(p).length,26);assert.ok(p.J2.ny<p.J3.ny);assert.ok(p.U2.ny<p.U4.ny);assert.deepEqual(p.J2.rotations,[90,270]);assert.deepEqual(p.J3.rotations,[90,270]);for(const ref of['Q1','D_PWR','C_BULK','JP1','JP2','R_BOOT','R_RESET','C_RESET','C4','C5','C6','C7'])assert.ok(p[ref],ref)})
