import test from'node:test'
import assert from'node:assert/strict'
import manifest from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition,validateCatalogSemanticTopology}from'../lib/phase2c/catalog-production-engine.mjs'
import{categorySchematicPinMaps,poeEthernetSensorCategoryPcbEvidence}from'../lib/real-board-proof.mjs'
import{approvedAssetFor}from'../lib/components/approved-production-assets.mjs'

test('Board009 projects only exact approved authoritative component identities',()=>{const d=catalogDefinition(manifest.boards[8],8);assert.equal(d.topologyId,'poe-sensor');assert.deepEqual(d.bom.map(x=>x.mpn),['W5500','ARJP11A-MASA-B-A-EMU2','Ag9905LP','Q22FA2380184517','BME280','UWT1A151MCL1GS']);for(const row of d.bom)assert.ok(approvedAssetFor(row.mpn),row.mpn);assert.deepEqual(approvedAssetFor('BME280').symbolPinMap,{1:'GND',2:'CSB',3:'SDI_SDA',4:'SCK_SCL',5:'SDO_ADDR',6:'VDDIO',7:'GND',8:'VDD'});assert.deepEqual(approvedAssetFor('ARJP11A-MASA-B-A-EMU2').symbolPinMap,{1:'ETH_TXP',2:'ETH_TXN',3:'ETH_RXP',4:'ETH_TX_CT',5:'ETH_RX_CT',6:'ETH_RXN',7:'POE_AUX',9:'POE_RECT_POS',10:'POE_RECT_NEG',11:'LED_YELLOW_A',12:'LED_YELLOW_K',13:'LED_GREEN_A',14:'LED_GREEN_K',SH:'CHASSIS'})})
test('Board009 schematic and PCB maps preserve exact package pins',()=>{const d=catalogDefinition(manifest.boards[8],8),m=categorySchematicPinMaps(d),pcb=poeEthernetSensorCategoryPcbEvidence();assert.deepEqual(m.U_POE,{1:'POE_5V',2:'POE_5V',3:'SELV_GND',5:'POE_RECT_POS',6:'POE_RECT_POS',7:'POE_RECT_NEG',8:'POE_RECT_NEG'});assert.equal(m.U_ETH[10],'W5500_EXRES');assert.equal(m.U_ETH[20],'W5500_TOCAP');assert.equal(m.U_ETH[22],'W5500_1V2');assert.equal(m.U_ETH[30],'XTAL_IN');assert.equal(m.U_ETH[31],'XTAL_OUT');assert.deepEqual(m.U_SENSOR,{1:'SELV_GND',2:'BME_CSB_STRAP',3:'I2C_SDA',4:'I2C_SCL',5:'BME_SDO_STRAP',6:'3V3',7:'SELV_GND',8:'3V3'});assert.equal(m.J_ETH.SH,'CHASSIS');assert.deepEqual(pcb.footprints.map(x=>x.ref),d.bom.map(x=>x.ref));assert.equal(new Set(pcb.nets.map(x=>x.number)).size,pcb.nets.length);assert.ok(!Object.values(m.U_POE).includes('GND'),'primary and SELV grounds must never be collapsed')})
test('Board009 remains fail closed until the sourceable architecture has its complete circuit and evidence',()=>{const d=catalogDefinition(manifest.boards[8],8),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);assert.match(d.bom.find(x=>x.ref==='J_ETH').role,/PoE-capable/);for(const code of['poe-sensor-cable-protection-missing','poe-sensor-isolation-barrier-missing','poe-sensor-classification-power-unverified','poe-sensor-isolation-safety-unverified','poe-sensor-signal-integrity-unverified'])assert.ok(g.errors.includes(code),code);assert.ok(!g.errors.includes('poe-sensor-magjack-not-poe-capable'));assert.ok(!g.errors.includes('poe-sensor-exact-poe-envelope-impossible'))})
