import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{CAMERA_TRIGGER_MECHANICAL_CONTRACT as contract,validateCameraTriggerMechanicalGeometry as validate}from'../lib/phase2c/camera-trigger-mechanical-contract.mjs'

const cameraMountOutline=[[3,0],[20,0],[20,-10],[28,-10],[28,0],[45,0],[48,3],[48,27],[45,30],[3,30],[0,27],[0,3]]
const valid=()=>({outline:cameraMountOutline,outlineClosed:true,mountTongue:{projectionMm:10,widthMm:8,leftShoulderMm:20,rightShoulderMm:20,edgeCutsVerified:true,centeredOnCameraAxis:true,enclosureAndCameraClearanceVerified:true},mountSlot:{lengthMm:7,widthMm:3.5,inTongue:true,edgeCutsVerified:true,copperKeepoutMm:3,allLayersKeepout:true,fastenerHeadClearanceVerified:true},placements:{cameraOutputs:[{minY:24,maxY:29},{minY:24,maxY:29}],triggerControl:{minY:8,maxY:17},serviceAndPower:{minY:1,maxY:5}},isolationCorridor:{betweenControlAndOutputs:true,allLayersClearanceVerified:true,noMountMetalBridge:true},cableExit:{synchronizedOutputsHaveEqualServicePath:true,clearOfMountAndFastener:true},auxiliaryMountingHoles:[{x:6,y:8,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inIsolationCorridor:false},{x:42,y:8,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inIsolationCorridor:false}]})

test('Board029 manifest preserves camera-mount intent and 2300mm2 cap',()=>{const board=manifest.boards[28];assert.equal(board.id,'029_CAMERA_TRIGGER');assert.equal(board.outline.family,'camera mount-camera-trigger');assert.equal(board.maximumAreaMm2,2300);assert.equal(contract.maximumAreaMm2,2300)})
test('current catalog outline exceeds cap and lacks functional camera mounting',()=>{const definition=catalogDefinition(manifest.boards[28],28),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2>2300);assert.ok(result.errors.includes('camera-trigger-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('purposeful-camera-mount-tongue-unverified'))})
test('purposeful centered camera-mount trigger fits the area cap',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,1502);assert.equal(result.bounds.width,48);assert.equal(result.bounds.height,40)})
test('mount tongue, camera axis and fastener slot fail closed',()=>{const x=valid();x.mountTongue.projectionMm=4;x.mountTongue.centeredOnCameraAxis=false;x.mountSlot.widthMm=2;x.mountSlot.allLayersKeepout=false;const e=validate(x).errors;assert.ok(e.includes('purposeful-camera-mount-tongue-unverified'));assert.ok(e.includes('camera-mount-axis-interface-unverified'));assert.ok(e.includes('camera-mount-slot-invalid'));assert.ok(e.includes('camera-mount-slot-keepout-unverified'))})
test('output, control and service placement preserves camera-side access',()=>{const x=valid();x.placements.cameraOutputs[0].minY=15;x.placements.triggerControl.maxY=25;x.placements.serviceAndPower.maxY=10;x.cableExit.clearOfMountAndFastener=false;const e=validate(x).errors;assert.ok(e.includes('camera-trigger-outputs-not-on-camera-edge'));assert.ok(e.includes('trigger-control-in-output-service-zone'));assert.ok(e.includes('service-and-power-not-opposite-camera-edge'));assert.ok(e.includes('camera-output-cable-exit-unverified'))})
test('mounting metal cannot bridge the isolated trigger corridor',()=>{const x=valid();x.isolationCorridor.noMountMetalBridge=false;x.auxiliaryMountingHoles[0].inIsolationCorridor=true;x.auxiliaryMountingHoles[1].allLayersKeepout=false;const e=validate(x).errors;assert.ok(e.includes('camera-trigger-isolation-corridor-unverified'));assert.ok(e.includes('auxiliary-mount-1-bridges-isolation-corridor'));assert.ok(e.includes('auxiliary-mount-2-keepout-unverified'))})
