import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{DATA_LOGGER_MECHANICAL_CONTRACT as contract,validateDataLoggerMechanicalGeometry as validate}from'../lib/phase2c/data-logger-mechanical-contract.mjs'

const cardNotchOutline=[[3,0],[49,0],[52,3],[52,32],[32,32],[32,27],[20,27],[20,32],[0,32],[0,3]]
const valid=()=>({outline:cardNotchOutline,outlineClosed:true,cardNotch:{widthMm:12,depthMm:5,inwardCutoutVerified:true,edgeCutsVerified:true,centeredOnCardBay:true,fingerAccessVerified:true},cardBay:{insertionClearanceMm:9,cardEnvelopeVerified:true,insertionAxisClear:true,retentionAndEjectTravelVerified:true,enclosureOpeningAligned:true},placements:{cardSocket:{minY:25,maxY:31},acquisitionChannels:{minY:8,maxY:19},serviceAndPower:{minY:1,maxY:5}},cardKeepout:{topAndBottomAssemblyClear:true,noTallPartsInExtractionPath:true},channelCableExit:{clearOfCardPath:true,strainReliefVerified:true},mountingHoles:[{x:6,y:7,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inCardInsertionPath:false},{x:46,y:7,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inCardInsertionPath:false}]})

test('Board028 manifest preserves card-notch intent and 1950mm2 cap',()=>{const board=manifest.boards[27];assert.equal(board.id,'028_DATA_LOGGER');assert.equal(board.outline.family,'card notch-data-logger');assert.equal(board.maximumAreaMm2,1950);assert.equal(contract.maximumAreaMm2,1950)})
test('current catalog outline is under cap but not accepted without functional notch evidence',()=>{const definition=catalogDefinition(manifest.boards[27],27),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2<1950);assert.ok(result.errors.includes('purposeful-card-notch-unverified'));assert.ok(result.errors.includes('removable-card-insertion-envelope-unverified'))})
test('purposeful inward card-notch logger fits the maximum area',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,1595);assert.equal(result.bounds.width,52);assert.equal(result.bounds.height,32)})
test('card notch requires real inward geometry and finger access',()=>{const x=valid();x.cardNotch.depthMm=2;x.cardNotch.inwardCutoutVerified=false;x.cardNotch.fingerAccessVerified=false;const e=validate(x).errors;assert.ok(e.includes('purposeful-card-notch-unverified'));assert.ok(e.includes('card-notch-access-unverified'))})
test('card bay insertion, retention and extraction keepout fail closed',()=>{const x=valid();x.cardBay.insertionClearanceMm=3;x.cardBay.retentionAndEjectTravelVerified=false;x.cardKeepout.noTallPartsInExtractionPath=false;const e=validate(x).errors;assert.ok(e.includes('removable-card-insertion-envelope-unverified'));assert.ok(e.includes('removable-card-retention-interface-unverified'));assert.ok(e.includes('card-extraction-keepout-unverified'))})
test('channels, service, cables and mounting remain clear of removable media',()=>{const x=valid();x.placements.acquisitionChannels.maxY=28;x.placements.serviceAndPower.maxY=12;x.channelCableExit.clearOfCardPath=false;x.mountingHoles[0].inCardInsertionPath=true;const e=validate(x).errors;assert.ok(e.includes('acquisition-channels-in-card-service-zone'));assert.ok(e.includes('service-and-power-not-opposite-card-edge'));assert.ok(e.includes('logger-channel-cable-exit-unverified'));assert.ok(e.includes('mounting-hole-1-intrudes-card-path'))})
