import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {dataLoggerProductionProposal,validateDataLoggerProductionProposal} from '../lib/phase2c/templates/data-logger.mjs'
test('Board028 generic sensor shell cannot pass as an acquisition logger',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[27],27));assert.equal(g.ok,false);for(const c of ['data-acquisition-front-end-missing','multi-channel-input-missing','removable-storage-missing','logger-storage-protection-missing','data-logger-input-protection-missing','data-logger-antialias-filter-missing','data-logger-voltage-reference-missing','data-logger-controller-buffering-missing','data-logger-timebase-missing','data-logger-card-power-control-missing','data-logger-power-fail-integrity-missing','data-logger-calibration-evidence-missing','data-logger-category-mapped-to-sensor-shell'])assert.ok(g.errors.includes(c),c)})
test('Board028 reuses approved controller memory power and blocks unresolved measurement chain',()=>{const p=dataLoggerProductionProposal,g=validateDataLoggerProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('data-logger-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_ADC','P_AFE','P_PROTECT','P_FILTER','U_REF','J_INPUT','J_SD','P_SD','U_RTC','U_FAIL','J_PWR','P_TEST']);for(const r of ['U_CTRL','U_BUFFER','U_CAL','U_PWR','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board028 requires accuracy noise throughput integrity thermal and power-fail evidence',()=>{for(const k of ['inputProtectionLeakageNoiseVerified','antiAliasSettlingVerified','adcLinearityNoiseThroughputVerified','referenceDriftDriveVerified','fullAccuracyErrorBudgetVerified','storageCapacityEnduranceThroughputVerified','recordChecksumAtomicIntegrityVerified','powerFailHoldUpFlushVerified','analogPowerThermalVerified','productionCalibrationStoragePowerFailTestVerified'])assert.ok(dataLoggerProductionProposal.evidenceRequired.includes(k),k)})
test('Board028 probe and storage outline stays inside 1950 mm2',()=>{const p=dataLoggerProductionProposal,g=validateDataLoggerProductionProposal(p);assert.equal(g.areaMm2,1930);assert.ok(g.areaMm2<=1950);assert.equal(p.outline.purposefulFeatures.portsOpposed,true);assert.equal(p.outline.purposefulFeatures.analogDigitalPartitionRequired,true)})
