import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{DRONE_PERIPHERAL_MECHANICAL_CONTRACT as contract,validateDronePeripheralMechanicalGeometry as validate}from'../lib/phase2c/drone-peripheral-mechanical-contract.mjs'

const outline=[[3,0],[43,0],[46,3],[46,43],[43,46],[3,46],[0,43],[0,3]],hole=(x,y)=>({x,y,diameterMm:3.2,keepoutRadiusMm:3.2,allLayersKeepout:true})
const valid=()=>({outline,outlineClosed:true,clippedCornerCount:4,mountingHoles:[hole(8,8),hole(38,8),hole(8,38),hole(38,38)],mountingPatternPrimarySourceVerified:true,centerKeepout:{widthMm:14,heightMm:14,allLayersAndCourtyard:true},edgeConnectorGroups:[{edge:'left',cableExitDepthMm:10,serviceAccessVerified:true},{edge:'right',cableExitDepthMm:10,serviceAccessVerified:true},{edge:'bottom',cableExitDepthMm:10,serviceAccessVerified:true}],powerEntryEdgeSeparatedFromSensitiveSignals:true,undersideHeightEnvelopeVerified:true,topsidePropClearanceVerified:true,vibrationRetentionVerified:true})

test('Board021 manifest preserves drone-stack intent and 2300mm2 cap',()=>{const b=manifest.boards[20];assert.equal(b.id,'021_DRONE_PERIPHERAL');assert.match(b.outline.family,/drone stack/);assert.equal(b.maximumAreaMm2,2300);assert.equal(contract.maximumAreaMm2,2300)})
test('current catalog clone fails area and flight-stack datum checks',()=>{const d=catalogDefinition(manifest.boards[20],20),r=validate({outline:d.outlinePoints,outlineClosed:true});assert.equal(r.areaMm2,3166.17);assert.equal(r.ok,false);assert.ok(r.errors.includes('drone-stack-outline-exceeds-maximum-area'));assert.ok(r.errors.includes('drone-stack-four-hole-pattern-required'));assert.ok(r.errors.includes('drone-stack-mounting-datum-unverified'))})
test('clipped square stack plate is purposeful and under area cap',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,2098);assert.equal(r.bounds.width,46);assert.equal(r.bounds.height,46)})
test('mounting holes require source-backed square symmetry and keepouts',()=>{const x=valid();x.mountingPatternPrimarySourceVerified=false;x.mountingHoles[0].x=10;x.mountingHoles[1].keepoutRadiusMm=1;const e=validate(x).errors;assert.ok(e.includes('drone-stack-mounting-datum-unverified'));assert.ok(e.includes('drone-stack-hole-pattern-not-square'));assert.ok(e.includes('drone-stack-hole-2-keepout-unverified'))})
test('connectors must occupy three serviceable cable edges',()=>{const x=valid();x.edgeConnectorGroups[2].edge='right';x.edgeConnectorGroups[1].cableExitDepthMm=4;const e=validate(x).errors;assert.ok(e.includes('drone-stack-connectors-not-distributed-across-edges'));assert.ok(e.includes('drone-stack-connector-group-2-access-obstructed'))})
test('center, vertical, vibration and power separation evidence fail closed',()=>{const x=valid();x.centerKeepout.widthMm=8;x.powerEntryEdgeSeparatedFromSensitiveSignals=false;x.undersideHeightEnvelopeVerified=false;x.vibrationRetentionVerified=false;const e=validate(x).errors;assert.ok(e.includes('drone-stack-center-keepout-unverified'));assert.ok(e.includes('drone-stack-power-signal-edge-separation-unverified'));assert.ok(e.includes('drone-stack-vertical-envelope-unverified'));assert.ok(e.includes('drone-stack-vibration-retention-unverified'))})
