import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{ETHERNET_GATEWAY_MECHANICAL_CONTRACT as contract,validateEthernetGatewayMechanicalGeometry as validate}from'../lib/phase2c/ethernet-gateway-mechanical-contract.mjs'

const dualNotchOutline=[[0,0],[48,0],[48,30],[34,30],[34,25],[28,25],[28,30],[20,30],[20,25],[14,25],[14,30],[0,30]]
const valid=()=>({outline:dualNotchOutline,outlineClosed:true,portNotches:[{centerXmm:17,widthMm:6,depthMm:5,edgeCutsVerified:true,connectorAligned:true,shellAndLatchClearanceVerified:true},{centerXmm:31,widthMm:6,depthMm:5,edgeCutsVerified:true,connectorAligned:true,shellAndLatchClearanceVerified:true}],notchesSymmetricAboutBoardCenter:true,placements:{ethernetPorts:[{minY:25,maxY:30},{minY:25,maxY:30}],portInterfaceBlocks:[{immediatelyBehindPort:true},{immediatelyBehindPort:true}],gatewayLogic:{minY:8,maxY:17},serviceAndPower:{minY:1,maxY:5}},cableExit:{independentPathsVerified:true,noLatchInterference:true},connectorLoadPath:{clearOfComponents:true,enclosureSupportVerified:true},mountingHoles:[{x:5,y:6,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inConnectorLoadPath:false},{x:43,y:6,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inConnectorLoadPath:false}]})

test('Board027 manifest preserves dual-port-notch intent and 1600mm2 cap',()=>{const board=manifest.boards[26];assert.equal(board.id,'027_ETHERNET_GATEWAY');assert.equal(board.outline.family,'dual-port notch-ethernet-gateway');assert.equal(board.maximumAreaMm2,1600);assert.equal(contract.maximumAreaMm2,1600)})
test('current catalog outline exceeds cap and lacks two functional port notches',()=>{const definition=catalogDefinition(manifest.boards[26],26),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2>1600);assert.ok(result.errors.includes('ethernet-gateway-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('dual-port-notch-count-invalid'))})
test('purposeful symmetric dual-notch gateway fits the area cap',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,1380);assert.equal(result.bounds.width,48);assert.equal(result.bounds.height,30)})
test('each port notch requires usable geometry and connector clearance',()=>{const x=valid();x.portNotches[0].depthMm=2;x.portNotches[1].shellAndLatchClearanceVerified=false;x.portNotches[1].centerXmm=25;const e=validate(x).errors;assert.ok(e.includes('port-notch-1-geometry-invalid'));assert.ok(e.includes('port-notch-2-connector-clearance-unverified'));assert.ok(e.includes('ethernet-port-spacing-insufficient'))})
test('ports, interface blocks, logic, service and power remain ordered',()=>{const x=valid();x.placements.ethernetPorts[0].minY=18;x.placements.portInterfaceBlocks[1].immediatelyBehindPort=false;x.placements.gatewayLogic.maxY=24;x.placements.serviceAndPower.maxY=10;const e=validate(x).errors;assert.ok(e.includes('ethernet-ports-not-in-notched-edge-bays'));assert.ok(e.includes('ethernet-port-interface-placement-unverified'));assert.ok(e.includes('gateway-logic-not-behind-port-interface-row'));assert.ok(e.includes('service-and-power-not-opposite-port-edge'))})
test('cable exits, connector loads and mounting fail closed on interference',()=>{const x=valid();x.cableExit.independentPathsVerified=false;x.connectorLoadPath.enclosureSupportVerified=false;x.mountingHoles[0].inConnectorLoadPath=true;x.mountingHoles[1].allLayersKeepout=false;const e=validate(x).errors;assert.ok(e.includes('dual-port-cable-exit-unverified'));assert.ok(e.includes('ethernet-connector-load-path-unverified'));assert.ok(e.includes('mounting-hole-1-interferes-connector-load-path'));assert.ok(e.includes('mounting-hole-2-keepout-unverified'))})
