import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {fpgaPeripheralProductionProposal,validateFpgaPeripheralProductionProposal} from '../lib/phase2c/templates/fpga-peripheral.mjs'
test('Board040 instrument shell cannot pass as FPGA platform',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[39],39));assert.equal(g.ok,false);for(const c of ['fpga-device-missing','fpga-configuration-memory-missing','fpga-high-speed-connector-missing','fpga-bank-decoupling-missing','fpga-clock-missing','fpga-bank-voltage-plan-missing','fpga-power-sequencing-missing','fpga-jtag-reset-missing','fpga-mezzanine-pin-map-missing','fpga-high-speed-channel-evidence-missing','fpga-pdn-evidence-missing','fpga-timing-analysis-missing','fpga-thermal-solution-missing'])assert.ok(g.errors.includes(c),c)})
test('Board040 reuses approved flash clock support and blocks package-specific platform',()=>{const p=fpgaPeripheralProductionProposal,g=validateFpgaPeripheralProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('fpga-peripheral-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_FPGA','P_BANK','J_HS_A','J_HS_B','P_LANE','P_CLK','P_PWR','U_SEQ','P_PDN','J_JTAG','P_BOOT','U_TEMP','P_THERM','P_TEST']);for(const r of ['U_CFG','Y_REF','C_DEC','FB_PLL'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board040 requires SI PI configuration timing thermal EMC and production evidence',()=>{for(const k of ['bankVccoVrefIoStandardsVerified','configurationFlashCompatibilityVerified','clockPhaseNoiseJitterVerified','railSequenceRampPowerGoodVerified','pdnTargetImpedanceVerified','channelImpedanceLossSkewEyeVerified','timingClosureConstraintsBitstreamVerified','thermalWorkloadHeatsinkVerified','productionBoundaryScanLoopbackBerVerified'])assert.ok(fpgaPeripheralProductionProposal.evidenceRequired.includes(k),k)})
test('Board040 bank and connector outline stays inside 3350 mm2',()=>{const p=fpgaPeripheralProductionProposal,g=validateFpgaPeripheralProductionProposal(p);assert.equal(g.areaMm2,3248);assert.ok(g.areaMm2<=3350);assert.equal(p.outline.purposefulFeatures.bankQuadrantCount,4);assert.equal(p.outline.purposefulFeatures.clockKeepoutRequired,true)})
