import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {hmiControllerProductionProposal,validateHmiControllerProductionProposal} from '../lib/phase2c/templates/hmi-controller.mjs'
test('Board038 USB instrument cannot pass as display HMI',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[37],37));assert.equal(g.ok,false);for(const c of ['hmi-display-interface-missing','hmi-display-power-backlight-missing','hmi-operator-controls-missing','hmi-control-protection-missing','hmi-application-controller-missing','hmi-ui-storage-missing','hmi-host-interface-missing','hmi-watchdog-recovery-missing','hmi-display-timing-evidence-missing','hmi-safe-state-evidence-missing','hmi-category-mapped-to-usb-instrument'])assert.ok(g.errors.includes(c),c)})
test('Board038 reuses approved support and blocks unresolved display assembly',()=>{const p=hmiControllerProductionProposal,g=validateHmiControllerProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('hmi-controller-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['DS1','U_DISP','J_PANEL','P_LEVEL','D_PANEL','U_BL','P_RAIL','U_TOUCH','J_HOST','J_DEBUG','U_WDOG','P_FASCIA','P_TEST']);for(const r of ['U_APP','U_ASSET','U_CFG','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board038 requires SI timing power thermal EMC recovery and display-test evidence',()=>{for(const k of ['pixelClockTimingBandwidthVerified','busImpedanceSkewSignalIntegrityVerified','levelTranslationUnpoweredStateVerified','panelEsdEmcVerified','railSequenceResetBackpowerVerified','backlightCurrentDimmingFaultVerified','hostProtocolHeartbeatRecoveryVerified','powerThermalSunlightVerified','productionPixelColorBacklightHostTestVerified'])assert.ok(hmiControllerProductionProposal.evidenceRequired.includes(k),k)})
test('Board038 display-window outline stays inside 2650 mm2',()=>{const p=hmiControllerProductionProposal,g=validateHmiControllerProductionProposal(p);assert.equal(g.areaMm2,2580);assert.ok(g.areaMm2<=2650);assert.equal(p.outline.purposefulFeatures.windowDatumCount,4);assert.equal(p.outline.purposefulFeatures.flexBendKeepoutRequired,true)})
