import test from'node:test';import assert from'node:assert/strict';import{industrialIoTemplate as t,validateIndustrialIoTemplate as validate,validateIndustrialIoProductionTopology as topologyGate}from'../lib/phase2c/templates/industrial-io.mjs'
import{approvedAssetFor}from'../lib/components/approved-production-assets.mjs'
test('Board006 binds the exact manifest envelope',()=>{assert.deepEqual(validate(t),{ok:true,errors:[]});assert.equal(t.id,'006_INDUSTRIAL_IO');assert.equal(t.outline.maximumAreaMm2,2650);assert.equal(t.outline.family,'din rail');assert.ok(t.acceptance.minimumFunctionalBlocks>=4)})
test('Board006 forbids mains and fails closed without galvanic isolation',()=>{const x=structuredClone(t);x.electrical.noMains=false;x.electrical.galvanicallyIsolated=false;assert.ok(validate(x).errors.includes('mains-input-forbidden'));assert.ok(validate(x).errors.includes('field-isolation-required'))})
test('Board006 enforces conservative isolation geometry',()=>{const x=structuredClone(t);x.electrical.minimumCreepageMm=3.9;x.electrical.minimumClearanceMm=3;assert.ok(validate(x).errors.includes('creepage-too-small'));assert.ok(validate(x).errors.includes('clearance-too-small'))})
test('Board006 cannot lose field protection or isolated power',()=>{for(const role of['FIELD_INPUT_FUSE','FIELD_TVS','ISOLATED_POWER']){const x=structuredClone(t);x.requirements=x.requirements.filter(p=>p.role!==role);assert.ok(validate(x).errors.includes(`missing-role:${role}`))}})
test('Board006 does not claim live sourcing without runtime proof',()=>{const x=structuredClone(t);x.sourcing.liveClaim=true;assert.ok(validate(x).errors.includes('false-live-claim'))})
test('Board006 exact MPNs have approved pin-to-pad assets',()=>{for(const p of t.requirements)assert.equal(approvedAssetFor(p.mpn,{requiredPinCount:p.pinCount})?.mpn,p.mpn,p.ref)})
test('Board006 production topology fails closed on the audited incomplete implementation',()=>{const result=topologyGate({isolatedConverter:{mpn:'RFM-0505S',isolationVdc:1000,pinMap:{1:'5V',2:'GND',3:'FIELD_GND',4:'NC'}},iso1212:{channels:[{},{}],noConnectPins:[]},isolationCorridor:{keepoutVerified:false,clearanceMm:0.2,creepageMm:0.2},stm32:{connectedPowerPins:['23','24']}});assert.equal(result.ok,false);for(const code of['isolated-converter-rating-below-system-gate','isolated-converter-pin-1-must-be-GND','isolated-converter-pin-4-must-be-FIELD_5V','iso1212-channel-1-rthr-unproven','iso1212-channel-2-cin-unproven','iso1212-sub-pin-3-must-be-nc','isolation-keepout-unverified','stm32-power-pin-48-unconnected'])assert.ok(result.errors.includes(code),code)})
test('Board006 topology gate accepts only explicit primary-source and geometry evidence',()=>{const verified={isolatedConverter:{mpn:'RFM-0505S',isolationVrms:2500,pinMap:{1:'GND',2:'5V',3:'FIELD_GND',4:'FIELD_5V'}},iso1212:{channels:[1,2].map(()=>({RTHR:{primarySourceVerified:true},RSENSE:{primarySourceVerified:true},CIN:{primarySourceVerified:true}})),noConnectPins:['3','12']},isolationCorridor:{keepoutVerified:true,clearanceMm:3.2,creepageMm:4},stm32:{connectedPowerPins:['1','8','9','23','24','35','36','47','48']}};assert.equal(topologyGate(verified).ok,true)})
