import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{INDUSTRIAL_SENSOR_MECHANICAL_CONTRACT as contract,validateIndustrialSensorMechanicalGeometry as validate}from'../lib/phase2c/industrial-sensor-mechanical-contract.mjs'

const probeOutline=[[0,0],[50,0],[50,13],[62,13],[64,15],[64,21],[62,23],[50,23],[50,36],[0,36]]
const valid=()=>({outline:probeOutline,outlineClosed:true,probeNeck:{projectionMm:14,usableLengthMm:12,widthMm:10,topShoulderMm:13,bottomShoulderMm:13,edgeCutsVerified:true,enclosureSealBoundaryVerified:true,insertionAndRemovalClearanceVerified:true},placements:{probe:{minX:52,maxX:63},analogFrontEnd:{minX:38,maxX:49},fieldConnector:{minX:1,maxX:6}},probeEnvironment:{sensingSurfaceExposedAsRequired:true,noTallPartsBlockMediumFlow:true,cleanableClearanceVerified:true,guardAndCopperBoundaryVerified:true,noMountMetalInSensingZone:true},separation:{probeToHeatSourceMm:12,noHeatSpreadingCopperIntoNeck:true,fieldCableStrainClearOfProbe:true},mountingHoles:[{x:7,y:7,diameterMm:3.2,copperKeepoutRadiusMm:3.2,allLayersKeepout:true,ruggedStandoffClearanceVerified:true,onProbeNeck:false},{x:7,y:29,diameterMm:3.2,copperKeepoutRadiusMm:3.2,allLayersKeepout:true,ruggedStandoffClearanceVerified:true,onProbeNeck:false}]})

test('Board031 manifest preserves probe-neck intent and 3000mm2 cap',()=>{const board=manifest.boards[30];assert.equal(board.id,'031_INDUSTRIAL_SENSOR');assert.equal(board.outline.family,'probe neck-industrial-sensor');assert.equal(board.maximumAreaMm2,3000);assert.equal(contract.maximumAreaMm2,3000)})
test('current catalog outline is under cap but lacks functional probe-neck evidence',()=>{const definition=catalogDefinition(manifest.boards[30],30),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2<3000);assert.ok(result.errors.includes('purposeful-probe-neck-unverified'));assert.ok(result.errors.includes('sensing-probe-not-on-neck'))})
test('purposeful narrow-neck industrial sensor fits the maximum area',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,1936);assert.equal(result.bounds.width,64);assert.equal(result.bounds.height,36)})
test('probe neck proportions and enclosure seal interface fail closed',()=>{const x=valid();x.probeNeck.projectionMm=5;x.probeNeck.widthMm=18;x.probeNeck.enclosureSealBoundaryVerified=false;const e=validate(x).errors;assert.ok(e.includes('purposeful-probe-neck-unverified'));assert.ok(e.includes('probe-neck-enclosure-interface-unverified'))})
test('probe, front end and field connector retain ordered mechanical placement',()=>{const x=valid();x.placements.probe.minX=40;x.placements.analogFrontEnd.minX=25;x.placements.fieldConnector.maxX=15;x.separation.fieldCableStrainClearOfProbe=false;const e=validate(x).errors;assert.ok(e.includes('sensing-probe-not-on-neck'));assert.ok(e.includes('analog-front-end-not-at-probe-root'));assert.ok(e.includes('field-connector-not-opposite-probe-neck'));assert.ok(e.includes('field-cable-strain-path-unverified'))})
test('sensing environment, thermal isolation and rugged mounting fail closed',()=>{const x=valid();x.probeEnvironment.noTallPartsBlockMediumFlow=false;x.probeEnvironment.noMountMetalInSensingZone=false;x.separation.probeToHeatSourceMm=4;x.mountingHoles[0].onProbeNeck=true;x.mountingHoles[1].ruggedStandoffClearanceVerified=false;const e=validate(x).errors;assert.ok(e.includes('probe-sensing-environment-unverified'));assert.ok(e.includes('probe-electromechanical-guard-unverified'));assert.ok(e.includes('probe-thermal-isolation-insufficient'));assert.ok(e.includes('mounting-hole-1-intrudes-probe-neck'));assert.ok(e.includes('mounting-hole-2-rugged-keepout-unverified'))})
