import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {industrialSensorProductionProposal,validateIndustrialSensorProductionProposal} from '../lib/phase2c/templates/industrial-sensor.mjs'
test('Board031 CAN controller shell cannot pass as rugged analog sensing',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[30],30));assert.equal(g.ok,false);for(const c of ['industrial-sensor-probe-interface-missing','industrial-sensor-input-protection-missing','industrial-sensor-excitation-missing','industrial-sensor-analog-front-end-missing','industrial-sensor-filter-missing','industrial-sensor-adc-reference-missing','industrial-sensor-field-power-protection-missing','industrial-sensor-calibration-evidence-missing','industrial-sensor-emc-evidence-missing','industrial-sensor-temperature-evidence-missing','industrial-sensor-category-mapped-to-can-controller'])assert.ok(g.errors.includes(c),c)})
test('Board031 reuses approved field assets and blocks unresolved measurement chain',()=>{const p=industrialSensorProductionProposal,g=validateIndustrialSensorProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('industrial-sensor-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['S_PROBE','U_EXC','P_IN','U_AFE','P_FILT','U_ADC','U_REF','J_PROBE','J_FIELD','P_GND','U_TEMP','P_TEST']);for(const r of ['U_CTRL','U_CAN','R_CAN','D_CAN','F_IN','D_IN','U_PWR','U_CAL','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board031 requires accuracy drift noise surge environment and calibration evidence',()=>{for(const k of ['excitationAccuracySelfHeatingVerified','inputProtectionLeakageRecoveryVerified','afeGainCommonModeNoiseVerified','adcReferenceLinearityDriftVerified','worstCaseAccuracyErrorBudgetVerified','shieldGuardGroundingVerified','surgeEftEsdMiswireVerified','ingressChemicalUvVibrationVerified','productionRangeTemperatureNoiseCalibrationVerified'])assert.ok(industrialSensorProductionProposal.evidenceRequired.includes(k),k)})
test('Board031 guarded probe outline stays inside 3000 mm2',()=>{const p=industrialSensorProductionProposal,g=validateIndustrialSensorProductionProposal(p);assert.equal(g.areaMm2,2928);assert.ok(g.areaMm2<=3000);assert.equal(p.outline.purposefulFeatures.analogGuardRingRequired,true);assert.equal(p.outline.purposefulFeatures.chassisGuardMoatRequired,true)})
