import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{LED_MATRIX_CONTROLLER_MECHANICAL_CONTRACT as contract,validateLedMatrixControllerMechanicalGeometry as validate}from'../lib/phase2c/led-matrix-controller-mechanical-contract.mjs'

const panelOutline=[[5,0],[55,0],[60,5],[60,12],[56,12],[56,26],[60,26],[60,33],[55,38],[5,38],[0,33],[0,26],[4,26],[4,12],[0,12],[0,5]]
const valid=()=>({outline:panelOutline,outlineClosed:true,panelDatum:{originRecorded:true,rotationRecorded:true,enclosureAndDisplayAlignmentVerified:true,patternWidthMm:48,patternHeightMm:26,holesSymmetricAndRegistered:true},sideReliefs:[{depthMm:4,spanMm:14,edgeCutsVerified:true},{depthMm:4,spanMm:14,edgeCutsVerified:true}],reliefsSymmetricAboutPanelCenter:true,panelMountingHoles:[{x:6,y:6,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,fastenerAndStandoffClearanceVerified:true},{x:54,y:6,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,fastenerAndStandoffClearanceVerified:true},{x:6,y:32,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,fastenerAndStandoffClearanceVerified:true},{x:54,y:32,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,fastenerAndStandoffClearanceVerified:true}],placements:{panelConnectors:[{minY:30,maxY:37},{minY:30,maxY:37}],powerInput:{minX:1,maxX:6},controlLogic:{minX:17,maxX:40}},cableExit:{clearOfPanelAndFasteners:true,connectorServiceLoopsVerified:true},thermalAndCurrent:{highCurrentPathClearOfMounts:true,heatSourceToPanelClearanceVerified:true,enclosureAirflowVerified:true}})

test('Board030 manifest preserves panel-matched intent and 2650mm2 cap',()=>{const board=manifest.boards[29];assert.equal(board.id,'030_LED_MATRIX_CONTROLLER');assert.equal(board.outline.family,'panel matched-led-matrix-controller');assert.equal(board.maximumAreaMm2,2650);assert.equal(contract.maximumAreaMm2,2650)})
test('current catalog outline exceeds cap and lacks panel registration evidence',()=>{const definition=catalogDefinition(manifest.boards[29],29),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2>2650);assert.ok(result.errors.includes('led-matrix-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('matrix-panel-datum-unverified'))})
test('purposeful panel-matched matrix controller fits the area cap',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,2118);assert.equal(result.bounds.width,60);assert.equal(result.bounds.height,38)})
test('paired side reliefs and registered four-hole panel pattern fail closed',()=>{const x=valid();x.sideReliefs[0].depthMm=2;x.reliefsSymmetricAboutPanelCenter=false;x.panelDatum.holesSymmetricAndRegistered=false;x.panelMountingHoles.pop();const e=validate(x).errors;assert.ok(e.includes('panel-side-reliefs-unverified'));assert.ok(e.includes('panel-side-relief-symmetry-unverified'));assert.ok(e.includes('panel-mounting-pattern-count-invalid'));assert.ok(e.includes('panel-mounting-pattern-unverified'))})
test('panel connectors, service power and logic preserve ordered access',()=>{const x=valid();x.placements.panelConnectors[0].minY=20;x.placements.powerInput.maxX=14;x.placements.controlLogic.maxX=50;x.cableExit.clearOfPanelAndFasteners=false;const e=validate(x).errors;assert.ok(e.includes('matrix-connectors-not-on-panel-edge'));assert.ok(e.includes('matrix-power-input-not-on-service-edge'));assert.ok(e.includes('matrix-control-logic-outside-central-envelope'));assert.ok(e.includes('matrix-cable-exit-unverified'))})
test('high-current paths, heat sources and airflow avoid the panel mounting system',()=>{const x=valid();x.thermalAndCurrent.highCurrentPathClearOfMounts=false;x.thermalAndCurrent.heatSourceToPanelClearanceVerified=false;x.panelMountingHoles[0].allLayersKeepout=false;const e=validate(x).errors;assert.ok(e.includes('matrix-high-current-thermal-layout-unverified'));assert.ok(e.includes('panel-mount-1-keepout-unverified'))})
