import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {linuxCarrierProductionProposal,validateLinuxCarrierProductionProposal} from '../lib/phase2c/templates/linux-carrier.mjs'
test('Board039 PD sink cannot pass as compute-module carrier',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[38],38));assert.equal(g.ok,false);for(const c of ['compute-module-connector-missing','carrier-power-tree-missing','carrier-storage-interface-missing','carrier-high-speed-io-missing','carrier-module-pin-map-evidence-missing','carrier-reset-power-good-missing','carrier-boot-recovery-missing','carrier-high-speed-protection-missing','carrier-signal-integrity-evidence-missing','carrier-backpower-evidence-missing','carrier-thermal-solution-missing','carrier-manufacturing-bringup-missing','linux-carrier-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board039 reuses approved protection/config and blocks module-specific hardware',()=>{const p=linuxCarrierProductionProposal,g=validateLinuxCarrierProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('linux-carrier-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['MOD1','J_MOD_A','J_MOD_B','P_PINMAP','P_PWR','J_STORAGE','J_NET','J_USB','J_DISP','P_HS','J_BOOT','J_DEBUG','P_THERM','P_MECH','P_TEST']);for(const r of ['F_IN','D_IN','U_CFG','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board039 requires SI PI thermal EMC recovery and bringup evidence',()=>{for(const k of ['modulePinMapReservedPinsVerified','railSequenceResetPowerGoodVerified','pdnTargetImpedanceVerified','stackupImpedanceLossSkewVerified','highSpeedViaCouplingReturnVerified','portProtectionBackpowerVerified','bootRecoveryDebugVerified','moduleKeepoutHeightToleranceVerified','heatsinkWorkloadThrottlingVerified','productionBringupHighSpeedThermalVerified'])assert.ok(linuxCarrierProductionProposal.evidenceRequired.includes(k),k)})
test('Board039 module-matched outline stays inside 3000 mm2',()=>{const p=linuxCarrierProductionProposal,g=validateLinuxCarrierProductionProposal(p);assert.equal(g.areaMm2,2936);assert.ok(g.areaMm2<=3000);assert.equal(p.outline.purposefulFeatures.moduleMountHoleCount,4);assert.equal(p.outline.purposefulFeatures.heatsinkContactZoneRequired,true)})
