import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{LORA_NODE_MECHANICAL_CONTRACT as contract,validateLoraNodeMechanicalGeometry as validate}from'../lib/phase2c/lora-node-mechanical-contract.mjs'

const tailOutline=[[0,0],[48,0],[48,9],[65,9],[68,12],[68,18],[65,21],[48,21],[48,30],[0,30],[0,26],[-3,23],[-3,7],[0,4]]
const valid=()=>({outline:tailOutline,outlineClosed:true,antennaTail:{projectionMm:20,usableLengthMm:18,widthMm:12,neckWidthMm:12,edgeCutsVerified:true},antennaKeepout:{tailCoverageVerified:true,allCopperLayers:true,noPlanesTracksOrVias:true,noComponentsExceptFeedAndMatching:true,enclosureClearanceVerified:true,noMetalOrBatteryInFieldRegion:true},placements:{antenna:{minX:51,maxX:67},radio:{minX:36,maxX:47},serviceAndPower:{minX:1,maxX:6}},rfFeed:{adjacentRadioMatchingAndAntenna:true,staysOutsideUnrelatedCircuitry:true},separation:{antennaToNoisyCircuitMm:14,cableAndEnclosureClearOfAntennaField:true},mountingHoles:[{x:8,y:6,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inAntennaTail:false},{x:8,y:24,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inAntennaTail:false}]})

test('Board024 manifest preserves antenna-tail intent and 3350mm2 cap',()=>{const board=manifest.boards[23];assert.equal(board.id,'024_LORA_NODE');assert.equal(board.outline.family,'antenna tail-lora-node');assert.equal(board.maximumAreaMm2,3350);assert.equal(contract.maximumAreaMm2,3350)})
test('current catalog outline is not accepted without functional antenna-tail evidence',()=>{const definition=catalogDefinition(manifest.boards[23],23),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2<3350);assert.ok(result.errors.includes('purposeful-antenna-tail-unverified'));assert.ok(result.errors.includes('lora-antenna-all-layer-keepout-unverified'))})
test('purposeful narrow-tail LoRa envelope fits the maximum area',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,1728);assert.equal(result.bounds.width,71);assert.equal(result.bounds.height,30)})
test('tail proportions and all-layer antenna keepout fail closed',()=>{const x=valid();x.antennaTail.projectionMm=8;x.antennaTail.neckWidthMm=20;x.antennaKeepout.noPlanesTracksOrVias=false;const e=validate(x).errors;assert.ok(e.includes('purposeful-antenna-tail-unverified'));assert.ok(e.includes('lora-antenna-all-layer-keepout-unverified'))})
test('radio feed and noisy circuitry remain behind the antenna field',()=>{const x=valid();x.placements.radio.minX=20;x.rfFeed.adjacentRadioMatchingAndAntenna=false;x.separation.antennaToNoisyCircuitMm=5;const e=validate(x).errors;assert.ok(e.includes('lora-radio-outside-placement-envelope'));assert.ok(e.includes('lora-rf-feed-placement-unverified'));assert.ok(e.includes('lora-antenna-noisy-circuit-separation-insufficient'))})
test('mounting, cables, service and power cannot occupy the antenna tail',()=>{const x=valid();x.mountingHoles[0].inAntennaTail=true;x.mountingHoles[1].allLayersKeepout=false;x.placements.serviceAndPower.maxX=20;x.separation.cableAndEnclosureClearOfAntennaField=false;const e=validate(x).errors;assert.ok(e.includes('mounting-hole-1-intrudes-antenna-tail'));assert.ok(e.includes('mounting-hole-2-keepout-unverified'));assert.ok(e.includes('service-and-power-not-opposite-antenna-tail'));assert.ok(e.includes('lora-cable-and-enclosure-clearance-unverified'))})
