import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {motorEncoderProductionProposal,validateMotorEncoderProductionProposal} from '../lib/phase2c/templates/motor-encoder.mjs'
test('Board044 wireless sensor shell cannot pass as motor encoder',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[43],43));assert.equal(g.ok,false);for(const c of ['encoder-sensing-element-missing','encoder-target-missing','encoder-signal-conditioning-missing','encoder-output-interface-missing','encoder-connector-missing','encoder-input-output-protection-missing','encoder-power-filtering-missing','encoder-index-home-missing','encoder-alignment-evidence-missing','encoder-resolution-accuracy-evidence-missing','encoder-speed-timing-evidence-missing','encoder-calibration-production-test-missing','encoder-category-mapped-to-generic-wireless-sensor'])assert.ok(g.errors.includes(c),c)})
test('Board044 reuses approved control calibration power and blocks encoder-specific hardware',()=>{const p=motorEncoderProductionProposal,g=validateMotorEncoderProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('motor-encoder-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_SENSE','T_TARGET','P_COND','U_OUT','J_ENC','D_ENC','P_INDEX','U_TEMP','P_DIAG','P_TEST']);for(const r of ['U_CTRL','U_CAL','U_PWR','FB_PWR','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board044 requires alignment accuracy speed timing EMC diagnostics and motion-test evidence',()=>{for(const k of ['shaftGapRunoutConcentricityVerified','resolutionQuantizationVerified','angularAccuracyLinearityVerified','maximumSpeedEdgeRateVerified','latencyJitterVerified','quietRailMotorTransientVerified','fieldSignalDiagnosticsVerified','motorPwmEmcEftEsdVerified','productionRotationEndOfLineVerified'])assert.ok(motorEncoderProductionProposal.evidenceRequired.includes(k),k)})
test('Board044 circular encoder outline stays inside 1950 mm2',()=>{const p=motorEncoderProductionProposal,g=validateMotorEncoderProductionProposal(p);assert.equal(g.areaMm2,1854);assert.ok(g.areaMm2<=1950);assert.deepEqual(p.outline.purposefulFeatures.shaftCenter,[22,22]);assert.equal(p.outline.purposefulFeatures.radialAlignmentDatumRequired,true)})
