import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {motorDriverProductionProposal,validateMotorDriverProductionProposal} from '../lib/phase2c/templates/motor-driver.mjs'
test('Board014 generic PD sink cannot pass as a brushed motor driver',()=>{const d=catalogDefinition(manifest.boards[13],13),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);for(const c of ['brushed-motor-h-bridge-missing','brushed-motor-power-switches-missing','brushed-motor-connector-missing','brushed-motor-current-sense-missing','brushed-motor-power-entry-protection-missing','brushed-motor-transient-clamp-missing','brushed-motor-gate-control-missing','brushed-motor-bulk-decoupling-missing'])assert.ok(g.errors.includes(c),c)})
test('Board014 reuses exact protection candidates but blocks envelope-dependent power parts',()=>{const p=motorDriverProductionProposal,g=validateMotorDriverProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('brushed-motor-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U1','J_MOTOR','R_IPROPI','J_PWR','R_GATE','P_REGEN','P_EMI']);for(const r of ['F1','Q_REV','D_TVS','C_BULK','C_HF'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board014 completeness gate rejects absent motor supply and regeneration envelopes',()=>{const g=validateMotorDriverProductionProposal(motorDriverProductionProposal);for(const code of ['brushed-motor-electrical-envelope-undeclared','brushed-motor-supply-envelope-undeclared','brushed-motor-regeneration-envelope-undeclared'])assert.ok(g.errors.includes(code),code)})
test('Board014 requires thermal current reverse and regeneration evidence',()=>{for(const k of ['continuousStartupStallCurrentVerified','currentSenseLimitVerified','reversePolarityVerified','regenerationHandled','thermalCopperViaVerified','productionStallFaultTestVerified'])assert.ok(motorDriverProductionProposal.evidenceRequired.includes(k),k)})
test('Board014 thermal-wing outline stays inside 2650 mm2',()=>{const g=validateMotorDriverProductionProposal(motorDriverProductionProposal);assert.equal(g.areaMm2,2576);assert.ok(g.areaMm2<=2650);assert.equal(motorDriverProductionProposal.outline.purposefulFeatures.thermalWingCount,2);assert.equal(motorDriverProductionProposal.outline.purposefulFeatures.thermalViaFieldRequired,true)})
