import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{MOTOR_DRIVER_MECHANICAL_CONTRACT as contract,validateMotorDriverMechanicalGeometry as validate}from'../lib/phase2c/motor-driver-mechanical-contract.mjs'

const outline=[[0,0],[34,0],[34,-4],[50,-4],[50,0],[56,0],[56,36],[50,36],[50,40],[34,40],[34,36],[0,36]]
const wing=(x,y)=>({projectionMm:4,spanMm:16,fastener:{x,y,diameterMm:3.2,keepoutRadiusMm:3.2,allLayersKeepout:true},copperAreaMm2:40,thermalViaCount:8,allCopperLayersTied:true})
const valid=()=>({outline,outlineClosed:true,body:{widthMm:56,heightMm:36},thermalWings:[wing(42,-2),wing(42,38)],placements:{powerInput:{minX:1,maxX:5},logic:{minX:8,maxX:25},gateDrive:{minX:27,maxX:36},powerStage:{minX:36,maxX:49},motorOutput:{minX:51,maxX:55}},powerStageToWingRootMaximumMm:3,separation:{logicToSwitchNodeMm:3.2,switchNodeAllLayersKeepoutVerified:true},highCurrentEdgeClearanceVerified:true,thermalModelPrimarySourceVerified:true})

test('Board014 manifest preserves thermal-wing intent and 2650mm2 cap',()=>{const board=manifest.boards[13];assert.equal(board.id,'014_MOTOR_DRIVER');assert.match(board.outline.family,/thermal wings/);assert.equal(board.maximumAreaMm2,2650);assert.equal(contract.maximumAreaMm2,2650)})
test('current expanded octagon fails area and functional-wing checks',()=>{const d=catalogDefinition(manifest.boards[13],13),r=validate({outline:d.outlinePoints,outlineClosed:true,body:{widthMm:58,heightMm:38},thermalWings:[]});assert.equal(r.ok,false);assert.equal(r.areaMm2,2962.25);assert.ok(r.errors.includes('motor-outline-exceeds-maximum-area'));assert.ok(r.errors.includes('two-thermal-wings-required'))})
test('purposeful dual thermal-wing envelope stays under maximum area',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,2144);assert.equal(r.bounds.width,56);assert.equal(r.bounds.height,44)})
test('thermal wings require fasteners, keepouts, copper and via spreading',()=>{const x=valid();delete x.thermalWings[0].fastener;x.thermalWings[1].thermalViaCount=2;const e=validate(x).errors;assert.ok(e.includes('thermal-wing-1-fastener-missing'));assert.ok(e.includes('thermal-wing-1-fastener-keepout-unverified'));assert.ok(e.includes('thermal-wing-2-heat-spreading-unverified'))})
test('motor power chain stays ordered from left input to right output',()=>{const x=valid();x.placements.powerInput.maxX=9;x.placements.powerStage.minX=20;x.placements.motorOutput.minX=45;const e=validate(x).errors;assert.ok(e.includes('motor-power-input-not-on-left-edge'));assert.ok(e.includes('power-stage-outside-placement-envelope'));assert.ok(e.includes('motor-output-not-on-right-edge'))})
test('heat source proximity and switch-node separation fail closed',()=>{const x=valid();x.powerStageToWingRootMaximumMm=7;x.separation.logicToSwitchNodeMm=2;x.separation.switchNodeAllLayersKeepoutVerified=false;x.thermalModelPrimarySourceVerified=false;const e=validate(x).errors;assert.ok(e.includes('power-stage-too-far-from-thermal-wing-root'));assert.ok(e.includes('logic-to-switch-node-clearance-insufficient'));assert.ok(e.includes('switch-node-keepout-unverified'));assert.ok(e.includes('power-stage-thermal-evidence-missing'))})
