import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {oscilloscopeFrontendProductionProposal,validateOscilloscopeFrontendProductionProposal} from '../lib/phase2c/templates/oscilloscope-frontend.mjs'
test('Board042 generic USB instrument cannot pass as oscilloscope front end',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[41],41));assert.equal(g.ok,false);for(const c of ['oscilloscope-input-connector-missing','oscilloscope-attenuator-missing','oscilloscope-overload-protection-missing','oscilloscope-coupling-termination-missing','oscilloscope-front-end-amplifier-missing','oscilloscope-antialias-filter-missing','oscilloscope-adc-missing','oscilloscope-reference-clock-missing','oscilloscope-trigger-pickoff-missing','oscilloscope-shield-grounding-missing','oscilloscope-bandwidth-linearity-evidence-missing','oscilloscope-calibration-overload-evidence-missing','oscilloscope-category-mapped-to-generic-usb-instrument'])assert.ok(g.errors.includes(c),c)})
test('Board042 reuses approved digital assets and blocks entire calibrated analog chain',()=>{const p=oscilloscopeFrontendProductionProposal,g=validateOscilloscopeFrontendProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('oscilloscope-frontend-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['J_CH1','P_ATT','P_PROTECT','P_COUPLE','U_AFE','P_FILTER','U_ADC','U_REF','Y_SAMPLE','P_TRIG','P_MEM','P_PWR','P_GND','P_TEST']);for(const r of ['U_CTRL','U_MEM','U_CAL','J_USB','D_USB','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board042 requires bandwidth noise linearity timing overload EMC and calibration evidence',()=>{for(const k of ['attenuatorRatioCompensationVerified','overloadSurvivalRecoveryVerified','afeGainNoiseLinearityVerified','antialiasFlatnessRejectionVerified','adcEnobRateVerified','sampleClockApertureJitterVerified','triggerLevelLatencyVerified','powerRailNoiseThermalVerified','esdEmcVerified','productionAmplitudeFrequencyTimingCalibrationVerified'])assert.ok(oscilloscopeFrontendProductionProposal.evidenceRequired.includes(k),k)})
test('Board042 BNC probe outline stays inside 1250 mm2',()=>{const p=oscilloscopeFrontendProductionProposal,g=validateOscilloscopeFrontendProductionProposal(p);assert.equal(g.areaMm2,1240);assert.ok(g.areaMm2<=1250);assert.equal(p.outline.purposefulFeatures.bncProbeWing.channelCount,1);assert.equal(p.outline.purposefulFeatures.guardMoatRequired,true)})
