import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {powerDistributionProductionProposal,validatePowerDistributionProductionProposal} from '../lib/phase2c/templates/power-distribution.mjs'
test('Board018 generic PD sink cannot pass as fused multi-rail distribution',()=>{const d=catalogDefinition(manifest.boards[17],17),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);for(const c of ['power-distribution-branch-fuses-missing','power-distribution-output-terminals-missing','power-distribution-bus-capacity-evidence-missing','power-distribution-branch-rating-evidence-missing','power-distribution-test-or-indication-missing','power-distribution-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board018 counts three independent branches and fails closed on exact branch hardware',()=>{const p=powerDistributionProductionProposal,g=validatePowerDistributionProductionProposal(p);assert.equal(p.branchCount,3);assert.equal(p.bom.find(x=>x.ref==='F_BRANCH').quantity,3);assert.equal(p.bom.find(x=>x.ref==='J_BRANCH').quantity,3);assert.equal(g.ok,false);assert.ok(g.errors.includes('power-distribution-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['J_IN','J_BRANCH','TP_LED','U_MON','P_BUS','P_BRANCH'])})
test('Board018 completeness gate rejects absent source branch coordination and thermal envelopes',()=>{const g=validatePowerDistributionProductionProposal(powerDistributionProductionProposal);for(const code of ['power-distribution-source-envelope-undeclared','power-distribution-branch-envelopes-undeclared','power-distribution-coordination-envelope-undeclared','power-distribution-thermal-envelope-undeclared'])assert.ok(g.errors.includes(code),code)})
test('Board018 requires aggregate bus branch fuse rating indication and thermal evidence',()=>{for(const k of ['aggregateBusCapacityVerified','independentBranchFusesVerified','fuseInterruptCoordinationVerified','branchTerminalRatingsVerified','testIndicationVerified','busBranchCopperThermalVerified','productionBranchFaultTestVerified'])assert.ok(powerDistributionProductionProposal.evidenceRequired.includes(k),k)})
test('Board018 mounting-ear outline fits within 1250 mm2',()=>{const g=validatePowerDistributionProductionProposal(powerDistributionProductionProposal);assert.equal(g.areaMm2,1200);assert.ok(g.areaMm2<=1250);assert.equal(powerDistributionProductionProposal.outline.purposefulFeatures.mountingEarCount,2);assert.equal(powerDistributionProductionProposal.outline.purposefulFeatures.fuseServiceAccessRequired,true)})
