import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{POWER_DISTRIBUTION_MECHANICAL_CONTRACT as contract,validatePowerDistributionMechanicalGeometry as validate}from'../lib/phase2c/power-distribution-mechanical-contract.mjs'

const outline=[[0,0],[42,0],[42,8],[46,8],[46,16],[42,16],[42,24],[0,24],[0,16],[-4,16],[-4,8],[0,8]],centers=[3,9,15,21]
const ear=(x)=>({projectionMm:4,lengthMm:8,hole:{x,y:12,diameterMm:3.2,keepoutRadiusMm:3.2,allLayersKeepout:true}})
const valid=()=>({outline,outlineClosed:true,body:{widthMm:42,heightMm:24},mountingEars:[ear(-2),ear(44)],inputTerminal:{minX:1,maxX:5},branchFuses:centers.map(centerY=>({centerY,minX:20,maxX:26,serviceGapMm:2})),outputTerminals:centers.map((centerY,i)=>({branch:i+1,centerY,minX:38,maxX:42})),powerTrunk:{minX:8,maxX:16,currentCapacityVerified:true,allCopperLayersTied:true},branchCurrentCapacityVerified:true,edgeCopperClearanceVerified:true,faultThermalSpacingVerified:true})

test('Board018 manifest preserves mounting-ear power distribution and 1250mm2 cap',()=>{const b=manifest.boards[17];assert.equal(b.id,'018_POWER_DISTRIBUTION');assert.match(b.outline.family,/mounting ears/);assert.equal(b.maximumAreaMm2,1250);assert.equal(contract.maximumAreaMm2,1250)})
test('current PD-sink octagon fails area and functional-ear checks',()=>{const d=catalogDefinition(manifest.boards[17],17),r=validate({outline:d.outlinePoints,outlineClosed:true,body:{widthMm:58,heightMm:38}});assert.equal(r.areaMm2,3174.25);assert.equal(r.ok,false);assert.ok(r.errors.includes('power-distribution-outline-exceeds-maximum-area'));assert.ok(r.errors.includes('power-distribution-mounting-ears-missing'))})
test('compact four-branch distribution with real ears stays under cap',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,1072);assert.equal(r.bounds.width,50);assert.equal(r.bounds.height,24)})
test('mounting ears require holes and all-layer copper keepouts',()=>{const x=valid();delete x.mountingEars[0].hole;x.mountingEars[1].hole.keepoutRadiusMm=2;const e=validate(x).errors;assert.ok(e.includes('power-distribution-ear-1-hole-missing'));assert.ok(e.includes('power-distribution-ear-1-keepout-unverified'));assert.ok(e.includes('power-distribution-ear-2-keepout-unverified'))})
test('fuses and outputs are one-to-one, uniformly spaced and serviceable',()=>{const x=valid();x.outputTerminals.pop();x.branchFuses[2].centerY+=2;x.branchFuses[1].serviceGapMm=.5;const e=validate(x).errors;assert.ok(e.includes('power-distribution-fuse-output-count-mismatch'));assert.ok(e.includes('power-distribution-fuse-2-service-gap-insufficient'));assert.ok(e.includes('power-distribution-branch-pitch-invalid'));assert.ok(e.includes('power-distribution-output-4-not-on-service-edge'))})
test('power trunk, branch capacity and fault spacing fail closed',()=>{const x=valid();x.powerTrunk.maxX=25;x.powerTrunk.currentCapacityVerified=false;x.branchCurrentCapacityVerified=false;x.edgeCopperClearanceVerified=false;x.faultThermalSpacingVerified=false;const e=validate(x).errors;assert.ok(e.includes('power-distribution-trunk-unverified'));assert.ok(e.includes('power-distribution-branch-capacity-unverified'));assert.ok(e.includes('power-distribution-edge-clearance-unverified'));assert.ok(e.includes('power-distribution-fault-thermal-spacing-unverified'))})
