import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {powerMonitorProductionProposal,validatePowerMonitorProductionProposal} from '../lib/phase2c/templates/power-monitor.mjs'
test('Board045 PD sink cannot pass as multi-rail telemetry',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[44],44));assert.equal(g.ok,false);for(const c of ['power-monitor-rail-connectors-missing','power-monitor-current-sense-elements-missing','power-monitor-kelvin-sense-missing','power-monitor-multichannel-converter-missing','power-monitor-voltage-divider-protection-missing','power-monitor-common-mode-evidence-missing','power-monitor-isolation-grounding-missing','power-monitor-telemetry-interface-missing','power-monitor-rail-protection-missing','power-monitor-calibration-storage-missing','power-monitor-accuracy-thermal-evidence-missing','power-monitor-production-test-missing','power-monitor-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board045 reuses approved telemetry assets and blocks two exact rail chains',()=>{const p=powerMonitorProductionProposal,g=validatePowerMonitorProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('power-monitor-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['J_R1_IN','J_R1_OUT','R_SH1','U_MON1','J_R2_IN','J_R2_OUT','R_SH2','U_MON2','P_SENSE','P_VDIV','P_ISO','P_RAIL','U_TEMP','J_HOST','P_TEST']);for(const r of ['U_CTRL','U_CAL','U_LOG','U_PWR','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board045 requires common-mode fault energy uncertainty thermal and calibration evidence',()=>{for(const k of ['shuntContinuousPulseFaultEnergyVerified','kelvinGeometryVerified','monitorCommonModeRangeVerified','senseProtectionSettlingVerified','dividerRatioPulseDriftVerified','isolationGroundDomainVerified','perRailUncertaintyBudgetVerified','busbarAmpacityTemperatureRiseVerified','fuseFaultCoordinationVerified','productionTwoRailKnownLoadFaultTestVerified'])assert.ok(powerMonitorProductionProposal.evidenceRequired.includes(k),k)})
test('Board045 dual busbar-notch outline stays inside 2300 mm2',()=>{const p=powerMonitorProductionProposal,g=validatePowerMonitorProductionProposal(p);assert.equal(g.areaMm2,2008);assert.ok(g.areaMm2<=2300);assert.equal(p.outline.purposefulFeatures.busbarNotchTop.depthMm,6);assert.equal(p.outline.purposefulFeatures.kelvinRouteKeepoutRequired,true)})
