import test from 'node:test';import assert from 'node:assert/strict';import {createProductionPartResolver} from '../lib/components/production-part-resolver.mjs'
import {approvedAssetFor} from '../lib/components/approved-production-assets.mjs'
test('production resolver ranks exact live preferred family candidates deterministically',async()=>{const calls=[];const provider={id:'digikey',lookupExact:async mpn=>{calls.push(mpn);return{live:true,exact:true,stockStatus:mpn.includes('MCP')?'IN_STOCK':'OUT_OF_STOCK',quantityAvailable:mpn.includes('MCP')?50:0,lifecycle:'Active',checkedAt:'now'}}};const resolve=createProductionPartResolver({providers:[provider]});const result=await resolve({requirement:{},family:'REGULATOR'});assert.equal(result.mpn,'MCP1700T-3302E/TT');assert.equal(calls.length,2)})
test('production resolver cache is bounded by TTL',async()=>{let calls=0,time=0;const provider={id:'digikey',lookupExact:async()=>{calls++;return{live:true,exact:true,stockStatus:'IN_STOCK',quantityAvailable:1,lifecycle:'Active',checkedAt:'now'}}};const resolve=createProductionPartResolver({providers:[provider],ttlMs:10,now:()=>time});await resolve({family:'RES_5K1_0603'});await resolve({family:'RES_5K1_0603'});assert.equal(calls,2);time=11;await resolve({family:'RES_5K1_0603'});assert.equal(calls,4)})
test('production resolver retries transient failure then succeeds',async()=>{let calls=0;const resolve=createProductionPartResolver({providers:[{id:'mouser',lookupExact:async()=>{if(++calls===1)throw Object.assign(new Error('temporary'),{code:'HTTP_503'});return{live:true,exact:true,stockStatus:'IN_STOCK',quantityAvailable:2,lifecycle:'Active',checkedAt:'now'}}}],retries:1});assert.equal((await resolve({family:'SENSOR_CONNECTOR'})).status,'SELECTED')})
test('production resolver fails closed without exact live evidence',async()=>{const resolve=createProductionPartResolver({providers:[{id:'digikey',lookupExact:async()=>({live:true,exact:false})}]});const result=await resolve({family:'USB'});assert.equal(result.blocker.code,'NO_LIVE_EXACT_PRODUCTION_CANDIDATE');assert.equal(JSON.stringify(result).includes('secret'),false)})
test('connector production candidates and approved assets must match six-pin requirement',()=>{assert.equal(approvedAssetFor('M20-9990645',{requiredPinCount:6}).footprint.pads.length,6);assert.equal(approvedAssetFor('M20-9990645',{requiredPinCount:10}),null);assert.equal(approvedAssetFor('20021121-00010T4LF',{requiredPinCount:6}),null)})
test('CAN passives and active TVS have approved physical packages and pin maps',()=>{for(const [mpn,count]of[['RC0603FR-07120RL',2],['CL10B104KB8NNNC',2],['NUP2105LT1G',3]]){const asset=approvedAssetFor(mpn,{requiredPinCount:count});assert.equal(asset.mpn,mpn);assert.equal(Object.keys(asset.pinMap).length,count)}assert.equal(approvedAssetFor('PESD2CAN,215'),null)})
test('dual supplier policy requires exact live evidence from both providers',async()=>{const provider=id=>({id,lookupExact:async mpn=>({live:true,exact:true,stockStatus:'IN_STOCK',quantityAvailable:10,lifecycle:'Active',checkedAt:'now'})});const dual=createProductionPartResolver({providers:[provider('digikey'),provider('mouser')],minimumLiveProviders:2});const selected=await dual({family:'CAN_TVS'});assert.deepEqual(selected.liveProviders,['digikey','mouser']);const blocked=createProductionPartResolver({providers:[provider('digikey')],minimumLiveProviders:2});assert.equal((await blocked({family:'CAN_TVS'})).status,'BLOCKED')})
