import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {quadMosfetDriverProductionProposal,validateQuadMosfetDriverProductionProposal} from '../lib/phase2c/templates/quad-mosfet-driver.mjs'
test('Board017 generic PD sink cannot pass as four protected switch channels',()=>{const d=catalogDefinition(manifest.boards[16],16),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);for(const c of ['quad-switch-power-devices-missing','quad-switch-gate-networks-missing','quad-switch-output-terminals-missing','quad-switch-inductive-clamps-missing','quad-switch-current-rating-evidence-missing','quad-switch-default-off-evidence-missing','quad-switch-thermal-path-evidence-missing','quad-switch-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board017 counts four independent channel paths and blocks exact load-dependent assets',()=>{const p=quadMosfetDriverProductionProposal,g=validateQuadMosfetDriverProductionProposal(p);assert.equal(p.channelCount,4);for(const r of ['Q_CH','R_GATE','J_OUT','D_CLAMP','R_SENSE'])assert.equal(p.bom.find(x=>x.ref===r).quantity,4,r);assert.equal(g.ok,false);assert.ok(g.errors.includes('quad-switch-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['Q_CH','R_GATE','J_OUT','D_CLAMP','R_SENSE','J_PWR','U_CTRL'])})
test('Board017 completeness gate rejects absent topology load power and diagnostic envelopes',()=>{const g=validateQuadMosfetDriverProductionProposal(quadMosfetDriverProductionProposal);for(const code of ['quad-switch-topology-undeclared','quad-load-envelopes-undeclared','quad-power-envelope-undeclared','quad-diagnostic-envelope-undeclared'])assert.ok(g.errors.includes(code),code)})
test('Board017 requires per-channel current thermal clamp and default-off proof',()=>{for(const k of ['perChannelVoltageCurrentSoaVerified','perChannelGateDefaultOffVerified','perChannelInductiveEnergyVerified','perChannelCurrentLimitDiagnosticVerified','simultaneousThermalVerified','productionOpenShortInductiveTestVerified'])assert.ok(quadMosfetDriverProductionProposal.evidenceRequired.includes(k),k)})
test('Board017 thermal-edge outline fits its tight 900 mm2 limit',()=>{const g=validateQuadMosfetDriverProductionProposal(quadMosfetDriverProductionProposal);assert.equal(g.areaMm2,800);assert.ok(g.areaMm2<=900);assert.equal(quadMosfetDriverProductionProposal.outline.purposefulFeatures.channelThermalZones,4);assert.equal(quadMosfetDriverProductionProposal.outline.purposefulFeatures.sharedHeatSpreaderProhibitedWithoutProof,true)})
