import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{QUAD_MOSFET_DRIVER_MECHANICAL_CONTRACT as contract,validateQuadMosfetDriverMechanicalGeometry as validate}from'../lib/phase2c/quad-mosfet-driver-mechanical-contract.mjs'

const outline=[[0,0],[36,0],[36,20],[32,20],[32,24],[4,24],[4,20],[0,20]],centers=[6,14,22,30]
const valid=()=>({outline,outlineClosed:true,body:{widthMm:36,heightMm:20},thermalEdge:{projectionMm:4,spanMm:28,exposedEdgeVerified:true},channelCells:centers.map(centerX=>({centerX,centerY:18,thermalCopperAreaMm2:24,thermalViaCount:6,allCopperLayersTied:true})),outputTerminals:centers.map((centerX,i)=>({channel:i+1,centerX,minY:1,maxY:4})),mountingHoles:[{x:3,y:10,diameterMm:2.7,keepoutRadiusMm:2.7,allLayersKeepout:true},{x:33,y:10,diameterMm:2.7,keepoutRadiusMm:2.7,allLayersKeepout:true}],controlHeader:{minX:1,maxX:4},powerInput:{minX:32,maxX:35},logicToSwitchNodeKeepoutVerified:true,sharedPowerBusCurrentCapacityVerified:true,perChannelProtectionPlacementVerified:true})

test('Board017 manifest preserves thermal-edge intent and 900mm2 cap',()=>{const b=manifest.boards[16];assert.equal(b.id,'017_QUAD_MOSFET_DRIVER');assert.match(b.outline.family,/thermal edge/);assert.equal(b.maximumAreaMm2,900);assert.equal(contract.maximumAreaMm2,900)})
test('current PD-sink octagon fails compact thermal-edge contract',()=>{const d=catalogDefinition(manifest.boards[16],16),r=validate({outline:d.outlinePoints,outlineClosed:true,body:{widthMm:58,heightMm:38}});assert.equal(r.areaMm2,2962.25);assert.equal(r.ok,false);assert.ok(r.errors.includes('quad-switch-outline-exceeds-maximum-area'));assert.ok(r.errors.includes('quad-switch-requires-four-channel-cells'))})
test('purposeful four-cell thermal lip fits inside 900mm2',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,832);assert.equal(r.bounds.width,36);assert.equal(r.bounds.height,24)})
test('four thermal cells require uniform pitch and one output each',()=>{const x=valid();x.channelCells[2].centerX+=2;x.outputTerminals.pop();const e=validate(x).errors;assert.ok(e.includes('quad-switch-output-terminal-count-mismatch'));assert.ok(e.includes('quad-switch-channel-pitch-not-uniform'));assert.ok(e.includes('quad-switch-channel-4-output-not-on-service-edge'))})
test('each channel must touch the thermal edge through copper and vias',()=>{const x=valid();x.channelCells[0].centerY=10;x.channelCells[1].thermalCopperAreaMm2=10;x.channelCells[2].thermalViaCount=1;const e=validate(x).errors;assert.ok(e.includes('quad-switch-channel-1-not-at-thermal-edge'));assert.ok(e.includes('quad-switch-channel-2-thermal-path-unverified'));assert.ok(e.includes('quad-switch-channel-3-thermal-path-unverified'))})
test('opposite-edge controls, power bus and protection evidence fail closed',()=>{const x=valid();x.controlHeader.maxX=9;x.powerInput.minX=20;x.logicToSwitchNodeKeepoutVerified=false;x.sharedPowerBusCurrentCapacityVerified=false;x.perChannelProtectionPlacementVerified=false;const e=validate(x).errors;assert.ok(e.includes('quad-switch-control-header-not-on-left-edge'));assert.ok(e.includes('quad-switch-power-input-not-on-right-edge'));assert.ok(e.includes('quad-switch-logic-switch-node-keepout-unverified'));assert.ok(e.includes('quad-switch-power-bus-capacity-unverified'));assert.ok(e.includes('quad-switch-channel-protection-placement-unverified'))})
