import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{RELAY_CONTROLLER_MECHANICAL_CONTRACT as contract,validateRelayControllerMechanicalGeometry as validate}from'../lib/phase2c/relay-controller-mechanical-contract.mjs'

const terminalEarOutline=[[0,0],[56,0],[56,4],[60,4],[60,14],[56,14],[56,36],[0,36],[0,14],[-4,14],[-4,4],[0,4]]
const valid=()=>({outline:terminalEarOutline,outlineClosed:true,body:{widthMm:56,heightMm:36},ears:[{projectionMm:4,lengthMm:10,hole:{x:-2,y:9,diameterMm:3.2,copperKeepoutRadiusMm:3.2,allLayersKeepout:true}},{projectionMm:4,lengthMm:10,hole:{x:58,y:9,diameterMm:3.2,copperKeepoutRadiusMm:3.2,allLayersKeepout:true}}],placements:{powerInput:{minX:1,maxX:5},logic:{minX:8,maxX:26},relayDrivers:{minX:29,maxX:37},relayBank:{minX:39,maxX:51},fieldTerminals:{minX:53,maxX:59}},domainSeparation:{logicToContactClearanceMm:3.2,allLayersKeepoutVerified:true,contactVoltagePrimarySourceVerified:true},edgeCopperClearanceVerified:true})

test('Board013 manifest preserves terminal-ear intent and 2300mm2 cap',()=>{const board=manifest.boards[12];assert.equal(board.id,'013_RELAY_CONTROLLER');assert.match(board.outline.family,/terminal ears/);assert.equal(board.maximumAreaMm2,2300);assert.equal(contract.maximumAreaMm2,2300)})
test('current chamfered catalog clone fails area and functional-ear checks',()=>{const definition=catalogDefinition(manifest.boards[12],12),result=validate({outline:definition.outlinePoints,outlineClosed:true,body:{widthMm:62,heightMm:38},ears:[]});assert.equal(result.ok,false);assert.ok(result.errors.includes('relay-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('relay-body-envelope-invalid'));assert.ok(result.errors.includes('terminal-ears-missing'));assert.equal(result.areaMm2,2928.25)})
test('purposeful two-ear relay envelope fits the maximum area',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,2096);assert.equal(result.bounds.width,64);assert.equal(result.bounds.height,36)})
test('each terminal ear requires a real mounting hole and all-layer keepout',()=>{const x=valid();delete x.ears[0].hole;x.ears[1].hole.copperKeepoutRadiusMm=2;const e=validate(x).errors;assert.ok(e.includes('terminal-ear-1-mounting-hole-missing'));assert.ok(e.includes('terminal-ear-1-hole-keepout-unverified'));assert.ok(e.includes('terminal-ear-2-hole-keepout-unverified'))})
test('relay, driver, logic and edge terminals stay in ordered serviceable envelopes',()=>{const x=valid();x.placements.relayBank.minX=20;x.placements.fieldTerminals.minX=48;x.placements.powerInput.maxX=10;const e=validate(x).errors;assert.ok(e.includes('relay-bank-outside-placement-envelope'));assert.ok(e.includes('field-terminals-not-on-output-edge'));assert.ok(e.includes('power-input-not-on-opposite-edge'))})
test('contact domain separation is fail closed against unverified relay ratings',()=>{const x=valid();x.domainSeparation.logicToContactClearanceMm=2;x.domainSeparation.allLayersKeepoutVerified=false;x.domainSeparation.contactVoltagePrimarySourceVerified=false;const e=validate(x).errors;assert.ok(e.includes('logic-to-contact-clearance-insufficient'));assert.ok(e.includes('logic-to-contact-keepout-unverified'));assert.ok(e.includes('relay-contact-voltage-evidence-missing'))})
