import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {roboticsMainProductionProposal,validateRoboticsMainProductionProposal} from '../lib/phase2c/templates/robotics-main.mjs'
test('Board033 generic CAN controller cannot pass as robot coordinator',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[32],32));assert.equal(g.ok,false);for(const c of ['robotics-real-time-controller-missing','robotics-actuator-interface-missing','robotics-sensor-interface-missing','robotics-platform-connectors-missing','robotics-interface-protection-missing','robotics-power-tree-missing','robotics-power-monitoring-missing','robotics-emergency-stop-missing','robotics-watchdog-supervisor-missing','robotics-safe-default-state-missing','robotics-main-category-mapped-to-generic-can-controller'])assert.ok(g.errors.includes(c),c)})
test('Board033 reuses approved controller CAN protection and blocks unresolved robot interfaces',()=>{const p=roboticsMainProductionProposal,g=validateRoboticsMainProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('robotics-main-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['J_MOTOR','P_MOTOR','J_ENC','P_ENC','J_SENSOR','J_ESTOP','P_SAFE','U_WDOG','P_PWR','U_MON','J_PWR','J_SERVICE','P_TEST']);for(const r of ['U_CTRL','U_CAN','R_CAN','D_CAN','F_IN','D_IN','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board033 requires safety power EMC fault thermal and HIL evidence',()=>{for(const k of ['realtimeDeadlineJitterVerified','motorInterfaceSafeStateVerified','dualChannelEstopDiagnosticsVerified','hardwareSafeDisableIndependentVerified','watchdogBrownoutResetCauseVerified','powerTreeTransientVerified','railCurrentVoltageAccuracyVerified','groundingShieldEmcVerified','productionHilSafetyFaultInjectionVerified'])assert.ok(roboticsMainProductionProposal.evidenceRequired.includes(k),k)})
test('Board033 robot mounting outline stays inside 900 mm2',()=>{const p=roboticsMainProductionProposal,g=validateRoboticsMainProductionProposal(p);assert.equal(g.areaMm2,832);assert.ok(g.areaMm2<=900);assert.equal(p.outline.purposefulFeatures.mountingHoleCount,4);assert.equal(p.outline.purposefulFeatures.estopKeepoutRequired,true)})
