import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{ROBOTICS_MAIN_MECHANICAL_CONTRACT as contract,validateRoboticsMainMechanicalGeometry as validate}from'../lib/phase2c/robotics-main-mechanical-contract.mjs'

const chassisOutline=[[0,0],[40,0],[40,5],[36,5],[36,19],[40,19],[40,24],[0,24],[0,19],[4,19],[4,5],[0,5]]
const valid=()=>({outline:chassisOutline,outlineClosed:true,chassisDatum:{centerlineRecorded:true,forwardAxisRecorded:true,chassisEnvelopeVerified:true,mountPatternWidthMm:24,mountPatternHeightMm:14,mountPatternSymmetric:true},wheelReliefs:[{depthMm:4,spanMm:14,edgeCutsVerified:true,wheelSweepClearanceVerified:true},{depthMm:4,spanMm:14,edgeCutsVerified:true,wheelSweepClearanceVerified:true}],wheelReliefsSymmetric:true,chassisMountingHoles:[{x:8,y:5,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,standoffClearanceVerified:true},{x:32,y:5,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,standoffClearanceVerified:true},{x:8,y:19,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,standoffClearanceVerified:true},{x:32,y:19,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,standoffClearanceVerified:true}],placements:{frontSensors:{minY:19,maxY:23},rearPower:{minY:1,maxY:5},coordinationCore:{minX:13,maxX:27},motorInterfaces:[{alignedToSide:true},{alignedToSide:true}]},cableRouting:{clearOfWheelSweeps:true,strainReliefAndChassisTiePointsVerified:true},assemblyClearance:{maximumHeightVerified:true,batteryAndFrameClearanceVerified:true}})

test('Board033 manifest preserves robot-chassis intent and 900mm2 cap',()=>{const board=manifest.boards[32];assert.equal(board.id,'033_ROBOTICS_MAIN');assert.equal(board.outline.family,'robot chassis-robotics-main');assert.equal(board.maximumAreaMm2,900);assert.equal(contract.maximumAreaMm2,900)})
test('current catalog outline exceeds compact cap and lacks chassis evidence',()=>{const definition=catalogDefinition(manifest.boards[32],32),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2>900);assert.ok(result.errors.includes('robotics-main-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('robot-chassis-datum-unverified'))})
test('purposeful wheel-relief robot controller fits the area cap',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,848);assert.equal(result.bounds.width,40);assert.equal(result.bounds.height,24)})
test('paired wheel reliefs require symmetry and verified sweep clearance',()=>{const x=valid();x.wheelReliefs[0].depthMm=2;x.wheelReliefs[1].wheelSweepClearanceVerified=false;x.wheelReliefsSymmetric=false;const e=validate(x).errors;assert.ok(e.includes('robot-wheel-reliefs-unverified'));assert.ok(e.includes('robot-wheel-sweep-clearance-unverified'))})
test('four-hole chassis pattern and centered coordination core fail closed',()=>{const x=valid();x.chassisMountingHoles.pop();x.chassisDatum.mountPatternSymmetric=false;x.placements.coordinationCore.maxX=35;const e=validate(x).errors;assert.ok(e.includes('robot-chassis-mount-count-invalid'));assert.ok(e.includes('robot-chassis-mount-pattern-unverified'));assert.ok(e.includes('robot-coordination-core-not-centered'))})
test('front, rear, side cables and assembly stay clear of the wheel system',()=>{const x=valid();x.placements.frontSensors.minY=10;x.placements.rearPower.maxY=12;x.placements.motorInterfaces[0].alignedToSide=false;x.cableRouting.clearOfWheelSweeps=false;x.assemblyClearance.batteryAndFrameClearanceVerified=false;const e=validate(x).errors;assert.ok(e.includes('robot-sensor-interface-not-on-front-edge'));assert.ok(e.includes('robot-power-not-on-rear-edge'));assert.ok(e.includes('robot-motor-interfaces-not-side-aligned'));assert.ok(e.includes('robot-chassis-cable-routing-unverified'));assert.ok(e.includes('robot-chassis-assembly-clearance-unverified'))})
