import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{ROBOTICS_EXPANSION_MECHANICAL_CONTRACT as contract,validateRoboticsExpansionMechanicalGeometry as validate}from'../lib/phase2c/robotics-expansion-mechanical-contract.mjs'

const mezzanineOutline=[[0,0],[44,0],[44,26],[30,26],[30,23],[26,23],[26,26],[18,26],[18,23],[14,23],[14,26],[0,26]]
const valid=()=>({outline:mezzanineOutline,outlineClosed:true,stackDatum:{originRecorded:true,rotationRecorded:true,parentBoardEnvelopeMatched:true},registrationNotches:[{centerXmm:16,widthMm:4,depthMm:3,edgeCutsVerified:true},{centerXmm:28,widthMm:4,depthMm:3,edgeCutsVerified:true}],notchesSymmetricAndParentMatched:true,placements:{mezzanineConnectors:[{maxY:6,parentMateAligned:true},{maxY:6,parentMateAligned:true}],ioConnectors:[{minY:20,maxY:25},{minY:20,maxY:25}],expansionLogic:{minX:14,maxX:30}},stackClearance:{connectorMatedHeightVerified:true,topAndBottomComponentEnvelopesVerified:true,noCollisionWithParentComponents:true,insertionAndRemovalToolAccessVerified:true,ioCableExitClearOfParentBoard:true},stackMountingHoles:[{x:6,y:13,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,parentStandoffAligned:true,fastenerClearanceVerified:true},{x:38,y:13,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,parentStandoffAligned:true,fastenerClearanceVerified:true}],cableStrain:{transferredToChassisNotMezzanine:true}})

test('Board034 manifest preserves mezzanine-matched intent and 1250mm2 cap',()=>{const board=manifest.boards[33];assert.equal(board.id,'034_ROBOTICS_EXPANSION');assert.equal(board.outline.family,'mezzanine matched-robotics-expansion');assert.equal(board.maximumAreaMm2,1250);assert.equal(contract.maximumAreaMm2,1250)})
test('current catalog outline exceeds cap and lacks stack-registration evidence',()=>{const definition=catalogDefinition(manifest.boards[33],33),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2>1250);assert.ok(result.errors.includes('robotics-expansion-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('mezzanine-stack-datum-unverified'))})
test('purposeful registered mezzanine expansion fits the area cap',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,1120);assert.equal(result.bounds.width,44);assert.equal(result.bounds.height,26)})
test('paired registration notches require parent match and spacing',()=>{const x=valid();x.registrationNotches[0].depthMm=1;x.registrationNotches[1].centerXmm=20;x.notchesSymmetricAndParentMatched=false;const e=validate(x).errors;assert.ok(e.includes('mezzanine-registration-notches-unverified'));assert.ok(e.includes('mezzanine-registration-notch-spacing-insufficient'));assert.ok(e.includes('mezzanine-registration-match-unverified'))})
test('board-to-board connectors, IO and logic retain ordered placement',()=>{const x=valid();x.placements.mezzanineConnectors[0].parentMateAligned=false;x.placements.ioConnectors[1].minY=10;x.placements.expansionLogic.maxX=40;const e=validate(x).errors;assert.ok(e.includes('mezzanine-connectors-not-parent-aligned'));assert.ok(e.includes('robot-io-connectors-not-on-service-edge'));assert.ok(e.includes('expansion-logic-outside-central-envelope'))})
test('stack height, service access, standoffs and cable strain fail closed',()=>{const x=valid();x.stackClearance.noCollisionWithParentComponents=false;x.stackClearance.insertionAndRemovalToolAccessVerified=false;x.stackMountingHoles[0].parentStandoffAligned=false;x.stackMountingHoles[1].allLayersKeepout=false;x.cableStrain.transferredToChassisNotMezzanine=false;const e=validate(x).errors;assert.ok(e.includes('mezzanine-stack-height-clearance-unverified'));assert.ok(e.includes('mezzanine-service-access-unverified'));assert.ok(e.includes('stack-mount-1-invalid'));assert.ok(e.includes('stack-mount-2-keepout-unverified'));assert.ok(e.includes('mezzanine-io-cable-strain-unverified'))})
