import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {rs485GatewayProductionProposal,validateRs485GatewayProductionProposal} from '../lib/phase2c/templates/rs485-gateway.mjs'
test('Board049 CAN controller cannot pass as isolated RS485 gateway',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[48],48));assert.equal(g.ok,false);for(const c of ['rs485-gateway-host-controller-missing','rs485-gateway-isolated-transceiver-missing','rs485-gateway-isolated-power-missing','rs485-gateway-barrier-evidence-missing','rs485-gateway-field-connector-missing','rs485-gateway-termination-bias-missing','rs485-gateway-surge-esd-missing','rs485-gateway-shield-grounding-missing','rs485-gateway-host-interface-missing','rs485-gateway-direction-timing-missing','rs485-gateway-baud-loading-evidence-missing','rs485-gateway-production-loopback-missing','rs485-gateway-category-mapped-to-can-controller'])assert.ok(g.errors.includes(c),c)})
test('Board049 reuses approved host assets and blocks isolated field chain',()=>{const p=rs485GatewayProductionProposal,g=validateRs485GatewayProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('rs485-gateway-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_485','P_ISOPWR','P_BARRIER','J_FIELD','P_TERM','P_BIAS','P_SURGE','P_SHIELD','P_HOST','P_WDOG','P_TEST','P_DIN']);for(const r of ['U_CTRL','U_CFG','J_USB','D_USB','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board049 requires topology isolation turnaround surge DIN and dielectric evidence',()=>{for(const k of ['rs485ModeRateTopologyVerified','transceiverCommonModeUnitLoadVerified','isolatedPowerLoadTransientVerified','barrierWorkingTransientVerified','creepageClearanceSlotVerified','terminationOwnershipVerified','failsafeBiasNetworkVerified','directionTurnaroundCollisionVerified','surgeClampPostRateVerified','productionBusBarrierDielectricVerified'])assert.ok(rs485GatewayProductionProposal.evidenceRequired.includes(k),k)})
test('Board049 DIN-rail outline stays inside 900 mm2',()=>{const p=rs485GatewayProductionProposal,g=validateRs485GatewayProductionProposal(p);assert.equal(g.areaMm2,832);assert.ok(g.areaMm2<=900);assert.equal(p.outline.purposefulFeatures.dinRailHook.projectionMm,4);assert.equal(p.outline.purposefulFeatures.barrierSlotRequired,true)})
