import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{SERVO_CONTROLLER_MECHANICAL_CONTRACT as contract,validateServoControllerMechanicalGeometry as validate}from'../lib/phase2c/servo-controller-mechanical-contract.mjs'

const definition=catalogDefinition(manifest.boards[14],14),centers=[9.5,16.34,23.18,30.02]
const valid=()=>({outline:definition.outlinePoints,outlineClosed:true,body:{widthMm:62,heightMm:38},combTeeth:centers.map(centerY=>({centerY,projectionMm:4,spanMm:5})),servoConnectorBays:centers.map(centerY=>({centerY,pinCount:3,minX:63,maxX:66,cableExitDepthMm:10})),mountingHoles:[{x:5,y:5,diameterMm:3.2,keepoutRadiusMm:3.2,allLayersKeepout:true},{x:5,y:33,diameterMm:3.2,keepoutRadiusMm:3.2,allLayersKeepout:true}],placements:{powerInput:{minX:1,maxX:6},logic:{minX:8,maxX:30},signalBuffer:{minX:32,maxX:44},servoPowerSpine:{minX:46,maxX:61}},powerSpineCopperWidthVerified:true,bulkCapacitorAdjacentToComb:true,logicPowerDomainSeparated:true})

test('Board015 manifest preserves connector-comb intent and 3000mm2 cap',()=>{const board=manifest.boards[14];assert.equal(board.id,'015_SERVO_CONTROLLER');assert.match(board.outline.family,/connector comb/);assert.equal(board.maximumAreaMm2,3000);assert.equal(contract.maximumAreaMm2,3000)})
test('current outline fits area but fails closed without functional comb evidence',()=>{const r=validate({outline:definition.outlinePoints,outlineClosed:true,body:{widthMm:62,heightMm:38}});assert.equal(r.areaMm2,2587.25);assert.equal(r.ok,false);assert.ok(r.errors.includes('servo-connector-comb-too-few-teeth'));assert.ok(r.errors.includes('servo-controller-mounting-holes-missing'))})
test('four aligned connector teeth make the existing unique outline purposeful',()=>{const r=validate(valid());assert.equal(r.ok,true,r.errors.join('; '));assert.equal(r.areaMm2,2587.25);assert.equal(r.bounds.width,67.5);assert.equal(r.bounds.height,39.5)})
test('comb teeth and three-pin servo bays are one-to-one and uniformly pitched',()=>{const x=valid();x.servoConnectorBays.pop();x.combTeeth[2].centerY+=2;const e=validate(x).errors;assert.ok(e.includes('servo-comb-to-connector-count-mismatch'));assert.ok(e.includes('servo-connector-bay-3-not-aligned-to-tooth'));assert.ok(e.includes('servo-comb-pitch-not-uniform'))})
test('each connector bay requires edge placement and unobstructed cable exit',()=>{const x=valid();x.servoConnectorBays[0].minX=55;x.servoConnectorBays[1].cableExitDepthMm=4;x.servoConnectorBays[2].pinCount=2;const e=validate(x).errors;assert.ok(e.includes('servo-connector-bay-1-not-on-comb-edge'));assert.ok(e.includes('servo-connector-bay-2-cable-exit-obstructed'));assert.ok(e.includes('servo-connector-bay-3-not-three-pin'))})
test('servo power spine and logic separation require explicit evidence',()=>{const x=valid();x.placements.servoPowerSpine.minX=35;x.powerSpineCopperWidthVerified=false;x.bulkCapacitorAdjacentToComb=false;x.logicPowerDomainSeparated=false;const e=validate(x).errors;assert.ok(e.includes('servo-power-spine-outside-placement-envelope'));assert.ok(e.includes('servo-power-spine-current-capacity-unverified'));assert.ok(e.includes('servo-bulk-capacitor-not-adjacent-to-comb'));assert.ok(e.includes('servo-logic-power-domain-separation-unverified'))})
