import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {servoControllerProductionProposal,validateServoControllerProductionProposal} from '../lib/phase2c/templates/servo-controller.mjs'
test('Board015 generic controller cannot pass as multi-channel servo hardware',()=>{const d=catalogDefinition(manifest.boards[14],14),g=validateCatalogSemanticTopology(d);assert.equal(g.ok,false);for(const c of ['servo-channel-connectors-missing','servo-pwm-controller-missing','servo-power-entry-protection-missing','servo-rail-bulk-decoupling-missing','servo-rail-current-capability-missing','servo-signal-protection-missing','servo-failsafe-output-state-missing','servo-supply-monitoring-missing'])assert.ok(g.errors.includes(c),c)})
test('Board015 defines eight channels and blocks every envelope-dependent exact asset',()=>{const p=servoControllerProductionProposal,g=validateServoControllerProductionProposal(p);assert.equal(p.channelCount,8);assert.equal(g.ok,false);assert.ok(g.errors.includes('servo-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_PWM','J_SERVO','R_SIG','U_RAIL','U_MON','U_LOGIC','J_PWR']);for(const r of ['F1','Q_REV','D_TVS','C_BULK','C_LOCAL'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board015 requires failsafe monitoring simultaneous-stall and thermal evidence',()=>{for(const k of ['simultaneousStallCurrentVerified','failsafeOutputsVerified','supplyMonitoringFaultThresholdsVerified','copperConnectorThermalVerified','productionLoadFaultTestVerified'])assert.ok(servoControllerProductionProposal.evidenceRequired.includes(k),k)})
test('Board015 connector-comb outline has eight teeth within 3000 mm2',()=>{const g=validateServoControllerProductionProposal(servoControllerProductionProposal);assert.equal(g.areaMm2,2816);assert.ok(g.areaMm2<=3000);assert.equal(servoControllerProductionProposal.outline.purposefulFeatures.servoConnectorTeeth,8);assert.equal(servoControllerProductionProposal.outline.purposefulFeatures.highCurrentSpineRequired,true)})
