import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {touchInterfaceProductionProposal,validateTouchInterfaceProductionProposal} from '../lib/phase2c/templates/touch-interface.mjs'
test('Board037 CAN controller cannot pass as capacitive touch panel',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[36],36));assert.equal(g.ok,false);for(const c of ['touch-controller-missing','touch-electrodes-missing','touch-sense-conditioning-missing','touch-host-interface-missing','touch-esd-protection-missing','touch-overlay-evidence-missing','touch-shield-ground-strategy-missing','touch-water-glove-evidence-missing','touch-baseline-recovery-missing','touch-production-raw-count-test-missing','touch-interface-category-mapped-to-can-controller'])assert.ok(g.errors.includes(c),c)})
test('Board037 reuses approved support assets and blocks unresolved touch stack',()=>{const p=touchInterfaceProductionProposal,g=validateTouchInterfaceProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('touch-interface-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_TOUCH','P_ELEC','P_GUARD','P_SENSE','D_TOUCH','J_HOST','P_SHIELD','P_OVERLAY','P_FEEDBACK','P_TEST']);for(const r of ['U_HOST','U_CAL','U_PWR','FB_PWR','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r)})
test('Board037 requires sensitivity moisture glove EMC and final-fascia fixture evidence',()=>{for(const k of ['electrodeParasiticSensitivityVerified','guardShieldGroundStrategyVerified','fasciaMaterialThicknessDielectricVerified','touchEsdLeakageVerified','baselineDriftRecalibrationVerified','moistureDropletRejectionVerified','gloveOperationVerified','emcChargerNoiseVerified','productionFinalFasciaRawCountFixtureVerified'])assert.ok(touchInterfaceProductionProposal.evidenceRequired.includes(k),k)})
test('Board037 fascia electrode outline stays inside 2300 mm2',()=>{const p=touchInterfaceProductionProposal,g=validateTouchInterfaceProductionProposal(p);assert.equal(g.areaMm2,2248);assert.ok(g.areaMm2<=2300);assert.equal(p.outline.purposefulFeatures.guardRingRequired,true);assert.equal(p.outline.purposefulFeatures.overlayDatumCount,3)})
