import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{USB_ISOLATOR_MECHANICAL_CONTRACT as contract,validateUsbIsolatorMechanicalGeometry as validate}from'../lib/phase2c/usb-isolator-mechanical-contract.mjs'

const outline=catalogDefinition(manifest.boards[11],11).outlinePoints
const valid=()=>({isolationClass:'basic',outline,outlineClosed:true,corridor:{centerXmm:21,clearanceMm:4,creepageMm:4,allCopperLayersKeepout:true,noPlanesTracksOrVias:true,maskAndSilkDoNotBridge:true},ratings:{usbIsolatorPrimarySourceVerified:true,usbIsolatorWithstandVrms:2500,isolatedPowerPrimarySourceVerified:true,isolatedPowerWithstandVrms:2500},placements:{upstreamConnector:{x:3},downstreamConnector:{x:40},upstreamEsd:{minX:7,maxX:10},usbIsolator:{minX:17,maxX:25,minY:3,maxY:9},isolatedPower:{minX:17,maxX:25,minY:13,maxY:19},downstreamEsd:{minX:31,maxX:35}},domainNets:{upstreamGround:'GND_UP',downstreamGround:'GND_ISO',upstreamPower:'VBUS_UP',downstreamPower:'VBUS_ISO'},slot:{enabled:false},slotRequiredBySelectedPackages:false})

test('Board012 existing isolation-waist outline supports separated edge domains',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.bounds.width,47.5);assert.equal(result.bounds.height,26.5);assert.equal(contract.barrierCenterXmm,21)})
test('basic isolation contract is source-backed and conservatively rounded to 4mm',()=>{assert.equal(contract.isolationClasses.basic.minimumWithstandVrms,2500);assert.equal(contract.isolationClasses.basic.minimumCreepageMm,4);assert.equal(contract.isolationClasses.basic.minimumClearanceMm,4);assert.ok(contract.primarySources.every(row=>/^https:/.test(row.url)))})
test('reinforced mode requires 5kVrms and an 8mm barrier',()=>{const x=valid();x.isolationClass='reinforced';const failed=validate(x);assert.ok(failed.errors.includes('isolation-corridor-clearance-insufficient'));assert.ok(failed.errors.includes('usb-isolator-primary-rating-insufficient'));x.corridor.clearanceMm=8;x.corridor.creepageMm=8;x.ratings.usbIsolatorWithstandVrms=5000;x.ratings.isolatedPowerWithstandVrms=5000;assert.equal(validate(x).ok,true)})
test('connector, ESD, isolator and converter envelopes fail closed',()=>{const x=valid();x.placements.upstreamConnector.x=12;x.placements.downstreamEsd.minX=20;x.placements.isolatedPower.minY=8;const e=validate(x).errors;assert.ok(e.includes('upstream-connector-not-on-left-edge'));assert.ok(e.includes('downstreamEsd-outside-placement-envelope'));assert.ok(e.includes('barrier-bridging-components-overlap'))})
test('no copper or common ground may shortcut the isolation corridor',()=>{const x=valid();x.corridor.noPlanesTracksOrVias=false;x.domainNets.downstreamGround='GND_UP';const e=validate(x).errors;assert.ok(e.includes('isolation-corridor-copper-keepout-unverified'));assert.ok(e.includes('usb-isolator-ground-domains-not-distinct'))})
test('slot is optional with proven geometry but mandatory when selected packages require it',()=>{const x=valid();x.slotRequiredBySelectedPackages=true;assert.ok(validate(x).errors.includes('isolation-slot-required-but-missing'));x.slot={enabled:true,edgeCutsVerified:true,centerXmm:21,lengthMm:10,plated:false};assert.equal(validate(x).ok,true)})
