import test from'node:test';import assert from'node:assert/strict';import{usbCPdSourceTemplate as t,validateUsbCPdSourceTemplate as validate}from'../lib/phase2c/templates/usb-c-pd-source.mjs';import{approvedAssetFor}from'../lib/components/approved-production-assets.mjs'
import{validateCopperStackup}from'../lib/manufacturing/copper-stackup-contract.mjs'
test('Board005 is a 5V SELV-only protected source',()=>{assert.deepEqual(validate(t),{ok:true,errors:[]});assert.deepEqual(t.electrical.sourcePdos,[{voltageV:5,currentA:1.5,powerW:7.5}]);assert.equal(t.electrical.noMains,true);assert.equal(t.electrical.noBoost,true)})
test('unsafe advertised PDOs fail closed',()=>{const x=structuredClone(t);x.electrical.sourcePdos.push({voltageV:9,currentA:2,powerW:18});assert.ok(validate(x).errors.includes('unsupported-source-pdo'))})
test('all Board005 exact parts have approved pin-compatible assets',()=>{for(const p of t.requirements)assert.equal(approvedAssetFor(p.mpn,{requiredPinCount:p.pinCount})?.mpn,p.mpn,p.ref)})
test('datasheet minimum source capacitance is structural',()=>{const x=structuredClone(t);x.requirements.find(p=>p.role==='PP5V_BULK').rating.capacitanceUf=100;assert.ok(validate(x).errors.includes('pp5v-bulk-too-small'))})
test('EEPROM configuration proof is a fail-closed manufacturing gate',()=>{assert.equal(t.configurationGate.failClosed,true);assert.ok(t.configurationGate.requiredEvidence.includes('programmed EEPROM readback digest'));assert.equal(t.acceptance.pdoImageVerified,true)})
test('Board005 requires the exact KiCad-proven six-layer rail stack',()=>{assert.equal(t.electrical.layers,6);assert.deepEqual(validateCopperStackup(t.stackup),{ok:true,errors:[]});assert.deepEqual(t.stackup.railMergeLayers,{GND:'In1.Cu',DRAIN:'In2.Cu',VBUS:'In3.Cu',PP5V:'In4.Cu','3V3':'B.Cu'});assert.match(t.stackup.justification,/Four-layer parity is not claimed/)})
test('Board005 rejects unproven four-layer substitutions',()=>{const x=structuredClone(t);x.electrical.layers=4;x.stackup.copperLayers=4;x.stackup.layerOrder=['F.Cu','In1.Cu','In2.Cu','B.Cu'];assert.ok(validate(x).errors.includes('unproven-pd-source-stackup'))})
