import test from'node:test';import assert from'node:assert/strict';import{usbCPdSourceTemplate as t,validateUsbCPdSourceConfigurationEvidence as validateConfig,validateUsbCPdSourceTemplate as validate}from'../lib/phase2c/templates/usb-c-pd-source.mjs';import{approvedAssetFor}from'../lib/components/approved-production-assets.mjs'
import{validateCopperStackup}from'../lib/manufacturing/copper-stackup-contract.mjs'
test('Board005 is a 5V SELV-only protected source',()=>{assert.deepEqual(validate(t),{ok:true,errors:[]});assert.deepEqual(t.electrical.sourcePdos,[{voltageV:5,currentA:1.5,powerW:7.5}]);assert.equal(t.electrical.noMains,true);assert.equal(t.electrical.noBoost,true)})
test('unsafe advertised PDOs fail closed',()=>{const x=structuredClone(t);x.electrical.sourcePdos.push({voltageV:9,currentA:2,powerW:18});assert.ok(validate(x).errors.includes('unsupported-source-pdo'))})
test('all Board005 exact parts have approved pin-compatible assets',()=>{for(const p of t.requirements)assert.equal(approvedAssetFor(p.mpn,{requiredPinCount:p.pinCount})?.mpn,p.mpn,p.ref)})
test('EEPROM I2C has exact approved 5.1k pull-ups to LDO_3V3',()=>{for(const ref of['R_EEPROM_SDA','R_EEPROM_SCL']){const p=t.requirements.find(x=>x.ref===ref);assert.equal(p.mpn,'RC0603FR-075K1L');assert.equal(p.rating.resistanceOhm,5100);assert.equal(p.rating.pullupRail,'LDO_3V3')}})
test('datasheet minimum source capacitance is structural',()=>{const x=structuredClone(t);x.requirements.find(p=>p.role==='PP5V_BULK').rating.capacitanceUf=100;assert.ok(validate(x).errors.includes('pp5v-bulk-too-small'))})
test('EEPROM configuration proof is a fail-closed manufacturing gate',()=>{assert.equal(t.configurationGate.failClosed,true);assert.ok(t.configurationGate.requiredEvidence.includes('programmed EEPROM readback digest'));assert.equal(t.acceptance.pdoImageVerified,false);assert.equal(validateConfig({}).valid,false)})
test('configuration evidence requires exact single PDO and matching programmed readback',()=>{const hash='a'.repeat(64),evidence={binaryPath:'tps25750.bin',readbackPath:'tps25750-readback.bin',sha256:hash,parsedPdos:[{voltageV:5,currentA:1.5}],currentLimitSetting:1,readbackSha256:hash};assert.equal(validateConfig(evidence).valid,true);assert.equal(validateConfig({...evidence,parsedPdos:[{voltageV:9,currentA:2}]}).valid,false);assert.equal(validateConfig({...evidence,readbackSha256:'b'.repeat(64)}).valid,false)})
test('Board005 requires the exact KiCad-proven six-layer rail stack',()=>{assert.equal(t.electrical.layers,6);assert.deepEqual(validateCopperStackup(t.stackup),{ok:true,errors:[]});assert.deepEqual(t.stackup.railMergeLayers,{GND:'In1.Cu',DRAIN:'In2.Cu',VBUS:'In3.Cu',PP5V:'In4.Cu','3V3':'B.Cu'});assert.match(t.stackup.justification,/Four-layer parity is not claimed/)})
test('Board005 rejects unproven four-layer substitutions',()=>{const x=structuredClone(t);x.electrical.layers=4;x.stackup.copperLayers=4;x.stackup.layerOrder=['F.Cu','In1.Cu','In2.Cu','B.Cu'];assert.ok(validate(x).errors.includes('unproven-pd-source-stackup'))})
