import test from 'node:test'
import assert from 'node:assert/strict'
import manifest from '../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import {catalogDefinition,validateCatalogSemanticTopology} from '../lib/phase2c/catalog-production-engine.mjs'
import {voltageMonitorProductionProposal,validateVoltageMonitorProductionProposal} from '../lib/phase2c/templates/voltage-monitor.mjs'
test('Board047 PD sink cannot pass as protected HV telemetry',()=>{const g=validateCatalogSemanticTopology(catalogDefinition(manifest.boards[46],46));assert.equal(g.ok,false);for(const c of ['high-voltage-input-terminal-missing','high-voltage-divider-missing','high-voltage-input-protection-missing','high-voltage-discharge-path-missing','voltage-measurement-adc-missing','voltage-measurement-reference-missing','high-voltage-isolation-data-missing','high-voltage-isolated-power-missing','high-voltage-spacing-evidence-missing','high-voltage-rating-evidence-missing','high-voltage-telemetry-interface-missing','high-voltage-calibration-safety-test-missing','voltage-monitor-category-mapped-to-pd-sink'])assert.ok(g.errors.includes(c),c)})
test('Board047 preserves only unconditional exact support and blocks application-dependent secondary assets',()=>{const p=voltageMonitorProductionProposal,g=validateVoltageMonitorProductionProposal(p);assert.equal(g.ok,false);assert.ok(g.errors.includes('voltage-monitor-exact-assets-unapproved'));assert.deepEqual(g.blockedRefs,['U_CTRL','U_PWR','J_HV','F_HV','P_DIV','P_CLAMP','P_BLEED','U_ISO','P_BARRIER','P_ISOPWR','U_ADC','J_HOST','P_HVPROT','P_TEST']);for(const r of ['U_CAL','C_DEC'])assert.equal(p.bom.find(x=>x.ref===r).status,'APPROVED_EXACT_ASSET',r);for(const r of ['U_CTRL','U_PWR'])assert.equal(p.bom.find(x=>x.ref===r).status,'BLOCKED_UNJUSTIFIED_EXACT_SELECTION',r)})
test('Board047 requires rating divider isolation discharge safety EMC and hipot evidence',()=>{for(const k of ['workingTransientSourceEnergyVerified','categoryPollutionAltitudeVerified','inputFuseInterruptCoordinationVerified','dividerPerElementVoltagePulseVerified','dividerRatioDriftThermalVerified','clampEnergyRecoveryVerified','bleedDischargeSingleFaultVerified','isolationBarrierCreepageClearanceVerified','hazardousTouchContainmentVerified','productionCalibrationHipotDischargeVerified'])assert.ok(voltageMonitorProductionProposal.evidenceRequired.includes(k),k)})
test('Board047 isolation-tongue outline stays inside 3000 mm2',()=>{const p=voltageMonitorProductionProposal,g=validateVoltageMonitorProductionProposal(p);assert.equal(g.areaMm2,2760);assert.ok(g.areaMm2<=3000);assert.equal(p.outline.purposefulFeatures.barrierSlotLengthMm,28);assert.equal(p.outline.purposefulFeatures.hazardousSideKeepoutRequired,true)})
