import test from'node:test'
import assert from'node:assert/strict'
import{manifest}from'../../../fixtures/phase2c/50-board-challenge-manifest.mjs'
import{catalogDefinition}from'../lib/phase2c/catalog-production-engine.mjs'
import{WIFI_GATEWAY_MECHANICAL_CONTRACT as contract,validateWifiGatewayMechanicalGeometry as validate}from'../lib/phase2c/wifi-gateway-mechanical-contract.mjs'

const wingOutline=[[0,0],[36,0],[36,4],[40,4],[40,7],[48,7],[48,17],[40,17],[40,20],[36,20],[36,24],[0,24],[-3,21],[-3,3]]
const valid=()=>({outline:wingOutline,outlineClosed:true,antennaWing:{projectionMm:12,spanMm:10,neckWidthMm:10,edgeCutsVerified:true,structuralNeckClearanceVerified:true,enclosureWindowAligned:true},antennaKeepout:{wholeWingVerified:true,allCopperLayers:true,noPlanesTracksOrVias:true,noComponentsExceptFeedAndMatching:true,noMetalFastenersOrCablesInFieldRegion:true},placements:{antenna:{minX:39,maxX:47},radio:{minX:29,maxX:36},gatewayInterface:{minX:11,maxX:25},connectors:{minX:0,maxX:5}},rfTransition:{radioMatchingAndAntennaAdjacent:true,crossesNoConnectorOrPowerCorridor:true},separation:{antennaToNoisyCircuitMm:10,connectorCableExitClearOfWing:true},mountingHoles:[{x:6,y:5,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inAntennaWing:false},{x:6,y:19,diameterMm:3,copperKeepoutRadiusMm:3,allLayersKeepout:true,inAntennaWing:false}]})

test('Board026 manifest preserves antenna-wing intent and 1250mm2 cap',()=>{const board=manifest.boards[25];assert.equal(board.id,'026_WIFI_GATEWAY');assert.equal(board.outline.family,'antenna wing-wifi-gateway');assert.equal(board.maximumAreaMm2,1250);assert.equal(contract.maximumAreaMm2,1250)})
test('current catalog outline exceeds cap and lacks functional wing evidence',()=>{const definition=catalogDefinition(manifest.boards[25],25),result=validate({outline:definition.outlinePoints,outlineClosed:true});assert.equal(result.ok,false);assert.ok(result.areaMm2>1250);assert.ok(result.errors.includes('wifi-gateway-outline-exceeds-maximum-area'));assert.ok(result.errors.includes('purposeful-antenna-wing-unverified'))})
test('purposeful antenna-wing gateway fits the maximum area',()=>{const result=validate(valid());assert.equal(result.ok,true,result.errors.join('; '));assert.equal(result.areaMm2,1071);assert.equal(result.bounds.width,51);assert.equal(result.bounds.height,24)})
test('wing proportions, neck and enclosure interface fail closed',()=>{const x=valid();x.antennaWing.projectionMm=5;x.antennaWing.neckWidthMm=18;x.antennaWing.enclosureWindowAligned=false;const e=validate(x).errors;assert.ok(e.includes('purposeful-antenna-wing-unverified'));assert.ok(e.includes('antenna-wing-mechanical-interface-unverified'))})
test('RF keepout and transition protect the isolated antenna wing',()=>{const x=valid();x.antennaKeepout.noPlanesTracksOrVias=false;x.antennaKeepout.noMetalFastenersOrCablesInFieldRegion=false;x.rfTransition.crossesNoConnectorOrPowerCorridor=false;const e=validate(x).errors;assert.ok(e.includes('wifi-antenna-wing-keepout-unverified'));assert.ok(e.includes('wifi-antenna-field-clearance-unverified'));assert.ok(e.includes('wifi-rf-transition-unverified'))})
test('connectors, cables and mounting remain opposite the antenna wing',()=>{const x=valid();x.placements.connectors.maxX=15;x.separation.connectorCableExitClearOfWing=false;x.mountingHoles[0].inAntennaWing=true;x.mountingHoles[1].allLayersKeepout=false;const e=validate(x).errors;assert.ok(e.includes('gateway-connectors-not-opposite-antenna-wing'));assert.ok(e.includes('gateway-cable-exit-wing-clearance-unverified'));assert.ok(e.includes('mounting-hole-1-intrudes-antenna-wing'));assert.ok(e.includes('mounting-hole-2-keepout-unverified'))})
